//! Player-facing handlers: `join`, `move_player`, `enter_gate`.
//!
//! These three are everything a browser session key is allowed to do outside of
//! `shoot`. They run **on the ER**, where transaction fees are zero and the forked
//! SVM performs no fee-payer validation at all — nothing debits a spammer, so the
//! only rate limit that exists anywhere is the tick counters written here (D16/R12).
//!
//! Two rules that the rest of this file is shaped around:
//!
//! - **Authority is the whole perimeter.** Every handler asserts
//!   `authority.is_signer && authority == slots[seat].session_pubkey`. There is no
//!   framework check underneath it; one omission is an arena-wide compromise (D17).
//! - **Seats are handed out by the Worker, not claimed by players.** `join` is the
//!   `claim_seat` of `01-architecture.md` §2.3 and is signed by
//!   `arena.crank_authority` (the treasury). If a session key could claim its own
//!   seat, one keypair would take all 20 for free in a single free-of-charge burst
//!   and the raid would never start. The Sybil gate is Privy identity in the Worker;
//!   this handler enforces that the Worker is the one asking.
//!
//! **The seat lifecycle, end to end**, since it spans four files and no one of them shows
//! the whole of it:
//!
//! 1. **Claimed** by `join` (tag 4) into a zeroed slot — [`claim_seat`], which zeroes and
//!    then writes, so a re-used index cannot inherit the last occupant's HP, damage or
//!    death count.
//! 2. **Entered** by `enter_gate` (tag 5), once: `ZONE_LOBBY → ZONE_ARENA` is one-way and
//!    the reverse call is refused, which is what bounds `arena.alive_count`.
//! 3. **Killed and respawned** by `boss_tick`, which owns `hp`, `deaths` and
//!    `respawn_at_tick`. A death does **not** release the seat: the design's death is a
//!    3-second timer, not permadeath (`00-game-design-spec.md` §3), so the session key,
//!    the identity and the accumulated `damage_dealt` all survive it — and must, or a
//!    respawning player would lose their leaderboard row mid-fight. Nothing in this file
//!    frees a seat; there is no unclaim instruction, by design.
//! 4. **Cleared** by `init::next_incarnation` (tag 15) through
//!    [`Players::reset_for_incarnation`], which zeroes all twenty slots on the base layer.
//!    That is the only thing that ever unclaims a seat, and it unclaims all of them at
//!    once. Everyone re-joins for incarnation N+1; `/session/init` is idempotent per
//!    `identity`, so a returning player is re-seated by the path that seats everyone.
//!
//! Coordinates are integers in arena-space units, y down, origin top-left, shared
//! verbatim with `Bullet` and `Boss`. `TILE` units make one map tile. Nothing here
//! is ever a float: the client extrapolates the same integers between ticks, and a
//! float on either side of the boundary reintroduces drift.

use bytemuck::Zeroable;
use pinocchio::{
    error::ProgramError,
    sysvars::{clock::Clock, Sysvar},
    AccountView, Address, ProgramResult,
};

use crate::error::HeartrotError;
use crate::guards::{
    assert_owned_by, assert_pda, assert_session_authority, assert_signer, assert_writable,
};
use crate::map::WALLS;
use crate::state::{
    self, Arena, PlayerSlot, Players, MAX_SEATS, PHASE_FIGHTING, PHASE_LOBBY, SEED_PLAYERS,
    ZONE_ARENA, ZONE_LOBBY,
};

// ---------------------------------------------------------------------------
// Map geometry
// ---------------------------------------------------------------------------

/// Arena-space units per map tile (positions are sub-tile so bullets, whose velocity is
/// an i8, have somewhere to move between ticks; tile indices are `pos / TILE`), and the
/// map edge in tiles — 64, which is exactly one `u64` of wall bits per row.
///
/// Both are re-exported from [`crate::map`] rather than declared a second time here.
/// That module is generated by `tools/gen_map.py` from `assets/map/arena.json` together
/// with the `WALLS` bitboard they size, so the numbers this file indexes with are the
/// numbers the map was compiled from — by construction, not by two copies someone has
/// to keep equal. (`map.rs`'s `const _: () = assert!(TILE == player::TILE)` drift guards
/// still hold; they now compare the re-export against its own definition.)
pub use crate::map::{MAP_TILES, TILE};

/// Highest legal coordinate. Everything written to `x`/`y` is clamped into
/// `0..=MAP_MAX_XY`, which is also what makes the tile index below in-range.
pub const MAP_MAX_XY: i16 = (MAP_TILES as i16) * TILE - 1;

/// The gate tile block, in lobby space: tiles 30..=33 on both axes, which the generated
/// map keeps as open floor inside the heart chamber. Standing inside it is what
/// `enter_gate` requires — the lobby *is* the matchmaker, so the gate has to be a place
/// you walk to and not an API call you make from across the map.
const GATE_MIN_X: i16 = 30 * TILE;
const GATE_MAX_X: i16 = 34 * TILE - 1;
const GATE_MIN_Y: i16 = 30 * TILE;
const GATE_MAX_Y: i16 = 34 * TILE - 1;

/// The lobby entrance and the sideways pitch seats fan out along, so twenty players
/// never stack on one pixel and the client can render a join without waiting for the
/// next crank tick to separate them.
///
/// The *arena* entrance is deliberately not here: `tick::entrance_for` owns it, because
/// that is where `boss_tick` returns a dead player, and walking through the gate has to
/// land in the same place a respawn does.
const LOBBY_ENTRANCE: (i16, i16) = (28 * TILE, 52 * TILE);
const LOBBY_SPACING: i16 = 24;

/// Starting health. Balance number, not a layout number — `hp_max` is per-slot state
/// so an incarnation could scale it later without touching this file.
pub const PLAYER_HP_MAX: u16 = 100;

/// Eight-way step, indexed by `facing`: 0 N, 1 NE, 2 E, 3 SE, 4 S, 5 SW, 6 W, 7 NW,
/// with y increasing downward. The diagonal component is `round(TILE / √2)` so a
/// diagonal move covers the same ground as a straight one — computed here as a
/// constant because the program may never touch a float.
const STEP: i16 = TILE;
const STEP_DIAG: i16 = 11;
const MOVE_STEP: [(i16, i16); 8] = [
    (0, -STEP),
    (STEP_DIAG, -STEP_DIAG),
    (STEP, 0),
    (STEP_DIAG, STEP_DIAG),
    (0, STEP),
    (-STEP_DIAG, STEP_DIAG),
    (-STEP, 0),
    (-STEP_DIAG, -STEP_DIAG),
];

/// `PlayerSlot.session_pubkey` sentinel for "seat never claimed".
const UNCLAIMED: [u8; 32] = [0u8; 32];

/// Tag 4 argument block: `seat` u8 `[0]`, `skin_id` u8 `[1]`, `session_pubkey` `[2..34]`,
/// `identity` `[34..66]`. This slicing *is* the frozen ABI — `instruction.rs` and
/// `docs/architecture/05-wire-abi.md` describe it, and TypeScript conforms to it. When
/// a client disagrees, the client is what changes.
const JOIN_DATA_LEN: usize = 1 + 1 + 32 + 32;

// ---------------------------------------------------------------------------
// Pure geometry helpers
// ---------------------------------------------------------------------------

/// Where seat *n* appears when it joins the lobby: fanned out sideways from the
/// entrance, the same shape `tick::entrance_for` uses on the arena side.
pub fn lobby_spawn(seat: u8) -> (i16, i16) {
    let offset = (seat as i16)
        .saturating_sub(MAX_SEATS as i16 / 2)
        .saturating_mul(LOBBY_SPACING);
    (
        LOBBY_ENTRANCE.0.saturating_add(offset).clamp(0, MAP_MAX_XY),
        LOBBY_ENTRANCE.1.clamp(0, MAP_MAX_XY),
    )
}

/// Write a freshly claimed seat, in place.
///
/// **Zero first, then set the fields whose correct value is not zero.** The ordering is the
/// whole point: assigning the slot field by field is `PlayerSlot`'s field list stored a
/// second time, here, and the second copy is the one that goes stale. It already had —
/// `deaths` was claimed out of `PlayerSlot._pad1` this run, and a field-by-field claim would
/// have carried a previous occupant's death count onto a re-used seat while looking
/// complete. `..PlayerSlot::zeroed()` makes that unrepresentable: a field added to the slot
/// is zero here until someone deliberately names it.
///
/// It is also exactly what [`Players::reset_for_incarnation`] does to all twenty seats, so a
/// seat claimed after a respawn and a seat claimed on a fresh arena are the same bytes.
///
/// Every field left implicit is correct at zero: `facing` 0 is north, `last_move_seq` 0 is
/// "no input yet", `respawn_at_tick` 0 is "not scheduled" (the value `tick::step` reads as
/// unarmed), `damage_dealt` and `deaths` start a leaderboard row at nothing, and both
/// rate-limit stamps start at 0 — legal under the `!=` rule in [`move_clock`], which can
/// only collide in the one slot/tick where the clock also reads 0.
fn claim_seat(
    slot: &mut PlayerSlot,
    seat: u8,
    skin_id: u8,
    session_pubkey: [u8; 32],
    identity: [u8; 32],
) {
    let (x, y) = lobby_spawn(seat);
    *slot = PlayerSlot {
        zone: ZONE_LOBBY,
        skin_id,
        x,
        y,
        hp: PLAYER_HP_MAX,
        hp_max: PLAYER_HP_MAX,
        session_pubkey,
        identity,
        ..PlayerSlot::zeroed()
    };
}

/// Is the tile containing this point solid? Anything off the map counts as wall, so
/// a caller that skips the clamp fails closed rather than indexing out of range.
fn is_wall(x: i16, y: i16) -> bool {
    if x < 0 || y < 0 {
        return true;
    }
    let tx = (x / TILE) as usize;
    let ty = (y / TILE) as usize;
    if tx >= MAP_TILES {
        return true;
    }
    match WALLS.get(ty) {
        Some(row) => row & (1u64 << tx) != 0,
        None => true,
    }
}

fn on_gate(x: i16, y: i16) -> bool {
    (GATE_MIN_X..=GATE_MAX_X).contains(&x) && (GATE_MIN_Y..=GATE_MAX_Y).contains(&y)
}

// ---------------------------------------------------------------------------
// Shared validation
// ---------------------------------------------------------------------------

/// The clock the `move` rate limiter stamps into `last_move_tick`.
///
/// `arena.tick` is the contract's source (D16) and is correct during a fight. It is
/// *not* correct in the lobby: `boss_tick` returns before incrementing unless
/// `phase == PHASE_FIGHTING`, so a tick-only limiter would grant each player exactly
/// one lobby move ever and then freeze them short of the gate — no match could ever
/// start. The ER's 50 ms slot is the only other monotonic counter available on this
/// side of the boundary, so the lobby uses that. The generated dungeon makes this more
/// load-bearing, not less: the walk from a lobby spawn to the gate is now dozens of
/// steps down a corridor rather than a straight line across an empty rectangle.
///
/// The comparison against the stamp is `!=`, not `>`. Swapping sources at the phase
/// flip leaves a stamp from the other clock in the field (a slot number dwarfs a
/// tick), and `>` would then freeze every player for the entire match. Neither clock
/// can be rewound by a caller, so `!=` is exactly as tight: one accepted move per
/// tick while fighting, one per 50 ms slot in the lobby.
///
/// ponytail: `slot as u32` truncates, so one move is dropped every ~2^32 slots
/// (~6.8 years of ER uptime). Widening `last_move_tick` is a layout change; it is
/// not worth one.
fn move_clock(arena: &Arena) -> Result<u32, ProgramError> {
    // The ER slot, in every phase.
    //
    // This used to return `arena.tick` during a fight, and that single line was the whole
    // of "the game feels sluggish": `MOVE_STEP` is one 16-unit tile and the gate is one
    // move per clock unit, so a 400 ms tick capped movement at 2.5 tiles a second across
    // a 64-tile arena — twenty-five seconds to cross it. The lobby, which already used
    // the 50 ms slot, moved eight times faster, so walking to the gate felt fine and the
    // raid itself felt like wading.
    //
    // Raising the crank instead would have worked and cost far more: every tick-denominated
    // constant in the simulation (bullet velocity, RESPAWN_TICKS, the enrage deadline,
    // the shot cooldown) is expressed in ticks and would have to be rescaled together,
    // and the validator would do 4-8x the work to produce a purely visual result that
    // interpolation already provides. The boss simulation is genuinely happy at 400 ms;
    // only the player's input gate needed to be finer than the simulation it feeds.
    //
    // The limiter is not weakened, only re-scaled: still exactly one move per clock unit,
    // and the ER coalesces account notifications to one per 50 ms slot anyway, so this is
    // the finest granularity a client could observe its own move landing at.
    let _ = arena;
    Ok(Clock::get()?.slot as u32)
}

/// Accounts must be validated before any state is touched, and every guard below
/// takes `&AccountView` — which means all of them have to run *before* the `RefMut`
/// borrows, not interleaved with them.
///
/// `players` is bound to `arena` by re-deriving its PDA from the arena address, which
/// is what stops a caller pairing match A's arena with match B's players. `arena`
/// itself is checked by owner + discriminator only: nothing but this program can
/// mint an account it owns, so re-deriving `[b"arena", arena_id]` would buy nothing
/// for ~1.5K CU.
///
/// Returns the arena address, since the `RefMut` on `arena` makes it unreachable
/// afterwards.
fn validate_pair(
    program_id: &Address,
    arena_ai: &AccountView,
    players_ai: &AccountView,
    authority_ai: &AccountView,
    arena_writable: bool,
) -> Result<Address, ProgramError> {
    assert_signer(authority_ai)?;
    assert_writable(players_ai)?;
    if arena_writable {
        assert_writable(arena_ai)?;
    }
    // Inside the ER a delegated account keeps its original owner; on base layer it
    // would be the delegation program. These three handlers only ever run on the ER.
    assert_owned_by(arena_ai, program_id)?;
    assert_owned_by(players_ai, program_id)?;

    let arena_key = *arena_ai.address();
    // `assert_pda` searches for the canonical bump itself (guards.rs) — the stored bump
    // is never a seed. Passing it as one derives a different address entirely, which
    // rejects every legitimate call.
    assert_pda(players_ai, &[SEED_PLAYERS, arena_key.as_ref()], program_id)?;
    Ok(arena_key)
}

/// Quantize the client's requested direction vector to one of the eight `facing`
/// octants, indexing `MOVE_STEP`.
///
/// The wire carries `dx`/`dy` (frozen ABI, tag 6) but the *displacement* is not the
/// client's to choose: only the sign of each component is read, and the step itself
/// comes off `MOVE_STEP` here. That is the "per-tick speed cap" `instruction.rs`
/// defers to the handler — a client that sends (127, 127) moves exactly one diagonal
/// step south-east, the same as one that sends (1, 1). Magnitude is ignored rather
/// than rejected so the caller may send either a unit vector or a full step vector.
///
/// The mapping is the one `app/src/input/controls.ts::dirFromVector` computes with
/// `atan2`, evaluated on the sign quadrant: 0 N, 1 NE, 2 E, 3 SE, 4 S, 5 SW, 6 W,
/// 7 NW, y down. `(0, 0)` is not a direction and is rejected at the boundary.
fn octant(dx: i8, dy: i8) -> Result<u8, ProgramError> {
    Ok(match (dx.signum(), dy.signum()) {
        (0, -1) => 0,
        (1, -1) => 1,
        (1, 0) => 2,
        (1, 1) => 3,
        (0, 1) => 4,
        (-1, 1) => 5,
        (-1, 0) => 6,
        (-1, -1) => 7,
        _ => return Err(ProgramError::InvalidInstructionData),
    })
}

/// The two phases in which a seat may act. Everything else is a fight that is over.
///
/// `LOBBY` and `FIGHTING` are the only phases in which player input means anything, and
/// this is the allow-list rather than a deny-list of the other four for a reason: the phase
/// byte grew from four values to six this run (`PHASE_ROLLING`, `PHASE_ROLLED`), and a
/// handler written as `phase != PHASE_SETTLING && phase != PHASE_SETTLED` would have
/// silently started accepting moves during a VRF roll. An allow-list gains nothing when a
/// phase is appended; a deny-list loses a rule.
///
/// What each refusal prevents:
///
/// - `SETTLING` / `ROLLED`: `outcome` is fixed and the leaderboard will be written from
///   these bytes. A move accepted here changes a match that is already scored.
/// - `ROLLING`: a VRF callback is in flight against this arena. Player writes are not the
///   hazard — committing is — but there is no fight to move in either.
/// - `SETTLED`: the accounts are on their way back to base layer, so the write is either
///   discarded or, worse, lands after the commit snapshot and is silently lost.
///
/// Applied by all three handlers here. `join` and `enter_gate` deliberately accept
/// `FIGHTING` as well as `LOBBY`: late entry is the design's matchmaking (`00-game-design-
/// spec.md` §4 — "the lobby *is* the matchmaker"), all 20 seats exist before the crank is
/// armed so a late seat costs the frozen account list nothing (R15), and a raid that
/// refused reinforcements would punish exactly the player who watched the fight start.
fn assert_playable(phase: u8) -> Result<(), ProgramError> {
    if phase == PHASE_LOBBY || phase == PHASE_FIGHTING {
        Ok(())
    } else {
        Err(HeartrotError::WrongPhase.into())
    }
}

// ---------------------------------------------------------------------------
// join
// ---------------------------------------------------------------------------

/// `join(seat, skin_id, session_pubkey, identity)` — accounts
/// `[arena (w), players (w), treasury (signer)]`.
///
/// Claims the Worker's chosen seat for a browser session key, or rotates the key on the
/// seat this identity already holds. Rejects an occupied seat and rejects a session key
/// that is already seated elsewhere.
pub fn join(program_id: &Address, accounts: &mut [AccountView], data: &[u8]) -> ProgramResult {
    let [arena_ai, players_ai, treasury_ai, ..] = accounts else {
        return Err(ProgramError::NotEnoughAccountKeys);
    };

    if data.len() != JOIN_DATA_LEN {
        return Err(ProgramError::InvalidInstructionData);
    }
    // The Worker picks the seat — it is the thing holding the Privy identity map and the
    // `seat_occupied` read that decided the arena had room. Honouring its choice is what
    // makes the seat it reported to the browser the seat the browser actually gets;
    // picking a different free slot here would hand the client a stale index.
    let seat = data[0];
    let skin_id = data[1];
    let mut session_pubkey = [0u8; 32];
    session_pubkey.copy_from_slice(&data[2..34]);
    let mut identity = [0u8; 32];
    identity.copy_from_slice(&data[34..66]);
    // The all-zero session key is the "unclaimed" sentinel and the all-zero identity
    // is what an unwritten slot carries; accepting either would let two joins collide
    // onto one seat and would make the leaderboard key meaningless.
    if session_pubkey == UNCLAIMED || identity == [0u8; 32] {
        return Err(ProgramError::InvalidInstructionData);
    }

    validate_pair(program_id, arena_ai, players_ai, treasury_ai, true)?;
    let treasury_key = *treasury_ai.address();

    let mut arena_data = arena_ai.try_borrow_mut()?;
    let arena = state::load_mut::<Arena>(&mut arena_data)?;
    assert_playable(arena.phase)?;
    // Seats are administered, not self-served — see the module header.
    if treasury_key.as_ref() != arena.crank_authority.as_slice() {
        return Err(HeartrotError::NotArenaAuthority.into());
    }

    let mut players_data = players_ai.try_borrow_mut()?;
    let players = state::load_mut::<Players>(&mut players_data)?;

    let mut returning: Option<usize> = None;
    for (i, slot) in players.slots.iter().enumerate() {
        if slot.session_pubkey == UNCLAIMED {
            continue;
        }
        // Privy identity is the durable record; the session key is not. A player who
        // cleared their browser storage comes back to this seat with a new key.
        if slot.identity == identity {
            returning = Some(i);
            continue;
        }
        if slot.session_pubkey == session_pubkey {
            return Err(HeartrotError::SessionKeyInUse.into());
        }
    }

    // An identity that is already seated keeps the seat it holds, whatever the Worker
    // asked for: moving a live player to a different index mid-match would strip their
    // position, HP and damage, and `seat_occupied` would then describe two seats.
    if let Some(seat) = returning {
        let slot = players
            .slots
            .get_mut(seat)
            .ok_or(HeartrotError::SeatOutOfRange)?;
        // Key rotation only. Position, HP, zone, damage and both rate-limit stamps
        // belong to the match in progress: someone who lost their browser storage
        // walks back into the fight where they left it, not to the lobby with a
        // cleared score. Writing the same key twice is therefore a no-op, which is
        // what makes `/session/init` safe to retry.
        slot.session_pubkey = session_pubkey;
        slot.skin_id = skin_id;
        return Ok(());
    }

    // `get_mut` is the bounds check — a `seat` of 200 lands here, not in an indexing
    // panic. Requiring the slot to be unclaimed is what stops a second identity being
    // written over a live player: without it the Worker's occupancy read (a base-layer
    // round trip behind the ER) racing two joins onto one index would silently evict
    // whoever got there first. The two failures carry different codes because they mean
    // different things to the Worker: `SeatOutOfRange` is its own bug, `SeatOccupied` is
    // a lost race it should retry on another seat.
    let slot = players
        .slots
        .get_mut(seat as usize)
        .ok_or(HeartrotError::SeatOutOfRange)?;
    if slot.session_pubkey != UNCLAIMED {
        return Err(HeartrotError::SeatOccupied.into());
    }
    claim_seat(slot, seat, skin_id, session_pubkey, identity);

    // The bitmask is the Worker's cheap read of occupancy; `session_pubkey` above is
    // the authority. They are written together so they cannot drift.
    arena.seat_occupied |= 1u32 << seat;
    Ok(())
}

// ---------------------------------------------------------------------------
// move
// ---------------------------------------------------------------------------

/// `move(seat, seq, dx, dy)` — accounts `[arena (r), players (w), session key (signer)]`.
///
/// `move` is a Rust keyword, hence the name.
pub fn move_player(
    program_id: &Address,
    accounts: &mut [AccountView],
    data: &[u8],
) -> ProgramResult {
    let [arena_ai, players_ai, authority_ai, ..] = accounts else {
        return Err(ProgramError::NotEnoughAccountKeys);
    };

    // The slice pattern is the exact-length gate: five argument bytes, no more and no
    // fewer. A short block is somebody probing for an index panic and a long one is
    // client/program skew, and neither is accepted quietly.
    let &[seat, seq_lo, seq_hi, dx_req, dy_req] = data else {
        return Err(ProgramError::InvalidInstructionData);
    };
    let seq = u16::from_le_bytes([seq_lo, seq_hi]);
    // The client asks for a direction; the chain decides how far that is.
    let dir = octant(dx_req as i8, dy_req as i8)?;
    // `octant` only ever answers 0..7, but indexing with `[]` would still compile in a
    // panic branch — and a BPF panic is an abort with no error to read.
    let (dx, dy) = *MOVE_STEP
        .get(dir as usize)
        .ok_or(ProgramError::InvalidInstructionData)?;

    // `arena` stays read-only here: a move must not rewrite the 1,160-byte account
    // the whole lobby is subscribed to.
    validate_pair(program_id, arena_ai, players_ai, authority_ai, false)?;

    let now = {
        let arena_data = arena_ai.try_borrow()?;
        let arena = state::load::<Arena>(&arena_data)?;
        assert_playable(arena.phase)?;
        move_clock(arena)?
    };

    let mut players_data = players_ai.try_borrow_mut()?;
    let players = state::load_mut::<Players>(&mut players_data)?;
    // `get_mut` bounds-checks the client's seat index, and `assert_session_authority` is
    // the *entire* security perimeter behind it: this signer must be the session key
    // stored on the seat being moved. The index is untrusted; the signature is not.
    // (`assert_session_authority` also rejects the unclaimed sentinel, so an empty seat
    // can never be driven — see guards.rs.)
    let slot = players
        .slots
        .get_mut(seat as usize)
        .ok_or(HeartrotError::SeatOutOfRange)?;
    assert_session_authority(slot, authority_ai)?;

    // A dead player is `boss_tick`'s to move: it owns `respawn_at_tick` and the
    // return to the entrance.
    if slot.hp == 0 {
        return Err(HeartrotError::PlayerDead.into());
    }

    // The rate limit. ER fees are zero, so this counter is the only thing standing
    // between one keypair and an unbounded flood (D16/R12).
    if slot.last_move_tick == now {
        return Err(HeartrotError::RateLimited.into());
    }

    // Walls are the real dungeon out of `crate::map`, not a border ring: a corridor
    // mouth or a pillar rejects the step here exactly as the client's copy of the same
    // generated grid predicted it would.
    let nx = slot.x.saturating_add(dx).clamp(0, MAP_MAX_XY);
    let ny = slot.y.saturating_add(dy).clamp(0, MAP_MAX_XY);
    if is_wall(nx, ny) {
        return Err(HeartrotError::BlockedByWall.into());
    }

    slot.x = nx;
    slot.y = ny;
    slot.facing = dir;
    // Echo the client's sequence number back. Without it an arriving position is
    // ambiguous as to which input produced it and prediction cannot be reconciled;
    // the symptom is rubber-banding for every player (D14).
    slot.last_move_seq = seq;
    slot.last_move_tick = now;
    Ok(())
}

// ---------------------------------------------------------------------------
// enter_gate
// ---------------------------------------------------------------------------

/// `enter_gate(seat)` — accounts `[arena (w), players (w), session key (signer)]`.
///
/// Flips the seat from lobby to arena and teleports it to the arena entrance.
///
/// The only player-callable handler here with no tick counter, and it does not need one:
/// the `zone != ZONE_LOBBY` refusal below makes it one-shot per seat per incarnation, so a
/// flood of repeats is a flood of rejections that write nothing — where `move` and `shoot`
/// would each succeed, every time, at zero fee. That refusal is therefore load-bearing
/// twice over: it is the rate limit *and* the `alive_count` bound.
pub fn enter_gate(
    program_id: &Address,
    accounts: &mut [AccountView],
    data: &[u8],
) -> ProgramResult {
    let [arena_ai, players_ai, authority_ai, ..] = accounts else {
        return Err(ProgramError::NotEnoughAccountKeys);
    };

    // Tag 5 is not in `lib.rs::ZERO_ARG_TAGS`, so a trailing payload reaches this
    // handler and this is the only place that can refuse it. One argument byte, exactly.
    let &[seat] = data else {
        return Err(ProgramError::InvalidInstructionData);
    };

    validate_pair(program_id, arena_ai, players_ai, authority_ai, true)?;

    let mut arena_data = arena_ai.try_borrow_mut()?;
    let arena = state::load_mut::<Arena>(&mut arena_data)?;
    assert_playable(arena.phase)?;

    let mut players_data = players_ai.try_borrow_mut()?;
    let players = state::load_mut::<Players>(&mut players_data)?;
    let seat = seat as usize;
    // Same perimeter as `move_player`: the index is bounds-checked, the signature is
    // what proves the caller owns the seat.
    let slot = players
        .slots
        .get_mut(seat)
        .ok_or(HeartrotError::SeatOutOfRange)?;
    assert_session_authority(slot, authority_ai)?;

    // One direction only. Coming back out is `phase == Settled`, not an instruction —
    // and rejecting the repeat is what keeps `alive_count` from being incremented
    // twice by one player, which would inflate `bullets_per_volley` for everyone.
    if slot.zone != ZONE_LOBBY {
        return Err(HeartrotError::WrongZone.into());
    }
    // The client retries this instruction while the player walks onto the tile, so
    // "not there yet" must be tellable apart from every other gate failure.
    if !on_gate(slot.x, slot.y) {
        return Err(HeartrotError::NotOnGate.into());
    }
    // Aliveness is derived as `hp != 0 && zone == ZONE_ARENA`, so a seat with a zero
    // `hp_max` would count toward `alive_count` while never being alive. `join`
    // always sets it; this is the assertion that says so.
    if slot.hp_max == 0 {
        return Err(ProgramError::InvalidAccountData);
    }

    // `boss_tick` owns the arena entrance; a second definition here would read as a
    // teleport bug the first time anyone died.
    let (x, y) = crate::handlers::tick::entrance_for(seat);
    slot.zone = ZONE_ARENA;
    slot.x = x;
    slot.y = y;
    slot.facing = 0;
    slot.hp = slot.hp_max;
    slot.respawn_at_tick = 0;

    // Cap rather than wrap: `alive_count` drives `bullets_per_volley = 3 + alive_count`,
    // and a wrapped count would fill the pool on the next volley.
    arena.alive_count = arena.alive_count.saturating_add(1).min(MAX_SEATS as u8);
    Ok(())
}

// ---------------------------------------------------------------------------
// Checks
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::{PHASE_ROLLED, PHASE_ROLLING, PHASE_SETTLED, PHASE_SETTLING};

    /// A seat index is re-used forever — twenty of them serve every incarnation of an arena
    /// — so a claim that leaves one field of the previous occupant behind is a scoreboard
    /// that lies and a rate limiter that starts pre-armed. `deaths` is the concrete case:
    /// it was `PlayerSlot._pad1` until this run, and a field-by-field claim would have gone
    /// on looking complete while carrying a dead player's count onto a new one.
    #[test]
    fn a_seat_claim_cannot_inherit_the_last_occupant() {
        let mut used = PlayerSlot::zeroed();
        used.zone = ZONE_ARENA;
        used.facing = 5;
        used.hp = 0;
        used.deaths = 9;
        used.damage_dealt = 12_345;
        used.respawn_at_tick = 700;
        used.last_move_tick = 700;
        used.last_shot_tick = 699;
        used.last_move_seq = 4_000;

        claim_seat(&mut used, 3, 7, [1u8; 32], [2u8; 32]);

        assert_eq!(used.session_pubkey, [1u8; 32]);
        assert_eq!(used.identity, [2u8; 32]);
        assert_eq!(used.skin_id, 7);
        assert_eq!(used.zone, ZONE_LOBBY);
        assert_eq!((used.hp, used.hp_max), (PLAYER_HP_MAX, PLAYER_HP_MAX));
        assert_eq!((used.x, used.y), lobby_spawn(3));

        // The whole point, stated as bytes rather than as a list of fields: a re-used seat
        // and a never-used one are indistinguishable. A field added to `PlayerSlot` and
        // forgotten here fails this line — a per-field assertion would not, since it would
        // be the same forgotten list a second time.
        let mut fresh = PlayerSlot::zeroed();
        claim_seat(&mut fresh, 3, 7, [1u8; 32], [2u8; 32]);
        assert_eq!(bytemuck::bytes_of(&used), bytemuck::bytes_of(&fresh));
        assert_eq!((used.deaths, used.damage_dealt, used.respawn_at_tick), (0, 0, 0));
        assert_eq!((used.last_move_tick, used.last_shot_tick), (0, 0));
    }

    /// The phase gate, over the whole 6-value phase byte and past the end of it.
    ///
    /// Player input is legal in exactly two phases. The four refusals are one rule with
    /// four reasons (see [`assert_playable`]); walking every value is what stops the next
    /// appended phase from defaulting to "playable".
    #[test]
    fn only_a_live_match_accepts_player_input() {
        assert!(assert_playable(PHASE_LOBBY).is_ok());
        assert!(assert_playable(PHASE_FIGHTING).is_ok(), "late entry is the matchmaker");

        for phase in [
            PHASE_SETTLING,
            PHASE_SETTLED,
            PHASE_ROLLING,
            PHASE_ROLLED,
            PHASE_ROLLED + 1,
            u8::MAX,
        ] {
            assert_eq!(
                assert_playable(phase).unwrap_err(),
                HeartrotError::WrongPhase.into(),
                "phase {phase} accepted input into a fight that is over",
            );
        }

        // The move limiter runs off the ER slot in EVERY phase, so a fight is gated at
        // 50 ms rather than at the 400 ms crank tick. That is the whole difference between
        // 2.5 tiles a second and twenty.
        //
        // The slot arrives through a syscall that does not exist off chain, so the host
        // cannot read a value here — but it CAN prove the branch is gone. Under the old
        // code a fighting arena returned `arena.tick` without touching a sysvar, so
        // seeing the sysvar error is exactly the evidence that a fight no longer reads
        // the tick. Asserting `Ok(41)` here is what would mean the regression came back.
        let mut arena = Arena::zeroed();
        arena.phase = PHASE_FIGHTING;
        arena.tick = 41;
        assert_eq!(
            move_clock(&arena),
            Err(ProgramError::UnsupportedSysvar),
            "a fight must read the ER slot, never arena.tick",
        );
    }

    /// Incarnation N+1 must hand `join` twenty claimable seats and no live key.
    ///
    /// This is the only thing that ever unclaims a seat, and it is not in this file — so
    /// what is asserted here is the interface `join` and `guards::assert_session_authority`
    /// depend on: after the reset every slot carries the all-zero sentinel, which is
    /// simultaneously "claimable" to `join` and "authorizes nobody" to the guard. A reset
    /// that left a session key behind would leave a closed browser's key able to drive a
    /// seat in a fight its owner never entered.
    #[test]
    fn an_incarnation_reset_unclaims_every_seat() {
        let mut players = Players::zeroed();
        for seat in 0..MAX_SEATS as u8 {
            let key = [seat.wrapping_add(1); 32];
            let slot = players.slots.get_mut(seat as usize).expect("seat in range");
            claim_seat(slot, seat, 0, key, key);
            slot.deaths = 3;
            slot.damage_dealt = 500;
        }
        assert!(players.slots.iter().all(|s| s.session_pubkey != UNCLAIMED));

        players.reset_for_incarnation();

        assert!(players.slots.iter().all(|s| s.session_pubkey == UNCLAIMED));
        assert!(players.slots.iter().all(|s| s.identity == [0u8; 32]));
        assert!(players
            .slots
            .iter()
            .all(|s| s.deaths == 0 && s.damage_dealt == 0 && s.hp == 0));
    }

    #[test]
    fn geometry_holds() {
        // Every spawn is inside the map, on open floor, and unique per seat. The arena
        // side is `tick`'s point, checked here because this is where the wall test lives
        // and `tick` cannot see it: a spawn or a gate that lands a player inside the
        // generated dungeon leaves them unable to move at all, in any direction.
        let mut seen = [(0i16, 0i16); MAX_SEATS];
        for seat in 0..MAX_SEATS as u8 {
            for (x, y) in [
                lobby_spawn(seat),
                crate::handlers::tick::entrance_for(seat as usize),
            ] {
                assert!((0..=MAP_MAX_XY).contains(&x) && (0..=MAP_MAX_XY).contains(&y));
                assert!(!is_wall(x, y), "seat {seat} spawns in a wall");
            }
            let p = lobby_spawn(seat);
            assert!(!seen[..seat as usize].contains(&p), "seat {seat} stacks");
            seen[seat as usize] = p;
        }

        // The outer ring is closed.
        assert!(is_wall(0, 0) && is_wall(MAP_MAX_XY, MAP_MAX_XY));
        assert!(is_wall(500, MAP_MAX_XY) && is_wall(0, 500));
        assert!(!is_wall(TILE, TILE));
        // Off-map fails closed rather than indexing out of range.
        assert!(is_wall(-1, 0) && is_wall(0, -1) && is_wall(MAP_MAX_XY + 1, 0));

        // The interior is a dungeon, not an empty rectangle. Tile (24, 16) is inside the
        // rock that flanks the north corridor, and tile (32, 32) is the heart the boss
        // spawns on. If `crate::map::WALLS` ever regresses to a bare border ring the
        // first of these flips and the difficulty system is silently gone again.
        assert!(is_wall(24 * TILE, 16 * TILE), "interior has no walls");
        assert!(!is_wall(32 * TILE, 32 * TILE), "boss spawns in a wall");
        // The 2-tile corridor into the heart is open along its whole length — a corridor
        // sealed by a pillar would leave the gate unreachable and no match could start.
        for ty in 15..=23 {
            assert!(!is_wall(31 * TILE, ty * TILE), "north corridor blocked at {ty}");
            assert!(!is_wall(32 * TILE, ty * TILE), "north corridor blocked at {ty}");
        }

        // Walking into the ring is clamped in bounds and then rejected as wall, and
        // the clamp itself never overflows at the i16 extremes.
        for (dx, dy) in MOVE_STEP {
            let nx = i16::MAX.saturating_add(dx).clamp(0, MAP_MAX_XY);
            let ny = i16::MIN.saturating_add(dy).clamp(0, MAP_MAX_XY);
            assert!((0..=MAP_MAX_XY).contains(&nx) && (0..=MAP_MAX_XY).contains(&ny));
        }
        assert!(is_wall(
            TILE.saturating_add(MOVE_STEP[6].0).clamp(0, MAP_MAX_XY),
            TILE
        ));

        // Diagonals cover the same ground as straights, within one unit.
        for (dx, dy) in MOVE_STEP {
            let d2 = (dx as i32) * (dx as i32) + (dy as i32) * (dy as i32);
            let straight = (STEP as i32) * (STEP as i32);
            assert!((d2 - straight).abs() <= 2 * STEP as i32);
        }

        // `octant` must agree with `MOVE_STEP` on all eight directions, or the chain
        // walks a player somewhere other than where the client predicted and every
        // move rubber-bands. Feeding each step vector back through the quantizer is
        // the round trip: sign-only, so magnitude cannot matter.
        for (dir, (dx, dy)) in MOVE_STEP.iter().enumerate() {
            assert_eq!(octant(dx.signum() as i8, dy.signum() as i8), Ok(dir as u8));
            // Any vector in the same sign quadrant resolves to the same step.
            let scaled = octant((*dx as i32 * 7).signum() as i8, (*dy as i32 * 7).signum() as i8);
            assert_eq!(scaled, Ok(dir as u8), "magnitude changed the direction");
        }
        // The `atan2` mapping in app/src/input/controls.ts, spot-checked: north is 0
        // (y grows *down*, so north is negative dy) and the octants run clockwise.
        assert_eq!(octant(0, -1), Ok(0));
        assert_eq!(octant(127, -127), Ok(1));
        assert_eq!(octant(i8::MIN, 0), Ok(6));
        // Standing still is not a direction.
        assert!(octant(0, 0).is_err());

        // The gate is reachable: it is inside the map and not a wall.
        assert!(on_gate(GATE_MIN_X, GATE_MIN_Y) && on_gate(GATE_MAX_X, GATE_MAX_Y));
        assert!(!on_gate(GATE_MIN_X - 1, GATE_MIN_Y) && !on_gate(GATE_MAX_X + 1, GATE_MAX_Y));
        assert!(!is_wall(GATE_MIN_X, GATE_MIN_Y) && !is_wall(GATE_MAX_X, GATE_MAX_Y));
    }
}
