//! Player-facing handlers: `join`, `move_player`, `enter_gate`.
//!
//! These three are everything a browser session key is allowed to do outside of
//! `shoot`. They run **on the ER**, where transaction fees are zero and the forked
//! SVM performs no fee-payer validation at all — nothing debits a spammer, so the
//! only rate limit that exists anywhere is the tick counters written here (D16/R12).
//!
//! Two rules that the rest of this file is shaped around:
//!
//! - **Authority is the whole perimeter.** Every handler asserts
//!   `authority.is_signer && authority == slots[seat].session_pubkey`. There is no
//!   framework check underneath it; one omission is an arena-wide compromise (D17).
//! - **Seats are handed out by the Worker, not claimed by players.** `join` is the
//!   `claim_seat` of `01-architecture.md` §2.3 and is signed by
//!   `arena.crank_authority` (the treasury). If a session key could claim its own
//!   seat, one keypair would take all 20 for free in a single free-of-charge burst
//!   and the raid would never start. The Sybil gate is Privy identity in the Worker;
//!   this handler enforces that the Worker is the one asking.
//!
//! **The seat lifecycle, end to end**, since it spans four files and no one of them shows
//! the whole of it:
//!
//! 1. **Claimed** by `join` (tag 4) into a zeroed slot — [`claim_seat`], which zeroes and
//!    then writes, so a re-used index cannot inherit the last occupant's HP, damage or
//!    death count.
//! 2. **Entered** by `enter_gate` (tag 5), once: `ZONE_LOBBY → ZONE_ARENA` is one-way and
//!    the reverse call is refused, which is what bounds `arena.alive_count`.
//! 3. **Killed and respawned** by `boss_tick`, which owns `hp`, `deaths` and
//!    `respawn_at_tick`. A death does **not** release the seat: the design's death is a
//!    3-second timer, not permadeath (`00-game-design-spec.md` §3), so the session key,
//!    the identity and the accumulated `damage_dealt` all survive it — and must, or a
//!    respawning player would lose their leaderboard row mid-fight. Nothing in this file
//!    frees a seat; there is no unclaim instruction, by design.
//! 4. **Cleared** by `init::next_incarnation` (tag 15) through
//!    [`Players::reset_for_incarnation`], which zeroes all twenty slots on the base layer.
//!    That is the only thing that ever unclaims a seat, and it unclaims all of them at
//!    once. Everyone re-joins for incarnation N+1; `/session/init` is idempotent per
//!    `identity`, so a returning player is re-seated by the path that seats everyone.
//!
//! Coordinates are integers in arena-space units, y down, origin top-left, shared
//! verbatim with `Bullet` and `Boss`. `TILE` units make one map tile. Nothing here
//! is ever a float: the client extrapolates the same integers between ticks, and a
//! float on either side of the boundary reintroduces drift.

use bytemuck::Zeroable;
use pinocchio::{
    error::ProgramError,
    sysvars::{clock::Clock, Sysvar},
    AccountView, Address, ProgramResult,
};

use crate::error::HeartrotError;
use crate::guards::{
    assert_owned_by, assert_pda, assert_session_authority, assert_signer, assert_writable,
};
use crate::map::{GATE_MAX_X, GATE_MAX_Y, GATE_MIN_X, GATE_MIN_Y, PIT_BOT, PIT_TOP, WALLS};
use crate::state::{
    self, Arena, PlayerSlot, Players, MAX_SEATS, N_CLASSES, PHASE_FIGHTING, PHASE_LOBBY,
    PHASE_MUSTERING, SEED_PLAYERS, ZONE_ARENA, ZONE_LOBBY,
};

// ---------------------------------------------------------------------------
// Map geometry
// ---------------------------------------------------------------------------

/// Arena-space units per map tile (positions are sub-tile so bullets, whose velocity is
/// an i8, have somewhere to move between ticks; tile indices are `pos / TILE`), and the
/// map edge in tiles — 64, which is exactly one `u64` of wall bits per row.
///
/// Both are re-exported from [`crate::map`] rather than declared a second time here.
/// That module is generated by `tools/gen_map.py` from `assets/map/arena.json` together
/// with the `WALLS` bitboard they size, so the numbers this file indexes with are the
/// numbers the map was compiled from — by construction, not by two copies someone has
/// to keep equal. (`map.rs`'s `const _: () = assert!(TILE == player::TILE)` drift guards
/// still hold; they now compare the re-export against its own definition.)
pub use crate::map::{MAP_TILES, TILE};

/// Highest legal coordinate. Everything written to `x`/`y` is clamped into
/// `0..=MAP_MAX_XY`, which is also what makes the tile index below in-range.
pub const MAP_MAX_XY: i16 = (MAP_TILES as i16) * TILE - 1;

// The gate block (`GATE_MIN_X`..=`GATE_MAX_Y`) and the pit box (`PIT_TOP`/`PIT_BOT`) are
// imported from `crate::map`, not declared here.
//
// They used to be six literals in this file, and `tools/gen_map.py` parsed them back out
// of this source to check the grid it had just emitted — one fact stored twice, in the
// two places least able to notice they had drifted. They are `G` and `P` marks in
// `assets/map/arena.json` now, so the tiles `enter_gate` accepts are the tiles the map
// was compiled from, and `map.rs`'s const-assert block can prove `BOSS_SPAWN` is outside
// the gate on every `cargo check`.
//
// Standing inside the gate block is what `enter_gate` requires — the lobby *is* the
// matchmaker, so the gate has to be a place you walk to and not an API call you make from
// across the map.

/// The lobby entrance and the sideways pitch seats fan out along, so twenty players
/// never stack on one pixel and the client can render a join without waiting for the
/// next crank tick to separate them.
///
/// The *arena* entrance is deliberately not here: `tick::entrance_for` owns it, because
/// that is where `boss_tick` returns a dead player, and walking through the gate has to
/// land in the same place a respawn does.
const LOBBY_ENTRANCE: (i16, i16) = (28 * TILE, 52 * TILE);
const LOBBY_SPACING: i16 = 24;

/// Starting health. Balance number, not a layout number — `hp_max` is per-slot state
/// so an incarnation could scale it later without touching this file.
pub const PLAYER_HP_MAX: u16 = 100;

/// Eight-way step, indexed by `facing`: 0 N, 1 NE, 2 E, 3 SE, 4 S, 5 SW, 6 W, 7 NW,
/// with y increasing downward. The diagonal component is `round(TILE / √2)` so a
/// diagonal move covers the same ground as a straight one — computed here as a
/// constant because the program may never touch a float.
const STEP: i16 = TILE;
const STEP_DIAG: i16 = 11;
const MOVE_STEP: [(i16, i16); 8] = [
    (0, -STEP),
    (STEP_DIAG, -STEP_DIAG),
    (STEP, 0),
    (STEP_DIAG, STEP_DIAG),
    (0, STEP),
    (-STEP_DIAG, STEP_DIAG),
    (-STEP, 0),
    (-STEP_DIAG, -STEP_DIAG),
];

/// `PlayerSlot.session_pubkey` sentinel for "seat never claimed".
const UNCLAIMED: [u8; 32] = [0u8; 32];

/// Tag 4 argument block: `seat` u8 `[0]`, `skin_id` u8 `[1]`, `session_pubkey` `[2..34]`,
/// `identity` `[34..66]`, `class` u8 `[66]`. This slicing *is* the frozen ABI —
/// `instruction.rs` and `docs/architecture/05-wire-abi.md` describe it, and TypeScript
/// conforms to it. When a client disagrees, the client is what changes.
///
/// `class` is **appended**, not packed beside `skin_id`, so no existing offset moves and
/// both 32-byte slices are untouched (`17-fullscreen-spec.md` §5.4). The only thing a
/// client built against the 66-byte block gets wrong is the length, which is a clean
/// `InvalidInstructionData` here rather than a misread byte somewhere downstream. That
/// makes the program, the app and the Worker one indivisible deploy, deliberately.
const JOIN_DATA_LEN: usize = 1 + 1 + 32 + 32 + 1;

// ---------------------------------------------------------------------------
// Pure geometry helpers
// ---------------------------------------------------------------------------

/// Where seat *n* appears when it joins the lobby: fanned out sideways from the
/// entrance, the same shape `tick::entrance_for` uses on the arena side.
pub fn lobby_spawn(seat: u8) -> (i16, i16) {
    let offset = (seat as i16)
        .saturating_sub(MAX_SEATS as i16 / 2)
        .saturating_mul(LOBBY_SPACING);
    (
        LOBBY_ENTRANCE.0.saturating_add(offset).clamp(0, MAP_MAX_XY),
        LOBBY_ENTRANCE.1.clamp(0, MAP_MAX_XY),
    )
}

/// Write a freshly claimed seat, in place.
///
/// **Zero first, then set the fields whose correct value is not zero.** The ordering is the
/// whole point: assigning the slot field by field is `PlayerSlot`'s field list stored a
/// second time, here, and the second copy is the one that goes stale. It already had —
/// `deaths` was claimed out of `PlayerSlot._pad1` this run, and a field-by-field claim would
/// have carried a previous occupant's death count onto a re-used seat while looking
/// complete. `..PlayerSlot::zeroed()` makes that unrepresentable: a field added to the slot
/// is zero here until someone deliberately names it.
///
/// It is also exactly what [`Players::reset_for_incarnation`] does to all twenty seats, so a
/// seat claimed after a respawn and a seat claimed on a fresh arena are the same bytes.
///
/// Every field left implicit is correct at zero: `facing` 0 is north, `last_move_seq` 0 is
/// "no input yet", `respawn_at_tick` 0 is "not scheduled" (the value `tick::step` reads as
/// unarmed), `damage_dealt` and `deaths` start a leaderboard row at nothing, and both
/// rate-limit stamps start at 0 — legal under the `!=` rule in [`move_clock`], which can
/// only collide in the one slot/tick where the clock also reads 0.
fn claim_seat(
    slot: &mut PlayerSlot,
    seat: u8,
    skin_id: u8,
    class: u8,
    session_pubkey: [u8; 32],
    identity: [u8; 32],
) -> Result<(), ProgramError> {
    let (x, y) = lobby_spawn(seat);
    *slot = PlayerSlot {
        zone: ZONE_LOBBY,
        skin_id,
        x,
        y,
        hp: PLAYER_HP_MAX,
        hp_max: PLAYER_HP_MAX,
        session_pubkey,
        identity,
        ..PlayerSlot::zeroed()
    };
    // The class is written through `PlayerSlot::set_class` rather than by masking the byte
    // here, because that byte is shared with the aim `shoot::fire` writes and one encoder
    // is the only way the two halves cannot be typed differently in two files. On a slot
    // that was just zeroed the aim it preserves is 0, which is what a seat that has fired
    // no shot should carry.
    slot.set_class(class)
}

/// Is the tile containing this point solid? Anything off the map counts as wall, so
/// a caller that skips the clamp fails closed rather than indexing out of range.
fn is_wall(x: i16, y: i16) -> bool {
    if x < 0 || y < 0 {
        return true;
    }
    let tx = (x / TILE) as usize;
    let ty = (y / TILE) as usize;
    if tx >= MAP_TILES {
        return true;
    }
    match WALLS.get(ty) {
        Some(row) => row & (1u64 << tx) != 0,
        None => true,
    }
}

fn on_gate(x: i16, y: i16) -> bool {
    (GATE_MIN_X..=GATE_MAX_X).contains(&x) && (GATE_MIN_Y..=GATE_MAX_Y).contains(&y)
}

/// The y range a seat in `zone` may stand in. The *second* kind of barrier in this
/// program, and the one that is not made of tiles.
///
/// A raider is held inside `PIT_TOP..=PIT_BOT` by two comparisons rather than by wall
/// tiles, because the rows above the pit cannot be wall: `shoot::raycast` tests `is_wall`
/// before the part rectangles, so one solid tile between a player and the boss kills every
/// shot in that column. The pit ceiling is a movement rule laid over open floor.
///
/// - `PIT_TOP` stops a raider walking up into the boss's head.
/// - `PIT_BOT` stops a raider retreating down the gate corridor. Not tidiness:
///   `tick::spawn_volley` aims at the nearest live player, so one camper at the corridor
///   mouth makes the boss spend every volley on a target the rim shields.
///
/// **The two boxes tile the map at the gate seam and neither zone is unbounded.** The
/// lobby used to be — `zone != ZONE_ARENA` short-circuited the whole test — on the
/// argument that the lobby half is bounded by real walls. It is not: rows 1..23 are
/// deliberately open floor so `raycast` survives, so a `ZONE_LOBBY` seat could walk out of
/// the temple, up the pit and stand inside the boss's crown (measured: 445,696 reachable
/// positions, minimum y = 16, tile row 1). Such a seat is invisible to every mechanic —
/// not in `live`, never targeted, unslammable, cannot shoot — and every client draws it
/// standing in the creature. The lobby box is therefore `PIT_BOT + 1 ..= MAP_MAX_XY`:
/// everything below the rim, which is the whole lobby half and the gate.
///
/// The seam is exactly one unit wide and `map.rs` const-asserts it (`GATE_MIN_Y ==
/// PIT_BOT + 1`), which is what makes the flip safe in both directions: the doorway rows
/// are inside the *lobby* box, the entrance rows are inside the *arena* box, and
/// `enter_gate` teleports across the seam rather than stepping over it. If the two boxes
/// left a gap, a player who flipped zone standing on the gate tiles would be outside the
/// only legal y range with no legal move in any direction — a hard freeze with no error
/// anywhere.
fn zone_box(zone: u8) -> (i16, i16) {
    if zone == ZONE_ARENA {
        (PIT_TOP, PIT_BOT)
    } else {
        (PIT_BOT + 1, MAP_MAX_XY)
    }
}

/// How far outside its box a seat in `zone` standing at `y` is; 0 when it is inside.
///
/// `saturating_sub` because a corrupt or stale `y` is a caller's byte, not a panic: every
/// write clamps into `0..=MAP_MAX_XY`, but this program runs with `overflow-checks = true`
/// and an abort has no error code to read.
fn box_overshoot(zone: u8, y: i16) -> i16 {
    let (top, bot) = zone_box(zone);
    top.saturating_sub(y).max(y.saturating_sub(bot)).max(0)
}

/// May a seat in `zone` step from `y` to `ny`? The destination must be inside the zone's
/// box — **or** strictly closer to it than where the seat already stands.
///
/// That second clause is the un-stranding rule, and it is why this is not a bare range
/// test. Narrowing a box under a live account (which this fix does: yesterday's program
/// let a lobby seat stand at y = 16) leaves seats outside the box that were legal when
/// they were written, and a bare destination test freezes every one of them — no direction
/// helps, including the one pointing home, because a sideways step keeps the same illegal
/// y. Trading the freeze for a bounded walk back is strictly better: the overshoot is a
/// non-negative integer that must *decrease* every step, so the escape terminates inside
/// the box and cannot be ridden in the other direction.
fn may_move_to(zone: u8, y: i16, ny: i16) -> bool {
    // A stranded seat is governed by walls ALONE until it re-enters its box.
    //
    // The strictly-decreasing-overshoot rule this replaces could not be satisfied at every
    // stranded position: `move_player` demands `!is_wall(nx, ny) && may_move_to(..)`, and a
    // replay of both predicates over the generated `WALLS` found 4,620 stale lobby positions
    // where no step is both non-wall and overshoot-decreasing. Those seats froze on their
    // first move attempt, with no error to distinguish it from a wall.
    //
    // Letting a stranded seat move freely cannot freeze anyone that walls alone do not,
    // because it is exactly the rule the previous program applied to these seats — the one
    // that let them stand here. It is one-way in the direction that matters: `box_overshoot`
    // is 0 everywhere inside the box, so once a seat is home `over(ny) == 0` is the only
    // clause that can hold and it can never step back out.
    box_overshoot(zone, y) > 0 || box_overshoot(zone, ny) == 0
}

/// The three refusals `enter_gate` owes a caller, as a pure function of the seat.
///
/// Split out of the handler so the gate's rules are testable without an `AccountView`:
/// this *is* the "one-way, on the tiles, and only a real seat" contract, and every one of
/// the three is load-bearing (see [`enter_gate`]).
fn gate_refusal(slot: &PlayerSlot) -> Result<(), ProgramError> {
    // One direction only. Coming back out is `phase == Settled`, not an instruction —
    // and rejecting the repeat is what keeps `alive_count` from being incremented
    // twice by one player, which would inflate `bullets_per_volley` for everyone. It is
    // also the rate limit: `enter_gate` has no tick counter and needs none, because a
    // flood of repeats is a flood of rejections that write nothing.
    if slot.zone != ZONE_LOBBY {
        return Err(HeartrotError::WrongZone.into());
    }
    // The client retries this instruction while the player walks onto the tile, so
    // "not there yet" must be tellable apart from every other gate failure.
    if !on_gate(slot.x, slot.y) {
        return Err(HeartrotError::NotOnGate.into());
    }
    // Aliveness is derived as `hp != 0 && zone == ZONE_ARENA`, so a seat with a zero
    // `hp_max` would count toward `alive_count` while never being alive. `join`
    // always sets it; this is the assertion that says so.
    if slot.hp_max == 0 {
        return Err(ProgramError::InvalidAccountData);
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Shared validation
// ---------------------------------------------------------------------------

/// The clock the `move` rate limiter stamps into `last_move_tick`.
///
/// `arena.tick` is the contract's source (D16) and is correct during a fight. It is
/// *not* correct in the lobby: `boss_tick` returns before incrementing unless
/// `phase == PHASE_FIGHTING`, so a tick-only limiter would grant each player exactly
/// one lobby move ever and then freeze them short of the gate — no match could ever
/// start. The ER's 50 ms slot is the only other monotonic counter available on this
/// side of the boundary, so the lobby uses that. The open arena makes this more
/// load-bearing, not less: the lobby is now 60x20 tiles of unobstructed floor and the
/// gate is one 8-tile slot in the far wall, so the walk to it is a long straight run
/// that a one-move-per-400 ms limiter would turn back into wading.
///
/// The comparison against the stamp is `!=`, not `>`. Swapping sources at the phase
/// flip leaves a stamp from the other clock in the field (a slot number dwarfs a
/// tick), and `>` would then freeze every player for the entire match. Neither clock
/// can be rewound by a caller, so `!=` is exactly as tight: one accepted move per
/// tick while fighting, one per 50 ms slot in the lobby.
///
/// The stamp this writes is now read by a second rule: `shoot::fire` measures the charged
/// shot's hold as `Clock::get()?.slot − last_move_tick`, slot against slot. That is only a
/// duration because this function stamps the slot in **every** phase — the day it returns
/// `arena.tick` for any phase again, a charge becomes a subtraction across two clocks.
///
/// ponytail: `slot as u32` truncates, so one move is dropped every ~2^32 slots
/// (~6.8 years of ER uptime). Widening `last_move_tick` is a layout change; it is
/// not worth one.
fn move_clock(arena: &Arena) -> Result<u32, ProgramError> {
    // The ER slot, in every phase.
    //
    // This used to return `arena.tick` during a fight, and that single line was the whole
    // of "the game feels sluggish": `MOVE_STEP` is one 16-unit tile and the gate is one
    // move per clock unit, so a 400 ms tick capped movement at 2.5 tiles a second across
    // a 64-tile arena — twenty-five seconds to cross it. The lobby, which already used
    // the 50 ms slot, moved eight times faster, so walking to the gate felt fine and the
    // raid itself felt like wading.
    //
    // Raising the crank instead would have worked and cost far more: every tick-denominated
    // constant in the simulation (bullet velocity, RESPAWN_TICKS, the enrage deadline,
    // the shot cooldown) is expressed in ticks and would have to be rescaled together,
    // and the validator would do 4-8x the work to produce a purely visual result that
    // interpolation already provides. The boss simulation is genuinely happy at 400 ms;
    // only the player's input gate needed to be finer than the simulation it feeds.
    //
    // The limiter is not weakened, only re-scaled: still exactly one move per clock unit,
    // and the ER coalesces account notifications to one per 50 ms slot anyway, so this is
    // the finest granularity a client could observe its own move landing at.
    let _ = arena;
    Ok(Clock::get()?.slot as u32)
}

/// Land an accepted step on the seat: position, body direction, the client's sequence
/// echo and the rate-limit stamp, in one write.
///
/// `last_move_seq` echoes the client's input sequence number back. Without it an arriving
/// position is ambiguous as to which input produced it and prediction cannot be
/// reconciled; the symptom is rubber-banding for every player (D14).
///
/// Split out of [`move_player`] for one reason: `facing` is also where `shoot::fire` parks
/// the charged-shot flag (`state::CHARGED_SHOT_BIT`), and this write assigning a **bare
/// octant** is what clears it — a step ends the drawn arrow's lifetime with no second field
/// to expire. That is a rule the client mirrors, so it is asserted below against this
/// function rather than read off an assignment inside a handler no host test can call.
fn commit_move(slot: &mut PlayerSlot, dir: u8, (x, y): (i16, i16), seq: u16, now: u32) {
    slot.x = x;
    slot.y = y;
    slot.facing = dir;
    slot.last_move_seq = seq;
    slot.last_move_tick = now;
}

/// Accounts must be validated before any state is touched, and every guard below
/// takes `&AccountView` — which means all of them have to run *before* the `RefMut`
/// borrows, not interleaved with them.
///
/// `players` is bound to `arena` by re-deriving its PDA from the arena address, which
/// is what stops a caller pairing match A's arena with match B's players. `arena`
/// itself is checked by owner + discriminator only: nothing but this program can
/// mint an account it owns, so re-deriving `[b"arena", arena_id]` would buy nothing
/// for ~1.5K CU.
///
/// Returns the arena address, since the `RefMut` on `arena` makes it unreachable
/// afterwards.
fn validate_pair(
    program_id: &Address,
    arena_ai: &AccountView,
    players_ai: &AccountView,
    authority_ai: &AccountView,
    arena_writable: bool,
) -> Result<Address, ProgramError> {
    assert_signer(authority_ai)?;
    assert_writable(players_ai)?;
    if arena_writable {
        assert_writable(arena_ai)?;
    }
    // Inside the ER a delegated account keeps its original owner; on base layer it
    // would be the delegation program. These three handlers only ever run on the ER.
    assert_owned_by(arena_ai, program_id)?;
    assert_owned_by(players_ai, program_id)?;

    let arena_key = *arena_ai.address();
    // `assert_pda` searches for the canonical bump itself (guards.rs) — the stored bump
    // is never a seed. Passing it as one derives a different address entirely, which
    // rejects every legitimate call.
    assert_pda(players_ai, &[SEED_PLAYERS, arena_key.as_ref()], program_id)?;
    Ok(arena_key)
}

/// Quantize the client's requested direction vector to one of the eight `facing`
/// octants, indexing `MOVE_STEP`.
///
/// The wire carries `dx`/`dy` (frozen ABI, tag 6) but the *displacement* is not the
/// client's to choose: only the sign of each component is read, and the step itself
/// comes off `MOVE_STEP` here. That is the "per-tick speed cap" `instruction.rs`
/// defers to the handler — a client that sends (127, 127) moves exactly one diagonal
/// step south-east, the same as one that sends (1, 1). Magnitude is ignored rather
/// than rejected so the caller may send either a unit vector or a full step vector.
///
/// The mapping is the one `app/src/input/controls.ts::dirFromVector` computes with
/// `atan2`: 0 N, 1 NE, 2 E, 3 SE, 4 S, 5 SW, 6 W, 7 NW, y down. `(0, 0)` is not a
/// direction and is rejected at the boundary.
///
/// **Nearest of eight, not sign-only.** The sign quadrant answers "which of the four
/// diagonals" for every vector that is not exactly axis-aligned, so `(120, -7)` — a
/// thumbstick 3° off due east — used to resolve to north-east, 45° away. Free aim gives
/// `shoot` a raw `(dx, dy)` pair off a pointer, and `shoot` stamps `facing` from it
/// through this function, so sign-only would have every shot in the pit flip the sprite
/// to a diagonal. The octant boundary is 22.5°, and `tan 22.5° = 0.41421`, approximated
/// as `5/12 = 0.41667` — 0.15° of error at the boundary, in integers, with no table and
/// no float. Both products fit `i32` at the `i8` input range with three orders of
/// magnitude to spare.
///
/// Answers identically to the old body on all eight unit vectors, which is what its test
/// asserts and why that test is not edited.
pub(crate) fn octant(dx: i8, dy: i8) -> Result<u8, ProgramError> {
    let (x, y) = (dx as i32, dy as i32);
    if x == 0 && y == 0 {
        return Err(ProgramError::InvalidInstructionData);
    }
    let (ax, ay) = (x.abs(), y.abs());
    Ok(if 12 * ay < 5 * ax {
        // Inside 22.5° of the x axis.
        if x > 0 {
            2
        } else {
            6
        }
    } else if 12 * ax < 5 * ay {
        // Inside 22.5° of the y axis.
        if y < 0 {
            0
        } else {
            4
        }
    } else {
        // The diagonal band. Neither component can be zero here: a zero component
        // makes one of the two tests above true for any non-zero vector.
        match (x > 0, y > 0) {
            (true, false) => 1,
            (true, true) => 3,
            (false, true) => 5,
            (false, false) => 7,
        }
    })
}

/// The three phases in which a seat may act. Everything else is a fight that is over.
///
/// `LOBBY`, `MUSTERING` and `FIGHTING` are the only phases in which player input means
/// anything, and this is the allow-list rather than a deny-list of the other four for a
/// reason: the phase byte has grown twice now — four values to six (`PHASE_ROLLING`,
/// `PHASE_ROLLED`), then six to seven (`PHASE_MUSTERING`) — and a handler written as
/// `phase != PHASE_SETTLING && phase != PHASE_SETTLED` would have silently started
/// accepting moves during a VRF roll. An allow-list gains nothing when a phase is
/// appended; a deny-list loses a rule.
///
/// `MUSTERING` is the muster window: the gate is open, the countdown to `fight_at_tick` is
/// running, and everyone walks and joins exactly as they did in the lobby. Only weapons
/// stay down, and that costs nothing here — `shoot` tests `== PHASE_FIGHTING` directly, so
/// it refuses through the muster without a line of its own.
///
/// What each refusal prevents:
///
/// - `SETTLING` / `ROLLED`: `outcome` is fixed and the leaderboard will be written from
///   these bytes. A move accepted here changes a match that is already scored.
/// - `ROLLING`: a VRF callback is in flight against this arena. Player writes are not the
///   hazard — committing is — but there is no fight to move in either.
/// - `SETTLED`: the accounts are on their way back to base layer, so the write is either
///   discarded or, worse, lands after the commit snapshot and is silently lost.
///
/// Applied by all three handlers here. `join` and `enter_gate` deliberately accept
/// `FIGHTING` as well as `LOBBY`: late entry is the design's matchmaking (`00-game-design-
/// spec.md` §4 — "the lobby *is* the matchmaker"), all 20 seats exist before the crank is
/// armed so a late seat costs the frozen account list nothing (R15), and a raid that
/// refused reinforcements would punish exactly the player who watched the fight start.
fn assert_playable(phase: u8) -> Result<(), ProgramError> {
    if phase == PHASE_LOBBY || phase == PHASE_MUSTERING || phase == PHASE_FIGHTING {
        Ok(())
    } else {
        Err(HeartrotError::WrongPhase.into())
    }
}

// ---------------------------------------------------------------------------
// join
// ---------------------------------------------------------------------------

/// Tag 4's argument block, parsed and validated as bytes.
///
/// Pure, so the frozen ABI is testable without the three `AccountView`s `join` needs — and
/// the ABI is the half of `join` most worth a test, since every refusal here is one a
/// client can trip on its own.
///
/// **`class` is range-checked and never clamped.** A clamp turns client/program skew into
/// a player silently holding a weapon the chain disagrees about — a cooldown that reads
/// wrong and damage that reads wrong, with no error anywhere to name the cause. An unknown
/// class is a client bug, and a client bug has to be loud.
///
/// The check is here and not left to [`PlayerSlot::set_class`] (which repeats it, because
/// it is the encoder and must fail closed on its own) for one reason: a *returning*
/// identity never reaches `set_class` — it keeps the class its seat already holds — so a
/// client sending a class the program has never heard of would be answered `Ok` and go on
/// rendering a weapon nobody else can see. Refusing at the wire is what makes the two
/// paths agree.
fn parse_join(data: &[u8]) -> Result<(u8, u8, u8, [u8; 32], [u8; 32]), ProgramError> {
    if data.len() != JOIN_DATA_LEN {
        return Err(ProgramError::InvalidInstructionData);
    }
    let class = data[66];
    if class >= N_CLASSES {
        return Err(ProgramError::InvalidInstructionData);
    }
    let mut session_pubkey = [0u8; 32];
    session_pubkey.copy_from_slice(&data[2..34]);
    let mut identity = [0u8; 32];
    identity.copy_from_slice(&data[34..66]);
    // The all-zero session key is the "unclaimed" sentinel and the all-zero identity
    // is what an unwritten slot carries; accepting either would let two joins collide
    // onto one seat and would make the leaderboard key meaningless.
    if session_pubkey == UNCLAIMED || identity == [0u8; 32] {
        return Err(ProgramError::InvalidInstructionData);
    }
    // The Worker picks the seat — it is the thing holding the Privy identity map and the
    // `seat_occupied` read that decided the arena had room. Honouring its choice is what
    // makes the seat it reported to the browser the seat the browser actually gets;
    // picking a different free slot here would hand the client a stale index.
    Ok((data[0], data[1], class, session_pubkey, identity))
}

/// `join(seat, skin_id, session_pubkey, identity, class)` — accounts
/// `[arena (w), players (w), treasury (signer)]`.
///
/// Claims the Worker's chosen seat for a browser session key, or rotates the key on the
/// seat this identity already holds. Rejects an occupied seat and rejects a session key
/// that is already seated elsewhere.
pub fn join(program_id: &Address, accounts: &mut [AccountView], data: &[u8]) -> ProgramResult {
    let [arena_ai, players_ai, treasury_ai, ..] = accounts else {
        return Err(ProgramError::NotEnoughAccountKeys);
    };

    let (seat, skin_id, class, session_pubkey, identity) = parse_join(data)?;

    validate_pair(program_id, arena_ai, players_ai, treasury_ai, true)?;
    let treasury_key = *treasury_ai.address();

    let mut arena_data = arena_ai.try_borrow_mut()?;
    let arena = state::load_mut::<Arena>(&mut arena_data)?;
    assert_playable(arena.phase)?;
    // Seats are administered, not self-served — see the module header.
    if treasury_key.as_ref() != arena.crank_authority.as_slice() {
        return Err(HeartrotError::NotArenaAuthority.into());
    }

    let mut players_data = players_ai.try_borrow_mut()?;
    let players = state::load_mut::<Players>(&mut players_data)?;

    let mut returning: Option<usize> = None;
    for (i, slot) in players.slots.iter().enumerate() {
        if slot.session_pubkey == UNCLAIMED {
            continue;
        }
        // Privy identity is the durable record; the session key is not. A player who
        // cleared their browser storage comes back to this seat with a new key.
        if slot.identity == identity {
            returning = Some(i);
            continue;
        }
        if slot.session_pubkey == session_pubkey {
            return Err(HeartrotError::SessionKeyInUse.into());
        }
    }

    // An identity that is already seated keeps the seat it holds, whatever the Worker
    // asked for: moving a live player to a different index mid-match would strip their
    // position, HP and damage, and `seat_occupied` would then describe two seats.
    if let Some(seat) = returning {
        let slot = players
            .slots
            .get_mut(seat)
            .ok_or(HeartrotError::SeatOutOfRange)?;
        // Key rotation only. Position, HP, zone, damage and both rate-limit stamps
        // belong to the match in progress: someone who lost their browser storage
        // walks back into the fight where they left it, not to the lobby with a
        // cleared score. Writing the same key twice is therefore a no-op, which is
        // what makes `/session/init` safe to retry.
        //
        // `class` is deliberately NOT among them, where `skin_id` is. A skin is a render
        // hint; a class is the cooldown and the damage `shoot` reads out of this byte, and
        // `last_shot_tick` stays behind across a rotation. Rotating the class would let a
        // player fire the archer's 70, re-join as the knight, and take the next shot on the
        // knight's 800 ms — archer damage at knight cadence, ~87 DPS against the 50 both
        // classes are built to. Nothing is stored twice by refusing: the client renders the
        // class off this slot, so the seat's byte is what the player sees.
        //
        // ponytail: a class is therefore fixed for the incarnation. Switching costs a
        // wipe; if switching mid-match is ever wanted, gate it on `last_shot_tick == 0`.
        slot.session_pubkey = session_pubkey;
        slot.skin_id = skin_id;
        return Ok(());
    }

    // `get_mut` is the bounds check — a `seat` of 200 lands here, not in an indexing
    // panic. Requiring the slot to be unclaimed is what stops a second identity being
    // written over a live player: without it the Worker's occupancy read (a base-layer
    // round trip behind the ER) racing two joins onto one index would silently evict
    // whoever got there first. The two failures carry different codes because they mean
    // different things to the Worker: `SeatOutOfRange` is its own bug, `SeatOccupied` is
    // a lost race it should retry on another seat.
    let slot = players
        .slots
        .get_mut(seat as usize)
        .ok_or(HeartrotError::SeatOutOfRange)?;
    if slot.session_pubkey != UNCLAIMED {
        return Err(HeartrotError::SeatOccupied.into());
    }
    claim_seat(slot, seat, skin_id, class, session_pubkey, identity)?;

    // The bitmask is the Worker's cheap read of occupancy; `session_pubkey` above is
    // the authority. They are written together so they cannot drift.
    arena.seat_occupied |= 1u32 << seat;
    Ok(())
}

// ---------------------------------------------------------------------------
// move
// ---------------------------------------------------------------------------

/// `move(seat, seq, dx, dy)` — accounts `[arena (r), players (w), session key (signer)]`.
///
/// `move` is a Rust keyword, hence the name.
pub fn move_player(
    program_id: &Address,
    accounts: &mut [AccountView],
    data: &[u8],
) -> ProgramResult {
    let [arena_ai, players_ai, authority_ai, ..] = accounts else {
        return Err(ProgramError::NotEnoughAccountKeys);
    };

    // The slice pattern is the exact-length gate: five argument bytes, no more and no
    // fewer. A short block is somebody probing for an index panic and a long one is
    // client/program skew, and neither is accepted quietly.
    let &[seat, seq_lo, seq_hi, dx_req, dy_req] = data else {
        return Err(ProgramError::InvalidInstructionData);
    };
    let seq = u16::from_le_bytes([seq_lo, seq_hi]);
    // The client asks for a direction; the chain decides how far that is.
    let dir = octant(dx_req as i8, dy_req as i8)?;
    // `octant` only ever answers 0..7, but indexing with `[]` would still compile in a
    // panic branch — and a BPF panic is an abort with no error to read.
    let (dx, dy) = *MOVE_STEP
        .get(dir as usize)
        .ok_or(ProgramError::InvalidInstructionData)?;

    // `arena` stays read-only here: a move must not rewrite the 1,160-byte account
    // the whole lobby is subscribed to.
    validate_pair(program_id, arena_ai, players_ai, authority_ai, false)?;

    let now = {
        let arena_data = arena_ai.try_borrow()?;
        let arena = state::load::<Arena>(&arena_data)?;
        assert_playable(arena.phase)?;
        move_clock(arena)?
    };

    let mut players_data = players_ai.try_borrow_mut()?;
    let players = state::load_mut::<Players>(&mut players_data)?;
    // `get_mut` bounds-checks the client's seat index, and `assert_session_authority` is
    // the *entire* security perimeter behind it: this signer must be the session key
    // stored on the seat being moved. The index is untrusted; the signature is not.
    // (`assert_session_authority` also rejects the unclaimed sentinel, so an empty seat
    // can never be driven — see guards.rs.)
    let slot = players
        .slots
        .get_mut(seat as usize)
        .ok_or(HeartrotError::SeatOutOfRange)?;
    assert_session_authority(slot, authority_ai)?;

    // A dead player is `boss_tick`'s to move: it owns `respawn_at_tick` and the
    // return to the entrance.
    if slot.hp == 0 {
        return Err(HeartrotError::PlayerDead.into());
    }

    // The rate limit. ER fees are zero, so this counter is the only thing standing
    // between one keypair and an unbounded flood (D16/R12).
    if slot.last_move_tick == now {
        return Err(HeartrotError::RateLimited.into());
    }

    // Walls are the real dungeon out of `crate::map`, not a border ring: a corridor
    // mouth or a pillar rejects the step here exactly as the client's copy of the same
    // generated grid predicted it would.
    let nx = slot.x.saturating_add(dx).clamp(0, MAP_MAX_XY);
    let ny = slot.y.saturating_add(dy).clamp(0, MAP_MAX_XY);
    // Two barriers, one refusal. Walls are the real dungeon; the zone box is the pit
    // ceiling and floor, which cannot be walls without killing every ray in the column
    // (see `zone_box`). They share `BlockedByWall` deliberately: the client mirrors
    // `PIT_TOP`/`PIT_BOT` out of the same generated `map` module and predicts both
    // refusals identically, so a second error code would distinguish nothing a client
    // could not already see, and a legal-looking move the chain rejects is this project's
    // signature misdiagnosis.
    if is_wall(nx, ny) || !may_move_to(slot.zone, slot.y, ny) {
        return Err(HeartrotError::BlockedByWall.into());
    }

    commit_move(slot, dir, (nx, ny), seq, now);
    Ok(())
}

// ---------------------------------------------------------------------------
// enter_gate
// ---------------------------------------------------------------------------

/// `enter_gate(seat)` — accounts `[arena (w), players (w), session key (signer)]`.
///
/// Flips the seat from lobby to arena and teleports it to the arena entrance.
///
/// The only player-callable handler here with no tick counter, and it does not need one:
/// the `zone != ZONE_LOBBY` refusal below makes it one-shot per seat per incarnation, so a
/// flood of repeats is a flood of rejections that write nothing — where `move` and `shoot`
/// would each succeed, every time, at zero fee. That refusal is therefore load-bearing
/// twice over: it is the rate limit *and* the `alive_count` bound.
pub fn enter_gate(
    program_id: &Address,
    accounts: &mut [AccountView],
    data: &[u8],
) -> ProgramResult {
    let [arena_ai, players_ai, authority_ai, ..] = accounts else {
        return Err(ProgramError::NotEnoughAccountKeys);
    };

    // Tag 5 is not in `lib.rs::ZERO_ARG_TAGS`, so a trailing payload reaches this
    // handler and this is the only place that can refuse it. One argument byte, exactly.
    let &[seat] = data else {
        return Err(ProgramError::InvalidInstructionData);
    };

    validate_pair(program_id, arena_ai, players_ai, authority_ai, true)?;

    let mut arena_data = arena_ai.try_borrow_mut()?;
    let arena = state::load_mut::<Arena>(&mut arena_data)?;
    assert_playable(arena.phase)?;

    let mut players_data = players_ai.try_borrow_mut()?;
    let players = state::load_mut::<Players>(&mut players_data)?;
    let seat = seat as usize;
    // Same perimeter as `move_player`: the index is bounds-checked, the signature is
    // what proves the caller owns the seat.
    let slot = players
        .slots
        .get_mut(seat)
        .ok_or(HeartrotError::SeatOutOfRange)?;
    assert_session_authority(slot, authority_ai)?;

    gate_refusal(slot)?;

    // `boss_tick` owns the arena entrance; a second definition here would read as a
    // teleport bug the first time anyone died. It is also inside the arena box by
    // construction — every `E` mark is a `P` tile — so the flip below cannot strand the
    // seat outside the only y range `move_player` will accept.
    let (x, y) = crate::handlers::tick::entrance_for(seat);
    slot.zone = ZONE_ARENA;
    slot.x = x;
    slot.y = y;
    // A bare octant, like every `facing` write outside `shoot`: it also clears the
    // charged-shot flag, so nobody walks into the pit with a charged arrow drawn.
    slot.facing = 0;
    slot.hp = slot.hp_max;
    slot.respawn_at_tick = 0;

    // Cap rather than wrap: `alive_count` drives `bullets_per_volley = 3 + alive_count`,
    // and a wrapped count would fill the pool on the next volley.
    arena.alive_count = arena.alive_count.saturating_add(1).min(MAX_SEATS as u8);
    Ok(())
}

// ---------------------------------------------------------------------------
// Checks
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::{
        CHARGED_SHOT_BIT, CLASS_MASK, PHASE_ROLLED, PHASE_ROLLING, PHASE_SETTLED, PHASE_SETTLING,
    };

    /// A step overwrites `facing` whole, so the charged-shot flag `shoot::fire` parks in
    /// bit 3 dies with the arrow it describes — "charging accrues only while standing
    /// still" is a property of this one write, not a rule anyone maintains. And no octant
    /// the quantiser can answer reaches the flag, so a step can never set it by accident.
    #[test]
    fn a_step_clears_the_charged_shot_flag() {
        let mut slot = PlayerSlot::zeroed();
        slot.facing = 2 | 1 << CHARGED_SHOT_BIT;
        commit_move(&mut slot, 6, (100, 900), 41, 7_000);
        assert_eq!(slot.facing, 6, "the turn took the flag with it");
        assert_eq!(
            (slot.x, slot.y, slot.last_move_seq, slot.last_move_tick),
            (100, 900, 41, 7_000),
        );

        for dx in i8::MIN..=i8::MAX {
            for dy in i8::MIN..=i8::MAX {
                if let Ok(dir) = octant(dx, dy) {
                    assert!(dir < 1 << CHARGED_SHOT_BIT, "octant {dir} overlaps the flag");
                }
            }
        }
    }

    /// A seat index is re-used forever — twenty of them serve every incarnation of an arena
    /// — so a claim that leaves one field of the previous occupant behind is a scoreboard
    /// that lies and a rate limiter that starts pre-armed. `deaths` is the concrete case:
    /// it was `PlayerSlot._pad1` until this run, and a field-by-field claim would have gone
    /// on looking complete while carrying a dead player's count onto a new one.
    #[test]
    fn a_seat_claim_cannot_inherit_the_last_occupant() {
        let mut used = PlayerSlot::zeroed();
        used.zone = ZONE_ARENA;
        used.facing = 5;
        used.hp = 0;
        used.deaths = 9;
        used.damage_dealt = 12_345;
        used.respawn_at_tick = 700;
        used.last_move_tick = 700;
        used.last_shot_tick = 699;
        used.last_move_seq = 4_000;
        // The previous occupant's class AND their last aim, in the one byte that carries
        // both. A claim that kept either would hand a new player the old one's weapon.
        used.class_aim = 0xFF;

        claim_seat(&mut used, 3, 7, 1, [1u8; 32], [2u8; 32]).unwrap();

        assert_eq!(used.session_pubkey, [1u8; 32]);
        assert_eq!(used.identity, [2u8; 32]);
        assert_eq!(used.skin_id, 7);
        assert_eq!(
            used.class_aim, CLASS_MASK,
            "the archer bit, and no inherited aim"
        );
        assert_eq!(used.zone, ZONE_LOBBY);
        assert_eq!((used.hp, used.hp_max), (PLAYER_HP_MAX, PLAYER_HP_MAX));
        assert_eq!((used.x, used.y), lobby_spawn(3));

        // The whole point, stated as bytes rather than as a list of fields: a re-used seat
        // and a never-used one are indistinguishable. A field added to `PlayerSlot` and
        // forgotten here fails this line — a per-field assertion would not, since it would
        // be the same forgotten list a second time.
        let mut fresh = PlayerSlot::zeroed();
        claim_seat(&mut fresh, 3, 7, 1, [1u8; 32], [2u8; 32]).unwrap();
        assert_eq!(bytemuck::bytes_of(&used), bytemuck::bytes_of(&fresh));
        assert_eq!(
            (used.deaths, used.damage_dealt, used.respawn_at_tick),
            (0, 0, 0)
        );
        assert_eq!((used.last_move_tick, used.last_shot_tick), (0, 0));
    }

    /// Tag 4's wire block, both classes through it, and every byte-level refusal it owes.
    ///
    /// The class is the one argument a player picks that the chain then reads back as
    /// *rules* rather than as decoration, so the two failure modes worth a test are the
    /// ones with no error message: a class that was clamped instead of refused, and a
    /// class that landed anywhere but bit 7 (where it would corrupt the aim `shoot::fire`
    /// shares the byte with, and vice versa).
    #[test]
    fn a_join_carries_a_class_and_refuses_an_unknown_one() {
        let mut data = [0u8; JOIN_DATA_LEN];
        data[0] = 3;
        data[1] = 2;
        data[2..34].copy_from_slice(&[7u8; 32]);
        data[34..66].copy_from_slice(&[9u8; 32]);

        for class in 0..N_CLASSES {
            data[66] = class;
            let (seat, skin_id, parsed, key, identity) =
                parse_join(&data).expect("a legal class is accepted");
            assert_eq!((seat, skin_id, parsed), (3, 2, class));
            assert_eq!((key, identity), ([7u8; 32], [9u8; 32]));

            let mut slot = PlayerSlot::zeroed();
            claim_seat(&mut slot, seat, skin_id, class, key, identity).unwrap();
            assert_eq!(slot.class_aim >> 7, class, "the class must land in bit 7");
            assert_eq!(
                slot.class_aim & !CLASS_MASK,
                0,
                "a seat that has fired no shot has no aim to carry",
            );
        }

        // Refused, never clamped — including the values that would alias onto a legal
        // class if the byte were masked instead of range-checked.
        for bad in [
            N_CLASSES,
            N_CLASSES + 1,
            CLASS_MASK,
            CLASS_MASK | 1,
            u8::MAX,
        ] {
            data[66] = bad;
            assert_eq!(
                parse_join(&data).unwrap_err(),
                ProgramError::InvalidInstructionData,
                "class {bad} was accepted",
            );
        }

        // A client built against the 66-byte block is refused on length, which is the
        // whole reason `class` was appended rather than packed in beside `skin_id`: the
        // skew is one clean error and not a misread key.
        data[66] = 0;
        assert!(
            parse_join(&data[..JOIN_DATA_LEN - 1]).is_err(),
            "the old block still parses"
        );
        assert!(parse_join(&[]).is_err());

        // And both sentinels still refuse, from inside the extracted parser.
        let mut zero_key = data;
        zero_key[2..34].fill(0);
        assert!(
            parse_join(&zero_key).is_err(),
            "the unclaimed sentinel was accepted as a key"
        );
        let mut zero_identity = data;
        zero_identity[34..66].fill(0);
        assert!(
            parse_join(&zero_identity).is_err(),
            "an unwritten identity was accepted"
        );
    }

    /// The phase gate, over the whole 6-value phase byte and past the end of it.
    ///
    /// Player input is legal in exactly two phases. The four refusals are one rule with
    /// four reasons (see [`assert_playable`]); walking every value is what stops the next
    /// appended phase from defaulting to "playable".
    #[test]
    fn only_a_live_match_accepts_player_input() {
        assert!(assert_playable(PHASE_LOBBY).is_ok());
        assert!(
            assert_playable(PHASE_FIGHTING).is_ok(),
            "late entry is the matchmaker"
        );
        // The muster is a walking phase: joining, moving and entering the gate all stay
        // legal while the countdown runs, or the twenty seconds the window exists for
        // would be twenty seconds nobody could use.
        assert!(
            assert_playable(PHASE_MUSTERING).is_ok(),
            "the muster is walkable"
        );

        for phase in [
            PHASE_SETTLING,
            PHASE_SETTLED,
            PHASE_ROLLING,
            PHASE_ROLLED,
            PHASE_MUSTERING + 1,
            u8::MAX,
        ] {
            assert_eq!(
                assert_playable(phase).unwrap_err(),
                HeartrotError::WrongPhase.into(),
                "phase {phase} accepted input into a fight that is over",
            );
        }

        // The move limiter runs off the ER slot in EVERY phase, so a fight is gated at
        // 50 ms rather than at the 400 ms crank tick. That is the whole difference between
        // 2.5 tiles a second and twenty.
        //
        // The slot arrives through a syscall that does not exist off chain, so the host
        // cannot read a value here — but it CAN prove the branch is gone. Under the old
        // code a fighting arena returned `arena.tick` without touching a sysvar, so
        // seeing the sysvar error is exactly the evidence that a fight no longer reads
        // the tick. Asserting `Ok(41)` here is what would mean the regression came back.
        let mut arena = Arena::zeroed();
        arena.phase = PHASE_FIGHTING;
        arena.tick = 41;
        assert_eq!(
            move_clock(&arena),
            Err(ProgramError::UnsupportedSysvar),
            "a fight must read the ER slot, never arena.tick",
        );
    }

    /// Incarnation N+1 must hand `join` twenty claimable seats and no live key.
    ///
    /// This is the only thing that ever unclaims a seat, and it is not in this file — so
    /// what is asserted here is the interface `join` and `guards::assert_session_authority`
    /// depend on: after the reset every slot carries the all-zero sentinel, which is
    /// simultaneously "claimable" to `join` and "authorizes nobody" to the guard. A reset
    /// that left a session key behind would leave a closed browser's key able to drive a
    /// seat in a fight its owner never entered.
    #[test]
    fn an_incarnation_reset_unclaims_every_seat() {
        let mut players = Players::zeroed();
        for seat in 0..MAX_SEATS as u8 {
            let key = [seat.wrapping_add(1); 32];
            let slot = players.slots.get_mut(seat as usize).expect("seat in range");
            claim_seat(slot, seat, 0, 0, key, key).unwrap();
            slot.deaths = 3;
            slot.damage_dealt = 500;
        }
        assert!(players.slots.iter().all(|s| s.session_pubkey != UNCLAIMED));

        players.reset_for_incarnation();

        assert!(players.slots.iter().all(|s| s.session_pubkey == UNCLAIMED));
        assert!(players.slots.iter().all(|s| s.identity == [0u8; 32]));
        assert!(players
            .slots
            .iter()
            .all(|s| s.deaths == 0 && s.damage_dealt == 0 && s.hp == 0));
    }

    #[test]
    fn geometry_holds() {
        // Every spawn is inside the map, on open floor, and unique per seat. The arena
        // side is `tick`'s point, checked here because this is where the wall test lives
        // and `tick` cannot see it: a spawn or a gate that lands a player inside the
        // generated dungeon leaves them unable to move at all, in any direction.
        let mut seen = [(0i16, 0i16); MAX_SEATS];
        for seat in 0..MAX_SEATS as u8 {
            for (x, y) in [
                lobby_spawn(seat),
                crate::handlers::tick::entrance_for(seat as usize),
            ] {
                assert!((0..=MAP_MAX_XY).contains(&x) && (0..=MAP_MAX_XY).contains(&y));
                assert!(!is_wall(x, y), "seat {seat} spawns in a wall");
            }
            let p = lobby_spawn(seat);
            assert!(!seen[..seat as usize].contains(&p), "seat {seat} stacks");
            seen[seat as usize] = p;
        }

        // The outer ring is closed.
        assert!(is_wall(0, 0) && is_wall(MAP_MAX_XY, MAP_MAX_XY));
        assert!(is_wall(500, MAP_MAX_XY) && is_wall(0, 500));
        // ...and it opens onto floor. Searched for rather than typed as tile (1, 1): the
        // perimeter's thickness is the map's to choose and it is two tiles today, so the
        // named-tile form of this line asserted the ring was *thin* while claiming to
        // assert it was closed. `inset` is the first open column of the boss's air and is
        // reused below, so the two assertions cannot disagree about where the ring ends.
        let inset = (0..MAP_TILES as i16)
            .find(|tx| !is_wall(tx * TILE, TILE))
            .expect("row 1 is solid — the boss's air must be open floor or every ray dies");
        assert!(inset > 0, "the border ring is open at the top-left corner");
        // Off-map fails closed rather than indexing out of range.
        assert!(is_wall(-1, 0) && is_wall(0, -1) && is_wall(MAP_MAX_XY + 1, 0));

        // The interior is a dungeon, not an empty rectangle. Stated as "somewhere below
        // the pit there is rock" rather than as a named tile: the named-tile version of
        // this assertion had to be rewritten the moment the grid was redrawn, which is
        // exactly the property a drift guard must not have. If `crate::map::WALLS` ever
        // regresses to a bare border ring, this fires.
        assert!(
            (1..MAP_TILES as i16 - 1)
                .any(|ty| (1..MAP_TILES as i16 - 1).any(|tx| is_wall(tx * TILE, ty * TILE))),
            "interior has no walls",
        );
        // The boss stands on floor. `map.rs` const-asserts the same thing at compile time
        // against `BOSS_SPAWN`; this reads it through `is_wall`, which is the function the
        // *player* is refused by, so the two indexing conventions are checked against each
        // other rather than each being checked against itself.
        assert!(
            !is_wall(crate::map::BOSS_SPAWN.0, crate::map::BOSS_SPAWN.1),
            "boss spawns in a wall",
        );

        // Walking into the ring is clamped in bounds and then rejected as wall, and
        // the clamp itself never overflows at the i16 extremes.
        for (dx, dy) in MOVE_STEP {
            let nx = i16::MAX.saturating_add(dx).clamp(0, MAP_MAX_XY);
            let ny = i16::MIN.saturating_add(dy).clamp(0, MAP_MAX_XY);
            assert!((0..=MAP_MAX_XY).contains(&nx) && (0..=MAP_MAX_XY).contains(&ny));
        }
        // West out of the first open column is rock, whatever the ring's thickness.
        assert!(is_wall(
            (inset * TILE).saturating_add(MOVE_STEP[6].0).clamp(0, MAP_MAX_XY),
            TILE
        ));

        // Diagonals cover the same ground as straights, within one unit.
        for (dx, dy) in MOVE_STEP {
            let d2 = (dx as i32) * (dx as i32) + (dy as i32) * (dy as i32);
            let straight = (STEP as i32) * (STEP as i32);
            assert!((d2 - straight).abs() <= 2 * STEP as i32);
        }

        // `octant` must agree with `MOVE_STEP` on all eight directions, or the chain
        // walks a player somewhere other than where the client predicted and every
        // move rubber-bands. Feeding each step vector back through the quantizer is
        // the round trip: sign-only, so magnitude cannot matter.
        for (dir, (dx, dy)) in MOVE_STEP.iter().enumerate() {
            assert_eq!(octant(dx.signum() as i8, dy.signum() as i8), Ok(dir as u8));
            // Any vector in the same sign quadrant resolves to the same step.
            let scaled = octant(
                (*dx as i32 * 7).signum() as i8,
                (*dy as i32 * 7).signum() as i8,
            );
            assert_eq!(scaled, Ok(dir as u8), "magnitude changed the direction");
        }
        // The `atan2` mapping in app/src/input/controls.ts, spot-checked: north is 0
        // (y grows *down*, so north is negative dy) and the octants run clockwise.
        assert_eq!(octant(0, -1), Ok(0));
        assert_eq!(octant(127, -127), Ok(1));
        assert_eq!(octant(i8::MIN, 0), Ok(6));
        // Standing still is not a direction.
        assert!(octant(0, 0).is_err());

        // The gate is reachable: every unit of it is inside the map and on floor, and the
        // block is closed on all four sides. One walled tile inside the block is a gate a
        // player can stand next to and never on, which is a raid that cannot be started
        // and which nothing at runtime reports.
        assert!(on_gate(GATE_MIN_X, GATE_MIN_Y) && on_gate(GATE_MAX_X, GATE_MAX_Y));
        assert!(!on_gate(GATE_MIN_X - 1, GATE_MIN_Y) && !on_gate(GATE_MAX_X + 1, GATE_MAX_Y));
        assert!(!on_gate(GATE_MIN_X, GATE_MIN_Y - 1) && !on_gate(GATE_MAX_X, GATE_MAX_Y + 1));
        let mut gx = GATE_MIN_X;
        while gx <= GATE_MAX_X {
            let mut gy = GATE_MIN_Y;
            while gy <= GATE_MAX_Y {
                assert!(
                    on_gate(gx, gy) && !is_wall(gx, gy),
                    "gate unit ({gx}, {gy}) is wall"
                );
                gy += TILE;
            }
            gx += TILE;
        }

        // The gate is not the boss. `map.rs` const-asserts this too; it is repeated here
        // because the failure is silent and total — a gate block overlapping `BOSS_SPAWN`
        // would flip a player into the arena standing inside the shell.
        assert!(
            !on_gate(crate::map::BOSS_SPAWN.0, crate::map::BOSS_SPAWN.1),
            "the gate block contains BOSS_SPAWN",
        );
    }

    /// Check 11.6, and the reason `PIT_TOP` is a comparison rather than a row of wall
    /// tiles: for every pit column, a raider standing at the top of the pit is held there
    /// by the arena box **while the tile north of them is open floor**.
    ///
    /// If that tile were wall, `shoot::raycast` — which tests `is_wall` before it tests any
    /// part rectangle — would kill every shot fired up that column, and the whole
    /// top-centre composition would be a boss nobody in that lane can hit. The two
    /// barriers must disagree here, and this is the assertion that says so out loud.
    #[test]
    fn the_pit_ceiling_holds_raiders_without_being_a_wall() {
        assert!(PIT_TOP >= TILE && PIT_BOT > PIT_TOP && PIT_BOT <= MAP_MAX_XY);

        let mut columns = 0;
        let mut x = 0;
        while x <= MAP_MAX_XY {
            if !is_wall(x, PIT_TOP) {
                columns += 1;
                // Both northward steps — cardinal and diagonal — are refused...
                assert!(
                    !may_move_to(ZONE_ARENA, PIT_TOP, PIT_TOP - STEP),
                    "north out of the pit"
                );
                assert!(
                    !may_move_to(ZONE_ARENA, PIT_TOP, PIT_TOP - STEP_DIAG),
                    "NE/NW out of the pit",
                );
                // ...and the tile it would have stepped onto is floor, not rock.
                assert!(!is_wall(x, PIT_TOP - TILE), "boss air is walled at x={x}");
            }
            // The lobby is bounded by the same rim from below. It used to be unbounded on
            // the argument that real walls held it, and they do not: the boss's air is
            // open floor by construction (the assertion two lines up), so this comparison
            // is the only thing between a lobby seat and the inside of the crown.
            assert!(!may_move_to(ZONE_LOBBY, PIT_BOT + 1, PIT_TOP - STEP));
            assert!(may_move_to(ZONE_LOBBY, PIT_BOT + 1, PIT_BOT + 1 + STEP));
            x += TILE;
        }
        assert!(columns > 0, "the pit has no open columns");

        // The two boxes meet at the rim with no gap and no overlap — the seam is what
        // makes `enter_gate`'s flip safe, since it crosses zones and y in one write.
        assert!(
            !may_move_to(ZONE_ARENA, PIT_BOT, PIT_BOT + 1),
            "the pit floor leaks"
        );
        assert!(
            !may_move_to(ZONE_LOBBY, PIT_BOT + 1, PIT_BOT),
            "the lobby ceiling leaks"
        );
        assert!(
            may_move_to(ZONE_ARENA, PIT_TOP, PIT_BOT) && may_move_to(ZONE_ARENA, PIT_BOT, PIT_TOP)
        );
        assert_eq!(
            zone_box(ZONE_ARENA).1 + 1,
            zone_box(ZONE_LOBBY).0,
            "the boxes do not tile"
        );
        // ...and the gate the flip is triggered from is inside the lobby box, all of it.
        assert!(
            may_move_to(ZONE_LOBBY, GATE_MIN_Y, GATE_MIN_Y)
                && may_move_to(ZONE_LOBBY, GATE_MAX_Y, GATE_MAX_Y),
            "the gate rows are outside the lobby box — standing on the gate is a freeze",
        );
        for seat in 0..MAX_SEATS {
            let (_, y) = crate::handlers::tick::entrance_for(seat);
            assert!(
                may_move_to(ZONE_ARENA, y, y),
                "seat {seat} enters the arena outside the arena box and can never move",
            );
        }
    }

    /// Finding 2 of `docs/review/chain.md`, stated as the search the review ran: exhaustive
    /// BFS over every unit position a `ZONE_LOBBY` seat can reach through the shipped
    /// `map::WALLS` with the shipped eight-way `MOVE_STEP`, under the real move rule.
    ///
    /// Before the lobby box existed this search reached 445,696 positions with minimum
    /// y = **16** — tile row 1, inside the boss's crown — because the rows above the pit
    /// are deliberately open floor (see [`the_pit_ceiling_holds_raiders_without_being_a_wall`])
    /// and the clamp only applied to `ZONE_ARENA`. Two properties are asserted together
    /// because either alone is satisfiable by a broken rule: nothing above the rim is
    /// reachable, **and** the gate is still reachable from all twenty lobby spawns. A box
    /// that boxed the lobby in would pass the first and fail the second, and that failure
    /// is a raid nobody can ever start.
    ///
    /// Searched from one seat's spawn, once instead of twenty times, and the other
    /// nineteen spawns are asserted to be *in* the result: inside the legal set the step
    /// relation is symmetric (`MOVE_STEP` contains every negation, and the clamp is
    /// unreachable because the border ring is wall), so "seat 0 reaches seat k's spawn and
    /// the gate" is "seat k reaches the gate".
    ///
    /// Seeding this from a gate unit instead is what a first draft did, and it failed:
    /// `(x + y)` is even for every step in `MOVE_STEP` (±16 cardinal, ±11 diagonal), so
    /// its parity is invariant and the map's unit positions are two lattices that never
    /// touch. `(480, 639)` is on the odd one and no spawn is. Starting from a real spawn
    /// is the only seed that asks the question a player asks.
    #[test]
    fn a_lobby_seat_cannot_reach_the_pit_or_the_bosss_air() {
        let span = (MAP_MAX_XY as usize) + 1;
        let idx = |x: i16, y: i16| (y as usize) * span + (x as usize);
        let mut seen = vec![false; span * span];
        let start = lobby_spawn(0);
        seen[idx(start.0, start.1)] = true;
        let mut queue = std::collections::VecDeque::from([start]);
        let (mut count, mut min_y, mut gate_units) = (0usize, MAP_MAX_XY, 0usize);

        while let Some((x, y)) = queue.pop_front() {
            count += 1;
            min_y = min_y.min(y);
            gate_units += usize::from(on_gate(x, y));
            for (dx, dy) in MOVE_STEP {
                let nx = x.saturating_add(dx).clamp(0, MAP_MAX_XY);
                let ny = y.saturating_add(dy).clamp(0, MAP_MAX_XY);
                // Verbatim the pair of refusals in `move_player`.
                if is_wall(nx, ny) || !may_move_to(ZONE_LOBBY, y, ny) {
                    continue;
                }
                if !seen[idx(nx, ny)] {
                    seen[idx(nx, ny)] = true;
                    queue.push_back((nx, ny));
                }
            }
        }

        assert!(
            min_y > PIT_BOT,
            "a lobby seat reaches y={min_y}, above the rim at {PIT_BOT} — row \
             {} is inside the boss",
            min_y / TILE,
        );
        assert!(!seen[idx(crate::map::BOSS_SPAWN.0, crate::map::BOSS_SPAWN.1)]);
        // The escape clause cannot be ridden upward: every reachable position is inside
        // the box, so the walk that produced them never left it.
        // 155,648 positions today, against 445,696 before the lobby box existed. It was
        // 170,240 while the lobby was a pillared temple: the open arena deletes 26 pillars
        // but hands the deeper pit three rows and the perimeter a second tile, and the rows
        // cost more than the pillars returned. The bound is loose on purpose — the exact
        // number is a property of the generated map and would have to be re-measured every
        // time `arena.json` is redrawn — but a lobby that has collapsed to a corridor is a
        // different bug wearing this one's clothes.
        assert!(
            count > 10_000,
            "only {count} positions reachable — the lobby is a closet"
        );

        // The other half of the property, and the one a too-tight box breaks: the gate is
        // still there to be walked onto, from every seat's spawn.
        assert!(
            gate_units > 0,
            "no unit of the gate block is reachable from a lobby spawn"
        );
        for seat in 0..MAX_SEATS as u8 {
            let (x, y) = lobby_spawn(seat);
            assert!(
                seen[idx(x, y)],
                "seat {seat} spawns at ({x}, {y}), which seat 0 cannot reach — so seat \
                 {seat} cannot reach the gate seat 0 can",
            );
        }
    }

    /// The freeze this fix is most likely to cause, asserted rather than argued: a seat
    /// that has just crossed the gate seam — in either direction — has somewhere to go.
    ///
    /// Phase is in the loop because it is the other half of "can this seat act": movement
    /// geometry does not read the phase, and asserting that here is what would catch a
    /// future phase gate that made the muster or the fight unwalkable. A raider who
    /// entered during `MUSTERING` and could not move until `FIGHTING` would be a twenty-
    /// second freeze with no error, which is the same bug wearing a clock.
    #[test]
    fn a_seat_that_just_crossed_the_gate_can_always_move() {
        let step_exists = |zone: u8, x: i16, y: i16| {
            MOVE_STEP.iter().any(|(dx, dy)| {
                let nx = x.saturating_add(*dx).clamp(0, MAP_MAX_XY);
                let ny = y.saturating_add(*dy).clamp(0, MAP_MAX_XY);
                !is_wall(nx, ny) && may_move_to(zone, y, ny)
            })
        };

        for phase in [PHASE_LOBBY, PHASE_MUSTERING, PHASE_FIGHTING] {
            assert!(assert_playable(phase).is_ok());

            // Through the gate: `enter_gate` writes `ZONE_ARENA` and `entrance_for` in one
            // instruction, so this is the seat's state on the very next `move`.
            for seat in 0..MAX_SEATS {
                let (x, y) = crate::handlers::tick::entrance_for(seat);
                assert!(
                    step_exists(ZONE_ARENA, x, y),
                    "seat {seat} enters at ({x}, {y}) in phase {phase} with no legal move",
                );
            }

            // Standing on the gate and not yet through it: still `ZONE_LOBBY`, on rows the
            // *arena* box excludes. The client retries `enter_gate` from here, so a seat
            // can sit on these tiles for many slots.
            let mut gx = GATE_MIN_X;
            while gx <= GATE_MAX_X {
                let mut gy = GATE_MIN_Y;
                while gy <= GATE_MAX_Y {
                    assert!(
                        step_exists(ZONE_LOBBY, gx, gy),
                        "a lobby seat on gate unit ({gx}, {gy}) is frozen in phase {phase}",
                    );
                    gy += TILE;
                }
                gx += TILE;
            }
        }
    }

    /// The un-stranding rule, which exists for accounts the *old* program wrote: a lobby
    /// seat parked above the rim (legal yesterday, reachable only through finding 2) is
    /// governed by walls alone until it gets home, and is sealed in once it does.
    ///
    /// The earlier form of this rule permitted only strictly-overshoot-decreasing steps.
    /// That reads as "walk home and nowhere else", but `move_player` requires
    /// `!is_wall(nx, ny) && may_move_to(..)`, so at any position where every
    /// overshoot-decreasing step is a wall the seat had no legal move at all — a hard
    /// freeze, indistinguishable from a wall, for 4,620 stale lobby positions.
    #[test]
    fn a_stranded_seat_is_never_frozen_by_the_box() {
        // Deep in the boss's air, where the BFS above says the old program allowed.
        let stranded = 16i16;
        assert!(
            box_overshoot(ZONE_LOBBY, stranded) > 0,
            "the worst case really is stranded"
        );

        // The box refuses NOTHING while stranded, in any direction. This is the property
        // that makes a freeze unrepresentable: whatever `is_wall` permits, the box permits
        // too, so the box can never be the reason a seat has no move.
        for ny in [
            stranded,
            stranded + STEP,
            stranded + STEP_DIAG,
            stranded - STEP,
            stranded - STEP_DIAG,
        ] {
            assert!(
                may_move_to(ZONE_LOBBY, stranded, ny),
                "the box must refuse nothing at {ny}"
            );
        }

        // Walking home still terminates, and terminates inside the box rather than one
        // step short of it.
        let mut y = stranded;
        let mut steps = 0;
        while box_overshoot(ZONE_LOBBY, y) > 0 {
            assert!(may_move_to(ZONE_LOBBY, y, y + STEP));
            y += STEP;
            steps += 1;
            assert!(steps < MAP_TILES * 2, "the escape does not terminate");
        }
        assert!(y > PIT_BOT && y <= MAP_MAX_XY);

        // And it is not a hole in the ceiling. Once inside, the box is closed again in
        // both directions, from both zones — the seat cannot ride the escape back out.
        assert!(!may_move_to(ZONE_LOBBY, y, PIT_BOT));
        assert!(!may_move_to(ZONE_ARENA, PIT_TOP, PIT_TOP - 1));
        // From INSIDE, both ways. (`PIT_TOP - STEP` is itself outside the arena box, so a
        // seat standing there is stranded and moves freely by design — asserting a refusal
        // there would be asserting the rule this test exists to replace.)
        assert!(!may_move_to(ZONE_ARENA, PIT_TOP + STEP, PIT_TOP - 1));
        assert!(!may_move_to(ZONE_ARENA, PIT_BOT, PIT_BOT + 1));
    }

    /// The box may never be the reason a seat has no move: over every position on the map,
    /// in both zones, `may_move_to` permits at least as many steps as `is_wall` does.
    ///
    /// Exhaustive rather than sampled, because the defect this replaces was found by replay
    /// and missed by a test that checked the y arithmetic without consulting the map.
    ///
    /// `walls_allow` is asserted true as well as equal, and that second assertion is not
    /// redundant: the equality alone is satisfied by `false == false`, which is a walkable
    /// tile with eight walled neighbours — a sealed pocket in the drawn map, and a freeze
    /// the box is innocent of. Nothing else in the repo would report one. (0 such tiles on
    /// this map, in both rooms.)
    #[test]
    fn the_box_never_removes_a_seats_last_legal_move() {
        for zone in [ZONE_LOBBY, ZONE_ARENA] {
            let mut y = 0i16;
            while y <= MAP_MAX_XY {
                let mut x = 0i16;
                while x <= MAP_MAX_XY {
                    if !is_wall(x, y) {
                        let walls_allow = MOVE_STEP.iter().any(|(dx, dy)| !is_wall(x + dx, y + dy));
                        let both_allow = MOVE_STEP.iter().any(|(dx, dy)| {
                            !is_wall(x + dx, y + dy) && may_move_to(zone, y, y + dy)
                        });
                        assert!(
                            walls_allow,
                            "({x},{y}) is walkable floor sealed in on all eight sides"
                        );
                        assert_eq!(
                            walls_allow, both_allow,
                            "zone {zone} at ({x},{y}): the box removed the last legal move"
                        );
                    }
                    x += TILE;
                }
                y += TILE;
            }
        }
    }

    /// The gate's three refusals, which are the whole of the waiting-room contract that
    /// lives on this side: you must be standing on it, you may pass once, and an unclaimed
    /// seat may not pass at all.
    ///
    /// `enter_gate` itself needs three `AccountView`s the host cannot build, so the rules
    /// are asserted through [`gate_refusal`], which is the same code path the handler runs.
    #[test]
    fn the_gate_is_one_way_and_only_from_the_gate() {
        let mut slot = PlayerSlot::zeroed();
        claim_seat(&mut slot, 0, 0, 0, [1u8; 32], [2u8; 32]).unwrap();

        // Walking up to it is not standing on it. The client retries this instruction the
        // whole way in, so the refusal has to be its own code or "not there yet" is
        // indistinguishable from "already through".
        assert_eq!(
            gate_refusal(&slot).unwrap_err(),
            HeartrotError::NotOnGate.into()
        );
        slot.x = GATE_MIN_X;
        slot.y = GATE_MAX_Y;
        assert!(
            gate_refusal(&slot).is_ok(),
            "a lobby seat on the gate may pass"
        );

        // Every unit just outside the block is refused, on all four sides.
        for (x, y) in [
            (GATE_MIN_X - 1, GATE_MIN_Y),
            (GATE_MAX_X + 1, GATE_MIN_Y),
            (GATE_MIN_X, GATE_MIN_Y - 1),
            (GATE_MIN_X, GATE_MAX_Y + 1),
        ] {
            let mut off = slot;
            off.x = x;
            off.y = y;
            assert_eq!(
                gate_refusal(&off).unwrap_err(),
                HeartrotError::NotOnGate.into()
            );
        }

        // One way. This refusal is simultaneously the `alive_count` bound and the whole
        // rate limit on a handler that has no tick counter, so a second entry has to fail
        // even standing on the tile it succeeded from.
        let mut through = slot;
        through.zone = ZONE_ARENA;
        assert_eq!(
            gate_refusal(&through).unwrap_err(),
            HeartrotError::WrongZone.into()
        );
        through.x = GATE_MIN_X;
        through.y = GATE_MIN_Y;
        assert_eq!(
            gate_refusal(&through).unwrap_err(),
            HeartrotError::WrongZone.into(),
            "the zone check must be read before the position check",
        );

        // A seat that `join` never wrote cannot be walked through: `hp_max == 0` would
        // count toward `alive_count` while never being alive.
        let mut unclaimed = slot;
        unclaimed.hp_max = 0;
        assert_eq!(
            gate_refusal(&unclaimed).unwrap_err(),
            ProgramError::InvalidAccountData,
        );
    }
}
