/**
 * Arena wall map -- the browser's copy of the table the chain raycasts against.
 *
 * GENERATED by tools/gen_map.py from assets/map/arena.json. Do not edit.
 * Redraw the ASCII grid in that file and re-run the tool.
 *
 * The renderer draws from {@link MAP_GRID} and client-side prediction rejects a
 * move with {@link isWall}. Both read this one generated table, because a client
 * that disagrees with the chain about a single tile produces a permanent snap-back
 * on that tile that reads as lag rather than as a map bug.
 */

/** Map edge in tiles. */
export const MAP_TILES = 64;

/** Arena-space units per map tile. */
export const MAP_TILE = 16;

/** Highest legal coordinate, matching `handlers::player::MAP_MAX_XY`. */
export const MAP_MAX_XY = MAP_TILES * MAP_TILE - 1;

/**
 * One string per row, one character per tile: `#` wall, `.` floor, `P` pit floor,
 * `G` gate, `E` entrance, `B` the heart tile the boss spawns on. Row *y*, character *x*.
 *
 * Everything but `#` is walkable. A renderer that keys off `.` alone will draw the pit
 * and the gate as holes.
 */
export const MAP_GRID: readonly string[] = [
  '################################################################',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#',
  '#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#',
  '#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#',
  '#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#',
  '#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#',
  '#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#',
  '#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#',
  '#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#',
  '#PPPPPPPPPEPPPPPPPPPPPEPPPPPPPPPPPPPPPPPPPEPPPPPPPPPPPEPPPPPPPP#',
  '###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###',
  '#####PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#####',
  '########PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP########',
  '##############################PPPP##############################',
  '##############################PPPP##############################',
  '##############################GGGG##############################',
  '##############################GGGG##############################',
  '#..............................................................#',
  '#..............................................................#',
  '#.....##......##......##................##......##......##.....#',
  '#.....##......##......##................##......##......##.....#',
  '#..............................................................#',
  '#..............................................................#',
  '#.........##......##........................##......##.........#',
  '#.........##......##........................##......##.........#',
  '#..............................................................#',
  '#..............................................................#',
  '#.....##......##......##................##......##......##.....#',
  '#.....##......##......##................##......##......##.....#',
  '#..............................................................#',
  '#..............................................................#',
  '#.........##......##........................##......##.........#',
  '#.........##......##........................##......##.........#',
  '#..............................................................#',
  '#..............................................................#',
  '#.....##......##......##................##......##......##.....#',
  '#.....##......##......##................##......##......##.....#',
  '#..............................................................#',
  '#..............................................................#',
  '#..............................................................#',
  '################################################################',
];

/**
 * The four `E` marks, in arena-space units at the tile's top-left corner -- the exact
 * pairs `map::ENTRANCES` holds on the chain, so the browser can draw and predict a
 * respawn at the same place the program puts one.
 *
 * Row-major scan order (top to bottom, then left to right), *not* compass order.
 */
export const MAP_ENTRANCES: readonly (readonly [number, number])[] = [
  [160, 512], // tile (10, 32)
  [352, 512], // tile (22, 32)
  [672, 512], // tile (42, 32)
  [864, 512], // tile (54, 32)
];

/**
 * The `B` heart tile: where the boss stands, in arena-space units at the tile's
 * top-left corner. The exact pair `map::BOSS_SPAWN` holds on the chain, which
 * `init::init_arena` writes to `Boss.x`/`Boss.y` on every spawn and respawn -- so the
 * browser can draw the boss, and predict a hitscan against it, without restating a
 * position the map already carries.
 */
export const BOSS_SPAWN: readonly [number, number] = [512, 400]; // tile (32, 25)

/**
 * The raider box: a `ZONE_ARENA` player's y is confined to `PIT_TOP..=PIT_BOT`, the
 * bounding rows of the drawn `P` block (tile rows 24..37).
 *
 * The exact pair `map::PIT_TOP`/`map::PIT_BOT` hold on the chain, and `move_player`
 * compares a move's *destination* y against them. Client-side prediction must apply the
 * same clamp, on the same side of the move: a step the browser allows and the chain
 * refuses is a permanent snap-back on that tile, which reads as lag rather than as a
 * rule. And it is a rule, not a wall -- the rows above the pit are open floor, because
 * the chain's raycast dies on any wall tile between a player and the boss.
 */
export const PIT_TOP = 384;
export const PIT_BOT = 607;

/**
 * The gate block `enter_gate` demands the player be standing in -- the drawn `G`
 * rectangle, tiles (30, 38)..(33, 39), in arena-space units.
 *
 * The lobby's gate glow keys off the *predicted* local position against this box, so it
 * lights the instant you step on rather than a round trip later; the `enter_gate`
 * transaction still goes through the authoritative poll. Same four numbers as
 * `map::GATE_MIN_X`..`GATE_MAX_Y`, out of the same grid.
 */
export const GATE_MIN_X = 480;
export const GATE_MAX_X = 543;
export const GATE_MIN_Y = 608;
export const GATE_MAX_Y = 639;

/**
 * The x span `handlers::player::lobby_spawn` fans the seats across, and their shared row.
 *
 * The lobby camera frames THIS, not just the gate: seat 0 sits `MAX_SEATS / 2` spacings
 * left of the entrance, and a gate-centred camera showed x 256..768 while seat 0 stood at
 * 208 -- the first player to join could not see their own knight.
 */
export const LOBBY_SPAWN_MIN_X = 208;
export const LOBBY_SPAWN_MAX_X = 664;
export const LOBBY_SPAWN_Y = 832;

/** Is this arena-space point inside the gate block? `handlers::player::on_gate`. */
export function onGate(x: number, y: number): boolean {
  return x >= GATE_MIN_X && x <= GATE_MAX_X && y >= GATE_MIN_Y && y <= GATE_MAX_Y;
}

/** Is this tile solid? Off-map is solid, so a caller that skips the clamp fails closed. */
export function isWallTile(tx: number, ty: number): boolean {
  if (tx < 0 || ty < 0 || tx >= MAP_TILES || ty >= MAP_TILES) return true;
  return MAP_GRID[ty]![tx] === '#';
}

/**
 * Is the tile containing this arena-space point solid?
 *
 * Byte-for-byte the same decision as `handlers::player::is_wall`: negative
 * coordinates are wall before the divide (so the truncation direction can never
 * matter), and anything past the edge is wall.
 */
export function isWall(x: number, y: number): boolean {
  if (x < 0 || y < 0) return true;
  return isWallTile(Math.floor(x / MAP_TILE), Math.floor(y / MAP_TILE));
}
