/**
 * Arena wall map -- the browser's copy of the table the chain raycasts against.
 *
 * GENERATED by tools/gen_map.py from assets/map/arena.json. Do not edit.
 * The grid there is written by tools/gen_rooms.py from the room paintings: edit
 * `rooms` in that file, run gen_rooms.py, then re-run this tool.
 *
 * The renderer draws from {@link MAP_GRID} and client-side prediction rejects a
 * move with {@link isWall}. Both read this one generated table, because a client
 * that disagrees with the chain about a single tile produces a permanent snap-back
 * on that tile that reads as lag rather than as a map bug.
 */

/** Map edge in tiles. */
export const MAP_TILES = 64;

/** Arena-space units per map tile. */
export const MAP_TILE = 16;

/** Highest legal coordinate, matching `handlers::player::MAP_MAX_XY`. */
export const MAP_MAX_XY = MAP_TILES * MAP_TILE - 1;

/**
 * One string per row, one character per tile: `#` wall, `.` floor, `P` pit floor,
 * `G` gate, `E` entrance, `B` the heart tile the boss spawns on. Row *y*, character *x*.
 *
 * Everything but `#` is floor to a ray. A raider stands only on the dais -- `P`, `E`,
 * `B`, see {@link isDaisTile} -- and the `.` rows and shoulders around it are the boss's
 * air. A renderer that keys off `.` alone will draw the pit and the gate as holes.
 */
export const MAP_GRID: readonly string[] = [
  '################################################################',
  '##............................................................##',
  '##............................................................##',
  '##............................................................##',
  '##............................................................##',
  '##............................................................##',
  '##............................................................##',
  '##............................................................##',
  '##............................................................##',
  '##............................................................##',
  '##............................................................##',
  '##............................................................##',
  '##...................PPPPPPPPPPPPPPPPPPPPPP...................##',
  '##...............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP...............##',
  '##............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP............##',
  '##.........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.........##',
  '##.......PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.......##',
  '##......PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP......##',
  '##.....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.....##',
  '##....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP....##',
  '##...PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP...##',
  '##..PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP..##',
  '##..PPPPPPPPPPPPPPPPPPPPPPPPPPPPBPPPPPPPPPPPPPPPPPPPPPPPPPPP..##',
  '##.PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.##',
  '###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###',
  '###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###',
  '###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###',
  '####PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP####',
  '####PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP####',
  '#####PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#####',
  '######PPPPPPEPPPPPPPPPEPPPPPPPPPPPPPPPPPPEPPPPPPPPPEPPPPPP######',
  '#######PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#######',
  '#########PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#########',
  '##########PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP##########',
  '############PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP############',
  '###############PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###############',
  '###################PPPPPPPPPPPPPPPPPPPPPPPPPP###################',
  '########################PPPPPPPPPPPPPPPP########################',
  '############GGGGGGG##########GGGGGG##########GGGGGGG############',
  '############GGGGGGG##########GGGGGG##########GGGGGGG############',
  '#####......................................................#####',
  '#####......................................................#####',
  '#####......................................................#####',
  '#####......................................................#####',
  '#####......................................................#####',
  '#####......................................................#####',
  '#####......................................................#####',
  '#####......................................................#####',
  '#############......................................#############',
  '#############......................................#############',
  '#############......................................#############',
  '#############......................................#############',
  '#############......................................#############',
  '#############......................................#############',
  '#############......................................#############',
  '#############......................................#############',
  '################################################################',
  '################################################################',
  '################################################################',
  '################################################################',
  '################################################################',
  '################################################################',
  '################################################################',
  '################################################################',
];

/**
 * The four `E` marks, in arena-space units at the tile's top-left corner -- the exact
 * pairs `map::ENTRANCES` holds on the chain, so the browser can draw and predict a
 * respawn at the same place the program puts one.
 *
 * Row-major scan order (top to bottom, then left to right), *not* compass order.
 */
export const MAP_ENTRANCES: readonly (readonly [number, number])[] = [
  [192, 480], // tile (12, 30)
  [352, 480], // tile (22, 30)
  [656, 480], // tile (41, 30)
  [816, 480], // tile (51, 30)
];

/**
 * The `B` heart tile: where the boss stands, in arena-space units at the tile's
 * top-left corner. The exact pair `map::BOSS_SPAWN` holds on the chain, which
 * `init::init_arena` writes to `Boss.x`/`Boss.y` on every spawn and respawn -- so the
 * browser can draw the boss, and predict a hitscan against it, without restating a
 * position the map already carries.
 */
export const BOSS_SPAWN: readonly [number, number] = [512, 352]; // tile (32, 22)

/**
 * The raider box: a `ZONE_ARENA` player's y is confined to `PIT_TOP..=PIT_BOT`, the
 * bounding rows of the drawn `P` block (tile rows 12..37).
 *
 * The exact pair `map::PIT_TOP`/`map::PIT_BOT` hold on the chain, and `move_player`
 * compares a move's *destination* y against them. Client-side prediction must apply the
 * same clamp, on the same side of the move: a step the browser allows and the chain
 * refuses is a permanent snap-back on that tile, which reads as lag rather than as a
 * rule. And it is a rule, not a wall -- the rows above the pit are open floor, because
 * the chain's raycast dies on any wall tile between a player and the boss. The band is
 * the coarse half of that rule; {@link onDais} is the fine half.
 */
export const PIT_TOP = 192;
export const PIT_BOT = 607;

/** One gate block in arena-space units, both edges inclusive -- `map::Gate`. */
export interface Gate {
  readonly minX: number;
  readonly maxX: number;
  readonly minY: number;
  readonly maxY: number;
}

/**
 * The gate blocks `enter_gate` demands the player be standing in -- the separate drawn `G`
 * blocks on rows 38..39, left to right, so the index IS the difficulty tier
 * (`TIER_EASY..=TIER_HARD` in layout.ts) and the length is `N_TIERS`. The exact numbers
 * `map::GATES` holds on the chain, out of the same grid; `rooms.gen.ts`'s `LOBBY_GATES`
 * are the same blocks as the painting measured them, cross-checked by `gen_map.py`.
 *
 * The lobby's gate glow keys off the *predicted* local position against these blocks, so
 * it lights the instant you step on rather than a round trip later; the `enter_gate`
 * transaction still goes through the authoritative poll.
 */
export const GATES: readonly Gate[] = [
  // tier 0: tiles (12, 38)..(18, 39)
  { minX: 192, maxX: 303, minY: 608, maxY: 639 },
  // tier 1: tiles (29, 38)..(34, 39)
  { minX: 464, maxX: 559, minY: 608, maxY: 639 },
  // tier 2: tiles (45, 38)..(51, 39)
  { minX: 720, maxX: 831, minY: 608, maxY: 639 },
];

/**
 * The x span `handlers::player::lobby_spawn` fans the seats across, and their shared row.
 *
 * The lobby camera frames THIS, not just the gate: seat 0 sits `MAX_SEATS / 2` spacings
 * left of the entrance, and a gate-centred camera showed x 256..768 while seat 0 stood at
 * 208 -- the first player to join could not see their own knight.
 */
export const LOBBY_SPAWN_MIN_X = 208;
export const LOBBY_SPAWN_MAX_X = 664;
export const LOBBY_SPAWN_Y = 832;

/**
 * The lobby floor band: the drawn floor rows below the gate (tile rows 40..55), in
 * arena-space units, `LOBBY_BOT` inclusive of the last row's last unit exactly as
 * {@link PIT_BOT} is.
 *
 * A drawing fact, not a movement rule -- a `ZONE_LOBBY` seat is held in
 * `PIT_BOT + 1 ..= MAP_MAX_XY`, which also covers the gate rows and the border ring. This
 * is what the waiting room is framed on: `VIEW_LOBBY` is this band plus 208 units of
 * masonry above and 80 below (spec 1.1), so the frame moves when the map is redrawn
 * instead of drifting off a hardcoded 640/1008.
 */
export const LOBBY_TOP = 640;
export const LOBBY_BOT = 895;

/**
 * A side room off the lobby: a zone of its own, `SIDE_ZONE_BASE + index` (`ZONE_SECRET`,
 * `ZONE_KEEP`, `ZONE_CRYPT` in layout.ts), laid over the lobby floor so the grid is unchanged
 * and a lobby seat and a room seat may share a tile. `map::Room` on the chain, byte for byte:
 * `mayMoveTo` and `standable` hold a room seat inside `floor`; `use_door` moves a lobby seat
 * standing in `door` to `entry` facing `knock`, and a room seat standing in `exit` back to
 * `back` facing `leave`. `knock`/`leave` are cardinal octants (0 N, 2 E, 4 S, 6 W, y down),
 * `leave` four from `knock`: a seat comes back the way it came. The renderer paints each
 * chamber onto exactly its `floor` (`siderooms.gen.ts`), so a seat inside is drawn where the
 * chain has it, with no offset anywhere.
 */
export interface SideRoom {
  readonly name: string;
  readonly floor: Gate;
  readonly door: Gate;
  readonly exit: Gate;
  readonly entry: readonly [number, number];
  readonly back: readonly [number, number];
  readonly knock: number;
  readonly leave: number;
}

/** The zone byte of `SIDE_ROOMS[0]`: `state::ZONE_SECRET`, read back rather than retyped. */
export const SIDE_ZONE_BASE = 2;

export const SIDE_ROOMS: readonly SideRoom[] = [
  // secret: floor tiles (22, 40)..(41, 49), knock W
  {
    name: 'secret',
    floor: { minX: 352, maxX: 671, minY: 640, maxY: 799 },
    door: { minX: 80, maxX: 95, minY: 672, maxY: 767 },
    exit: { minX: 656, maxX: 671, minY: 672, maxY: 751 },
    entry: [656, 704], // tile (41, 44)
    back: [80, 704], // tile (5, 44)
    knock: 6,
    leave: 2,
  },
  // keep: floor tiles (19, 42)..(44, 53), knock E
  {
    name: 'keep',
    floor: { minX: 304, maxX: 719, minY: 672, maxY: 863 },
    door: { minX: 928, maxX: 943, minY: 672, maxY: 767 },
    exit: { minX: 304, maxX: 319, minY: 720, maxY: 799 },
    entry: [304, 752], // tile (19, 47)
    back: [928, 704], // tile (58, 44)
    knock: 2,
    leave: 6,
  },
  // crypt: floor tiles (22, 42)..(41, 51), knock S
  {
    name: 'crypt',
    floor: { minX: 352, maxX: 671, minY: 672, maxY: 831 },
    door: { minX: 480, maxX: 559, minY: 880, maxY: 895 },
    exit: { minX: 480, maxX: 543, minY: 672, maxY: 687 },
    entry: [496, 672], // tile (31, 42)
    back: [512, 880], // tile (32, 55)
    knock: 4,
    leave: 0,
  },
];

/** The side room a zone byte names, or `null` for the lobby, the pit and any byte off the table. */
export function sideRoomOf(zone: number): SideRoom | null {
  const i = zone - SIDE_ZONE_BASE;
  return Number.isInteger(i) && i >= 0 && i < SIDE_ROOMS.length ? SIDE_ROOMS[i]! : null;
}

/** Is this arena-space point inside the block? `map::Gate::contains`, byte for byte. */
export function inBlock(g: Gate, x: number, y: number): boolean {
  return x >= g.minX && x <= g.maxX && y >= g.minY && y <= g.maxY;
}

/**
 * Which gate this arena-space point stands in, as its tier, or `null` off every gate --
 * `map::gate_at`, the predicate `enter_gate` runs, byte for byte.
 */
export function gateAt(x: number, y: number): number | null {
  for (let tier = 0; tier < GATES.length; tier++) {
    const g = GATES[tier]!;
    if (x >= g.minX && x <= g.maxX && y >= g.minY && y <= g.maxY) return tier;
  }
  return null;
}

/** Is this arena-space point inside any gate block? {@link gateAt} for callers that light a floor. */
export function onGate(x: number, y: number): boolean {
  return gateAt(x, y) !== null;
}

/** Is this tile solid? Off-map is solid, so a caller that skips the clamp fails closed. */
export function isWallTile(tx: number, ty: number): boolean {
  if (tx < 0 || ty < 0 || tx >= MAP_TILES || ty >= MAP_TILES) return true;
  return MAP_GRID[ty]![tx] === '#';
}

/**
 * Is the tile containing this arena-space point solid?
 *
 * Byte-for-byte the same decision as `handlers::player::is_wall`: negative
 * coordinates are wall before the divide (so the truncation direction can never
 * matter), and anything past the edge is wall.
 */
export function isWall(x: number, y: number): boolean {
  if (x < 0 || y < 0) return true;
  return isWallTile(Math.floor(x / MAP_TILE), Math.floor(y / MAP_TILE));
}

/**
 * May a raider stand on this tile? The `P`, `E` and `B` tiles -- the painted platform and
 * its stairs -- exactly the bits of the chain's `map::DAIS`. Off-map is not dais.
 *
 * A second question from the same grid, because the two barriers differ: a `.` tile
 * inside the pit rows is the boss's air beside the dais's shoulders -- floor to the
 * chain's raycast (a wall there was a stand from which every upward shot died) and off
 * limits to a step. `handlers::player::standable` refuses a raider a destination off the
 * dais, and prediction mirrors it through {@link onDais}.
 */
export function isDaisTile(tx: number, ty: number): boolean {
  if (tx < 0 || ty < 0 || tx >= MAP_TILES || ty >= MAP_TILES) return false;
  const c = MAP_GRID[ty]![tx];
  return c === 'P' || c === 'E' || c === 'B';
}

/** Is the tile containing this arena-space point dais? `handlers::player::on_dais`, byte for byte. */
export function onDais(x: number, y: number): boolean {
  if (x < 0 || y < 0) return false;
  return isDaisTile(Math.floor(x / MAP_TILE), Math.floor(y / MAP_TILE));
}
