// @generated by `python3 tools/gen_ordnance.py` -- DO NOT EDIT.
//
// Hand-editing this file re-creates the defect it exists to close. The ids below are a
// contract with `Arena.tsx` (`<use href="#ord-b{sector}">`, `#ord-burst`) and
// `Knight.tsx` (`#ord-hit`): a dangling href renders nothing and throws nothing, so a
// drifted id is an invisible volley and no error anywhere. Edit the tool, then re-run it.
import ORDNANCE_ATLAS from './ordnance.png';

/**
 * One bullet frame: the thorn seed at the exact centre, its tail trailing away from the
 * velocity. Place the `<use>` at `(-w/2, -h/2)` and translate it to the bullet's position.
 */
export const ORD_BULLET = { w: 60, h: 60 } as const;

/**
 * The muzzle burst, `frames` frames of `w` x `h` side by side in ONE symbol. Show it
 * through a `w` x `h` window and step `translateX` by `-w` per frame.
 */
export const ORD_BURST = { w: 32, h: 32, frames: 3 } as const;

/** The impact splat, centred on its frame. */
export const ORD_HIT = { w: 18, h: 18 } as const;

const IMG = `<image href="${ORDNANCE_ATLAS}" width="480" height="152"/>`;

/**
 * The `<defs>` markup: 16 velocity sectors (`ord-b0` at +x, clockwise with y down,
 * 22.5 degrees a step -- `Math.round(Math.atan2(dy, dx) / (Math.PI / 8)) & 15`), the burst
 * strip and the splat, each a `<symbol>` whose `viewBox` crops the one atlas. Mounted once
 * by whichever component owns the arena `<svg>`; React must never walk it again.
 */
export const ORDNANCE_DEFS =
  `<symbol id="ord-b0" viewBox="0 0 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b1" viewBox="60 0 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b2" viewBox="120 0 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b3" viewBox="180 0 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b4" viewBox="240 0 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b5" viewBox="300 0 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b6" viewBox="360 0 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b7" viewBox="420 0 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b8" viewBox="0 60 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b9" viewBox="60 60 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b10" viewBox="120 60 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b11" viewBox="180 60 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b12" viewBox="240 60 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b13" viewBox="300 60 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b14" viewBox="360 60 60 60">${IMG}</symbol>` +
  `<symbol id="ord-b15" viewBox="420 60 60 60">${IMG}</symbol>` +
  `<symbol id="ord-burst" viewBox="0 120 96 32">${IMG}</symbol>` +
  `<symbol id="ord-hit" viewBox="96 120 18 18">${IMG}</symbol>`;
