/**
 * The static environment layer — image B's cavern, built out of `assets/sprites/temple.svg`.
 *
 * ## What this is
 *
 * One `<g>` that goes at the BACK of the arena `<svg>`, underneath everything, inside the
 * `#camera` group so it pans and scales with the camera (spec §1.4, §8.1). It holds, back
 * to front: a base fill, the 16 temple paths under a colour-grading filter, the pit floor
 * wash and its far rim light, and a five-stop gradient stack that manufactures the ceiling,
 * the core spill, the pit light pool, the near-rim shadow and the vignette.
 *
 * ## The performance contract, which is the point of this file
 *
 * `SCENE` is a module-scope `ReactElement`, not a component call. Arena renders `{SCENE}`
 * and on every subsequent update React compares the element by identity, finds it `===`
 * the previous one, and skips the entire subtree without diffing a single one of the
 * 22,195 rects inside. That is the same bailout `Arena.tsx`'s memoised `map` relies on,
 * one rung stronger: a `useMemo(..., [])` still runs the reconciler's cheap identity check
 * *and* can be dropped by React under memory pressure, while a module constant cannot.
 * There is no props object to change because there are no props, and no hook to get a
 * dependency wrong in.
 *
 * Four barriers, then, cheapest first — the first alone is sufficient, the rest are here
 * because "sufficient" has been wrong in this codebase before:
 *
 *   1. React never re-renders it: stable element identity (above).
 *   2. Nothing in it is derived from chain state. Every number below comes from a build
 *      constant, the generated `MAP_GRID`, or the measurement in this file's header
 *      comments. A `Players` notification at 10-20/s has nothing to write here.
 *   3. It carries `will-change: transform` and a `filter`, so it holds its own compositor
 *      raster. Spec §9.2 rule 4: promoted vs unpromoted is 30-85x, and it is the whole
 *      game. An unpromoted static background dirties the paint chunk it shares with the
 *      movers and the whole thing re-rasters — measured 8.6 ms against 1.9 ms.
 *   4. It is `pointer-events: none`, so it cannot become a hit-test target and drag a
 *      style recalculation in through the input path.
 *
 * The measured worst case if all four are somehow defeated and React remounts it every
 * frame is 11.2 ms/frame, and at 300 frames it crashed the renderer 3/3 times
 * (spec §9.2 rule 2). Do not add a prop to this file.
 *
 * ## Why inline paths and not a PNG
 *
 * `docs/art/temple-scene.md` §3.4 recommends rasterising to a 21 KB PNG via a new
 * `tools/gen_temple.py`. The spec cuts that (§12.4): two independent harnesses measured
 * that rasterising buys 0.30 ms — inside the 0.3 ms between-session drift — while the
 * raster path *builds* 2.7x slower (127.2 ms against 46.3 ms). This file is what is left
 * when the generator and the binary asset are deleted: a raw import, a regex, and a filter.
 */
import type { ReactElement } from 'react';

import { BOSS_SPAWN, CORE, MAP_GRID, MAP_TILE, PIT_BOT, PIT_TOP } from '@heartrot/client';

import templeSvg from '../../../assets/sprites/temple.svg?raw';

import { ARENA_UNITS } from './sprites';

// ---------------------------------------------------------------------------
// The temple asset
// ---------------------------------------------------------------------------

/**
 * `temple.svg`'s own coordinate space. The file is a 16-colour 210x238 bitmap wearing an
 * SVG costume: one `<path>` per palette index, 22,195 `M x y h w v h h-w z` subpaths,
 * 49,980 painted pixels against a 49,980-pixel canvas — 100% coverage, zero overlap, zero
 * transparency, verified by expanding every subpath back onto a grid. There are no
 * semantic shapes in it to layer, mask or animate; depth has to come from geometry, which
 * is what the rest of this file is.
 */
const TEMPLE_W = 210;
const TEMPLE_H = 238;

/**
 * The 16 (fill, path-data) pairs, pulled straight out of the asset at module load.
 *
 * Extracting them rather than injecting the file wholesale with `dangerouslySetInnerHTML`
 * buys three things for one regex: the asset's own `shape-rendering="crispEdges"` root
 * attribute is dropped, so the arena's conditional `shape-rendering` (spec §1.5) actually
 * governs these paths instead of being overridden by an attribute on a nested `<svg>`;
 * React renders real element nodes it can key; and there is no innerHTML write anywhere
 * near the layer whose entire purpose is never to be written to.
 */
const TEMPLE_PATHS: readonly (readonly [fill: string, d: string])[] = [
  ...templeSvg.matchAll(/<path fill="(#[0-9a-fA-F]{6})" d="([^"]*)"/g),
].map((m) => [m[1]!, m[2]!] as const);

// The asset is generated by `px2svg` and has been 16 paths since it was converted. If a
// re-conversion ever changes that shape, the regex silently matches fewer paths and the
// scene renders with holes in it and no error anywhere — which is exactly the class of
// failure this project keeps shipping. Fail loudly at import instead.
if (TEMPLE_PATHS.length !== 16) {
  throw new Error(
    `temple.svg: expected 16 <path> elements, matched ${TEMPLE_PATHS.length}. ` +
      'Re-check the px2svg output shape before touching this regex.',
  );
}

/**
 * The grade: neutral grey temple -> cold blue shaft, as one CSS `filter` (spec §8.1).
 *
 * `docs/art/temple-scene.md` §5 solves the target grade as a per-palette-entry remap:
 * `lerp(#080c16, #3d4a5a, u^1.15)` over the asset's measured luminance range L 18.2-113.8,
 * with `CEIL = #3d4a5a` solved — not chosen — as the lightest ceiling that keeps the ally
 * colour above 4:1 WCAG contrast against the lit pit. It then rejects a CSS filter as
 * unable to reach that, and specifies a generator to bake it into a PNG. The spec cuts the
 * generator (§12.4) and flags "cutting gen_temple.py in favour of a CSS filter is untested"
 * as an open risk.
 *
 * Tested. The four filter parameters below were fit by least squares against that exact
 * 16-entry target ramp, area-weighted by the asset's own pixel counts, evaluating the CSS
 * Filter Effects matrices for `sepia`/`hue-rotate`/`saturate`/`brightness` in sRGB (which
 * is what the shorthand functions specify):
 *
 *   RMSE 3.44 of 255 per channel, worst entry 3.7 L high at the top of the ramp.
 *   Pit band (world y 384..607) graded luminance, area-weighted: p5 29, p25 45, p50 53,
 *   p75 57, p95 63 — inside the L 28-75 constraint the WCAG sweep imposes. Reproduced
 *   this session: area-weighted graded pit band = sRGB (41, 50, 65), mean channel 51.9.
 *
 * The WCAG line that used to sit here — "self 8.02:1, ally 4.35:1, bullet 6.37:1" — was
 * measured against the deleted primitive circles, not against the shipped sprite art, and
 * against the GRADED TEMPLE rather than against the floor that is actually composited on
 * screen. Both halves were wrong, in the same direction. See PIT_POOL_ALPHA below for the
 * re-measurement and for what it changes.
 *
 * The one thing lost against the baked remap is the art doc's wood rule, which pulled the
 * four warm palette entries back toward warmth so the dead tree stayed the lightest warm
 * object in the frame. A global filter cannot separate 4 wood entries from 12 neutral ones
 * — measured: after grading, each wood entry sits within 1.5 of the blue-red spread of the
 * neutral at its own luminance, so the tree greys out. It costs nothing here because the
 * tree lives in source rows 7-70 (world y 30-301) and the boss at SCALE=3 spans world y
 * -5..810 in front of it. If the tree is ever wanted back, the lever is a per-entry fill
 * remap over `TEMPLE_PATHS` at module scope — the same arithmetic, applied to 16 strings
 * instead of to the raster — not the deleted PNG generator.
 *
 * ponytail: one global filter, no per-entry remap. Ceiling: the wood/stone hue split.
 * Upgrade path is the 16-string fill remap named above, still no generator, still no PNG.
 */
const TEMPLE_GRADE = 'sepia(1) hue-rotate(177deg) saturate(1.39) brightness(0.5)';

// ---------------------------------------------------------------------------
// Pit geometry, compiled from the generated grid
// ---------------------------------------------------------------------------

/**
 * The pit floor as one path of tile rects, and its horizontal extent.
 *
 * Compiled from `MAP_GRID` — the same generated table the chain raycasts and `predict.ts`
 * collides against — rather than drawn by hand. A hand-drawn pit that disagrees with
 * `map.rs` by one tile reads as permanent lag, which is this project's signature
 * misdiagnosis. `P` is `gen_map.py`'s pit marker and covers rows 24..37, the doorway
 * included, which is exactly the `PIT_TOP..=PIT_BOT` box `move_player` clamps a
 * `ZONE_ARENA` player into. Drawing the region the rule enforces means the rule is visible.
 */
const [PIT_PATH, PIT_X0, PIT_X1] = ((): [string, number, number] => {
  let d = '';
  let x0 = Number.POSITIVE_INFINITY;
  let x1 = 0;
  for (let ty = 0; ty < MAP_GRID.length; ty++) {
    const row = MAP_GRID[ty]!;
    for (let tx = 0; tx < row.length; tx++) {
      if (row[tx] !== 'P') continue;
      d += `M${tx * MAP_TILE} ${ty * MAP_TILE}h${MAP_TILE}v${MAP_TILE}h-${MAP_TILE}z`;
      if (tx * MAP_TILE < x0) x0 = tx * MAP_TILE;
      if ((tx + 1) * MAP_TILE > x1) x1 = (tx + 1) * MAP_TILE;
    }
  }
  return [d, x0, x1];
})();

// ---------------------------------------------------------------------------
// The lighting stack
// ---------------------------------------------------------------------------

/**
 * Five gradients, and they are what make a flat elevation read as a receding cavern. The
 * art doc's stack, re-zoned onto the spec's geometry: the boss's air is world y 16..383,
 * the pit y 384..607, the gate y 608..639, the temple approach y 640..1007.
 *
 * Measured free: the whole stack is inside the noise on a static promoted layer
 * (spec §8.1, and `temple-scene.md` §3.3 measured the same scene with and without it at
 * 3.5 vs 3.5 ms).
 *
 * Two framings have to survive one static layer, because the camera has two states and the
 * layer has one: FIGHTING shows the whole 1024 square, LOBBY shows y 512..1024 at 2x. That
 * is why stop 4 is a band rather than the art doc's bottom-up wash — an 80% black floor at
 * y 1024 fading out at y 737 would black out the half of the lobby the player walks
 * through. As a band peaking on the rim wall it reads as image B's dark foreground rim
 * under the wide camera and as the pit's lip under the close one, and the temple's own
 * stair (the brightest thing in the asset, source rows 179-229 -> world y 770-985) lights
 * the approach underneath it.
 */
const CEILING_END = 330; // just past the pit's top edge; sinks the boss into darkness
const RIM_SHADOW = [520, 600, 700] as const; // fade in, peak on the rim wall, fade out

/**
 * How hard the pit pool lights the ground the raiders stand on. **This number is measured,
 * and it moved DOWN, against the art review's recommendation. Read the arithmetic before
 * changing it.**
 *
 * `docs/review/art.md` fix 3 asks for 0.2 -> 0.35 to lift the knights over the legibility
 * floor. That is backwards, and the reason is that the review compared the skins against
 * the GRADED TEMPLE (sRGB 53) rather than against the floor the renderer actually
 * composites — graded temple, then the `#03070f` pit wash at 0.45, then this pool, then
 * the core spill. Reproducing the review's own method exactly gives its own numbers back
 * (Cobalt 2.54, Nocturne 1.91, Argent 2.11 against sRGB 53), and it also gives the
 * direction: **every skin is LIGHTER than the pit floor, not darker.** Area-weighted WCAG
 * relative luminance over the surviving pixels of each halved `k*-rest` group in
 * `knights.gen.ts`: Cobalt 0.1678, Argent 0.1303, Nocturne 0.1136.
 *
 * So brightening the floor walks it INTO the knights. At the pit centre (512, 496):
 *
 *   pool 0.20 / core 0.30 (shipped)   floor sRGB (58, 89, 106) Y 0.0912
 *                                     Cobalt 1.54  Nocturne 1.16  Argent 1.28
 *   pool 0.35 / core 0.30 (fix 3)     floor sRGB (74, 111, 131) Y 0.1457
 *                                     Cobalt 1.11  Nocturne 1.20  Argent 1.09
 *   pool 0.10 / core 0.10 (here)      floor sRGB (40, 57, 71)  Y 0.0382
 *                                     Cobalt 2.47  Nocturne 1.85  Argent 2.04
 *
 * At 0.35 the floor's luminance lands BETWEEN Nocturne and Cobalt — the single worst
 * value available, three skins straddling the ground they stand on. Worst-case ratio over
 * the whole pit: 1.16 shipped, 1.09 at fix 3, 1.85 here. It also flattens the pool's own
 * spatial swing, which is the other half of the same defect: the same knight read 1.16 at
 * the pit centre and 2.36 at the rim, so legibility changed as you walked. That range is
 * now 1.85..2.47.
 *
 * 1.85 is still under 3:1. The rest is the Knight layer's half — `art.md` fix 3's per-skin
 * key light raises the FIGURE, which is the lever that works in the same direction as this
 * one. Ground and figure had to be moved apart; the review moved them together.
 *
 * ponytail: two numbers, no per-region pool. Ceiling: one radial gradient cannot light the
 * rim without lighting the standing area. If that is ever wanted, the upgrade is a second
 * gradient masked to the pit walls, not a brighter pool.
 */
const PIT_POOL_ALPHA = 0.1;

/**
 * The core spill's peak opacity, and the same story in one line: it was a lamp with no
 * lamp in it.
 *
 * `art.md` fix 4 measures that `.hr-boss-vent` is `opacity: 0` for the lobby, the muster,
 * the spawn reveal and the first ~65% of the fight, while this layer painted a 330-unit
 * `#6ee1ff` pool at 0.3 centred exactly on the sealed core — the brightest cyan on screen
 * belonging to an object that is not drawn. This layer is static by contract and cannot
 * key off `vent_open`, so it cannot own the lamp; it can only own the room's ambient
 * bounce. 0.3 -> 0.1 makes it that, and leaves the hotspot to `Boss.tsx`, which is the one
 * node that knows whether the vent is open.
 */
const CORE_SPILL_ALPHA = 0.1;

/**
 * Where the creature's chest orb throws its light, in world units.
 *
 * Both terms are generated: `BOSS_SPAWN` out of `assets/map/arena.json` by `gen_map.py`,
 * `CORE` out of `assets/sprites/hitboxes.json` by `gen_hitboxes.py` at SCALE=3. It works
 * out to (587, 346) today, and writing 587 here instead would re-create this project's
 * signature defect — one fact stored twice — in the exact place those two generators exist
 * to prevent it. When the boss moves, this light moves with it and nobody has to remember.
 */
const CORE_WORLD = { x: BOSS_SPAWN[0] + CORE.x, y: BOSS_SPAWN[1] + CORE.y };

const LIGHTING = (
    <defs>
      {/* 1. The core's ambient bounce — NOT the core. There is no highlight above L 114
             anywhere in the asset, so every cool or bright value in this scene is added,
             never extracted; this one is added at a third of its old strength so the
             lamp itself can be the brightest thing at this point. See CORE_SPILL_ALPHA. */}
      <radialGradient
        id="scene-core"
        gradientUnits="userSpaceOnUse"
        cx={CORE_WORLD.x}
        cy={CORE_WORLD.y}
        r={330}
      >
        <stop offset="0" stopColor="#6ee1ff" stopOpacity={CORE_SPILL_ALPHA} />
        <stop offset="1" stopColor="#6ee1ff" stopOpacity={0} />
      </radialGradient>

      {/* 2. Pit light pool — the only broad light source, centred on where the raiders
             stand, and therefore the one gradient that decides whether they read at all.
             It zones the playfield against the dark it recedes into in both directions;
             it must not compete with the figures standing in it. See PIT_POOL_ALPHA. */}
      <radialGradient id="scene-pool" gradientUnits="userSpaceOnUse" r={1} cx={0} cy={0}
        gradientTransform={`translate(${ARENA_UNITS / 2} ${(PIT_TOP + PIT_BOT) / 2}) scale(470 215)`}>
        <stop offset="0" stopColor="#96cdeb" stopOpacity={PIT_POOL_ALPHA} />
        <stop offset="1" stopColor="#96cdeb" stopOpacity={0} />
      </radialGradient>

      {/* 3. The ceiling. The heaviest lifter in the stack: the asset's own dark top band is
             only 26 world units tall, and the reference needs the creature emerging from
             darkness across the whole upper third. Manufactured from a gradient rather than
             a crop, so it stays tunable and costs nothing. */}
      <linearGradient id="scene-ceiling" gradientUnits="userSpaceOnUse" x1={0} y1={0} x2={0} y2={CEILING_END}>
        <stop offset="0" stopColor="#050811" stopOpacity={0.92} />
        <stop offset="1" stopColor="#050811" stopOpacity={0} />
      </linearGradient>

      {/* 4. The near-rim shadow band. See the note above on why this is a band. */}
      <linearGradient
        id="scene-rim"
        gradientUnits="userSpaceOnUse"
        x1={0}
        y1={RIM_SHADOW[0]}
        x2={0}
        y2={RIM_SHADOW[2]}
      >
        <stop offset="0" stopColor="#03060c" stopOpacity={0} />
        <stop
          offset={(RIM_SHADOW[1] - RIM_SHADOW[0]) / (RIM_SHADOW[2] - RIM_SHADOW[0])}
          stopColor="#03060c"
          stopOpacity={0.72}
        />
        <stop offset="1" stopColor="#03060c" stopOpacity={0} />
      </linearGradient>

      {/* 5. Vignette. Frames the square under the wide camera and the approach under the
             close one. Transparent well past the pit so it never eats the playfield. */}
      <radialGradient id="scene-vignette" cx="50%" cy="50%" r="72%">
        <stop offset="0.52" stopColor="#000000" stopOpacity={0} />
        <stop offset="1" stopColor="#000000" stopOpacity={0.72} />
      </radialGradient>
    </defs>
);

// ---------------------------------------------------------------------------
// The layer
// ---------------------------------------------------------------------------

/**
 * The whole static environment, as one element built once at module load.
 *
 * Render it as `{SCENE}` as the FIRST child of the `#camera` group, before the walls, the
 * gate marker, the actors and the boss. Do not wrap it, do not give it a key that changes,
 * do not pass it anything.
 *
 * It replaces the arena's floor fill and nothing else. The walls the chain raycasts stay
 * drawn on top of it (spec §8.1): a legal-looking move the chain rejects reads as lag, and
 * a pretty floor that hides a wall is how that gets shipped.
 */
export const SCENE: ReactElement = (
  <g
    id="scene"
    aria-hidden
    // `will-change: transform` is the promotion hint, and the whole game per spec §9.2
    // rule 4. No transform is ever written to this node — the camera above it owns the
    // pan, and two writers on one node's transform is this project's signature bug.
    style={{ willChange: 'transform', pointerEvents: 'none' }}
  >
    {LIGHTING}

    {/* Base fill under everything, so the 210x238 -> 1024x1024 stretch cannot leave a
        seam at the edges and the vignette has something to sit on. This is the graded
        value of the asset's own void colour. */}
    <rect x={0} y={0} width={ARENA_UNITS} height={ARENA_UNITS} fill="#0c0f13" />

    {/* The temple. `preserveAspectRatio` is off by construction — the 210x238 source is
        stretched to the 1024x1024 arena, x4.876 and x4.303, an 11.8% vertical squash that
        is invisible on a stone texture read from above and mildly helpful, since a
        top-down ground plane is foreshortened anyway. The arena stays square because
        1024 = MAP_TILES * MAP_TILE is chain geometry; the reference's landscape read comes
        from zoning the square, not from cropping playfield away. */}
    <g
      transform={`scale(${ARENA_UNITS / TEMPLE_W} ${ARENA_UNITS / TEMPLE_H})`}
      style={{ filter: TEMPLE_GRADE }}
    >
      {TEMPLE_PATHS.map(([fill, d], i) => (
        <path key={i} fill={fill} d={d} />
      ))}
    </g>

    {/* The pit floor, darker than the lit masonry it is cut into — the hole the raiders
        stand in. Compiled from MAP_GRID, so it is the same region the chain clamps. */}
    <path d={PIT_PATH} fill="#03070f" fillOpacity={0.45} />

    {/* The far rim: the pit's top edge, lit. This is the cavern floor receding behind the
        boss, and the one hard line in the scene that says "the ground stops here". The
        NEAR rim — the one the creature's hands grip, drawn in front of everything — is the
        boss rig's occluder, not this layer's. */}
    <rect x={PIT_X0} y={PIT_TOP - 2} width={PIT_X1 - PIT_X0} height={3} fill="#a8d6f0" opacity={0.42} />
    <rect x={PIT_X0} y={PIT_TOP + 1} width={PIT_X1 - PIT_X0} height={14} fill="#03060c" opacity={0.5} />

    {/* The lighting, painted over the graded temple and NOT through the grade filter: the
        added cyan is already the colour it should be, and running it through
        sepia+hue-rotate would grade the light along with the stone. */}
    <rect
      x={0}
      y={0}
      width={ARENA_UNITS}
      height={CEILING_END}
      fill="url(#scene-ceiling)"
    />
    <rect x={0} y={0} width={ARENA_UNITS} height={ARENA_UNITS} fill="url(#scene-pool)" />
    <rect x={0} y={0} width={ARENA_UNITS} height={ARENA_UNITS} fill="url(#scene-core)" />
    <rect
      x={0}
      y={RIM_SHADOW[0]}
      width={ARENA_UNITS}
      height={RIM_SHADOW[2] - RIM_SHADOW[0]}
      fill="url(#scene-rim)"
    />
    <rect x={0} y={0} width={ARENA_UNITS} height={ARENA_UNITS} fill="url(#scene-vignette)" />
  </g>
);
