//! Arena wall bitboard.
//!
//! GENERATED by tools/gen_map.py from assets/map/arena.json. Do not edit.
//! The grid there is written by tools/gen_rooms.py from the room paintings: edit
//! `rooms` in that file, run gen_rooms.py, then re-run this tool.
//!
//! Bit *x* of row *y* is set when tile (x, y) is solid, which is the shape
//! `handlers::player::is_wall` already indexes and the cheapest wall test that
//! exists: one shift and one mask, no account, no CU worth measuring.
//!
//! The map is static per deployment, so it lives in the program image rather than
//! in an account. An account would cost rent, would have to be delegated and
//! committed with the arena, and would spend one of the ~38 account keys an ER
//! transaction is allowed -- with no address lookup tables available to buy it
//! back. This table costs 512 bytes of .so and zero keys. If maps ever need to
//! vary at runtime the upgrade path is a second generated table and a `map_id: u8`
//! on `Arena` selecting between them; still no account, still no key.

/// Map edge in tiles -- the width of the ASCII grid in `assets/map/arena.json`,
/// which is also what sizes the table below.
///
/// This is the only declaration of it in the program: `handlers::player` re-exports
/// this constant and `handlers::tick` casts it, so there is nothing left to assert it
/// against. An `assert!(MAP_TILES == player::MAP_TILES)` used to sit here, and once
/// `player.rs` became a `pub use` it was comparing this value to itself -- a drift
/// guard over a fact that is no longer stored twice is theatre, so it is gone.
pub const MAP_TILES: usize = 64;

/// Arena-space units per tile, compiled from `arena.json`'s `tile_size`.
///
/// Same story as `MAP_TILES`: sole declaration, re-exported rather than restated, and
/// `handlers::tick::ARENA_SIZE` is `MAP_TILES * TILE` derived from these two.
pub const TILE: i16 = 16;

/// Wall bitboard: bit *x* of row *y* set means tile (x, y) is solid.
///
/// Layout, top to bottom. Open floor for the boss's air, with the whole painted dais
/// laid over its lower rows -- the raid stands on the dais ([`DAIS`]) and the creature
/// stands on it too, in the middle of the band -- then the three gate blocks in the wall
/// under it ([`GATES`], one per difficulty tier), then the painted lobby floor. The whole
/// vertical order is the fight: you walk up the lobby, pick a gate, and the gate puts you
/// on the dais to walk the circle around the creature.
///
/// Both rooms are open floor with zero interior obstacles. `tools/gen_map.py` holds
/// them that way: at most one contiguous run of floor per row, so a free-standing
/// block anywhere splits a row and is refused -- the gate rows excepted, whose three
/// runs are the three doorways, each held to a solid rectangle. Perimeter architecture,
/// banners, torches, chains and floor markings are paint, never wall tiles.
///
/// The rows above the dais's widest row are floor wherever they are not dais, and that
/// is load-bearing rather than lazy drawing -- see [`DAIS`] and [`PIT_TOP`].
pub const WALLS: [u64; MAP_TILES] = [
    0xffffffffffffffff, // y=0  ################################################################
    0xc000000000000003, // y=1  ##............................................................##
    0xc000000000000003, // y=2  ##............................................................##
    0xc000000000000003, // y=3  ##............................................................##
    0xc000000000000003, // y=4  ##............................................................##
    0xc000000000000003, // y=5  ##............................................................##
    0xc000000000000003, // y=6  ##............................................................##
    0xc000000000000003, // y=7  ##............................................................##
    0xc000000000000003, // y=8  ##............................................................##
    0xc000000000000003, // y=9  ##............................................................##
    0xc000000000000003, // y=10 ##............................................................##
    0xc000000000000003, // y=11 ##............................................................##
    0xc000000000000003, // y=12 ##...................PPPPPPPPPPPPPPPPPPPPPP...................##
    0xc000000000000003, // y=13 ##...............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP...............##
    0xc000000000000003, // y=14 ##............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP............##
    0xc000000000000003, // y=15 ##.........PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.........##
    0xc000000000000003, // y=16 ##.......PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.......##
    0xc000000000000003, // y=17 ##......PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP......##
    0xc000000000000003, // y=18 ##.....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.....##
    0xc000000000000003, // y=19 ##....PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP....##
    0xc000000000000003, // y=20 ##...PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP...##
    0xc000000000000003, // y=21 ##..PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP..##
    0xc000000000000003, // y=22 ##..PPPPPPPPPPPPPPPPPPPPPPPPPPPPBPPPPPPPPPPPPPPPPPPPPPPPPPPP..##
    0xc000000000000003, // y=23 ##.PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.##
    0xe000000000000007, // y=24 ###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###
    0xe000000000000007, // y=25 ###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###
    0xe000000000000007, // y=26 ###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###
    0xf00000000000000f, // y=27 ####PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP####
    0xf00000000000000f, // y=28 ####PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP####
    0xf80000000000001f, // y=29 #####PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#####
    0xfc0000000000003f, // y=30 ######PPPPPPEPPPPPPPPPEPPPPPPPPPPPPPPPPPPEPPPPPPPPPEPPPPPP######
    0xfe0000000000007f, // y=31 #######PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#######
    0xff800000000001ff, // y=32 #########PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#########
    0xffc00000000003ff, // y=33 ##########PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP##########
    0xfff0000000000fff, // y=34 ############PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP############
    0xfffe000000007fff, // y=35 ###############PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###############
    0xffffe0000007ffff, // y=36 ###################PPPPPPPPPPPPPPPPPPPPPPPPPP###################
    0xffffff0000ffffff, // y=37 ########################PPPPPPPPPPPPPPPP########################
    0xfff01ff81ff80fff, // y=38 ############GGGGGGG##########GGGGGG##########GGGGGGG############
    0xfff01ff81ff80fff, // y=39 ############GGGGGGG##########GGGGGG##########GGGGGGG############
    0xf80000000000001f, // y=40 #####......................................................#####
    0xf80000000000001f, // y=41 #####......................................................#####
    0xf80000000000001f, // y=42 #####......................................................#####
    0xf80000000000001f, // y=43 #####......................................................#####
    0xf80000000000001f, // y=44 #####......................................................#####
    0xf80000000000001f, // y=45 #####......................................................#####
    0xf80000000000001f, // y=46 #####......................................................#####
    0xf80000000000001f, // y=47 #####......................................................#####
    0xfff8000000001fff, // y=48 #############......................................#############
    0xfff8000000001fff, // y=49 #############......................................#############
    0xfff8000000001fff, // y=50 #############......................................#############
    0xfff8000000001fff, // y=51 #############......................................#############
    0xfff8000000001fff, // y=52 #############......................................#############
    0xfff8000000001fff, // y=53 #############......................................#############
    0xfff8000000001fff, // y=54 #############......................................#############
    0xfff8000000001fff, // y=55 #############......................................#############
    0xffffffffffffffff, // y=56 ################################################################
    0xffffffffffffffff, // y=57 ################################################################
    0xffffffffffffffff, // y=58 ################################################################
    0xffffffffffffffff, // y=59 ################################################################
    0xffffffffffffffff, // y=60 ################################################################
    0xffffffffffffffff, // y=61 ################################################################
    0xffffffffffffffff, // y=62 ################################################################
    0xffffffffffffffff, // y=63 ################################################################
];

/// Dais bitboard: bit *x* of row *y* set means a `ZONE_ARENA` seat may stand on tile
/// (x, y). The `P`, `E` and `B` tiles of the drawn grid -- the painted platform ellipse
/// and its stairs, 1198 tiles -- and a strict subset of the floor in [`WALLS`]
/// (const-asserted below).
///
/// A second table because the two barriers answer different questions. `WALLS` is what
/// stops a RAY: `shoot`'s raycast tests it before any part box, so a wall tile between a
/// stand and the boss kills every shot in that column. This is what stops a STEP:
/// `handlers::player::standable` refuses a raider a destination off it. They differ
/// exactly where the dais narrows upward: above its widest row every row's outermost tile
/// has no dais over it, and a raider on that tile's top corner fires every upward shot into
/// the tile above. Wall there was a stand from which nothing could be hit -- eight of them
/// on the first whole-dais grid, found by `gen_hitboxes.py`'s sweep -- so the tile above
/// is the boss's air: floor for the ray, off the dais for the step. Before the dais grew
/// past the boss's feet the y band [`PIT_TOP`]`..=`[`PIT_BOT`] was the whole of this rule.
///
/// Costs 512 more bytes of .so and, like `WALLS`, zero account keys.
pub const DAIS: [u64; MAP_TILES] = [
    0x0000000000000000, // y=0 
    0x0000000000000000, // y=1 
    0x0000000000000000, // y=2 
    0x0000000000000000, // y=3 
    0x0000000000000000, // y=4 
    0x0000000000000000, // y=5 
    0x0000000000000000, // y=6 
    0x0000000000000000, // y=7 
    0x0000000000000000, // y=8 
    0x0000000000000000, // y=9 
    0x0000000000000000, // y=10
    0x0000000000000000, // y=11
    0x000007ffffe00000, // y=12
    0x00007ffffffe0000, // y=13
    0x0003ffffffffc000, // y=14
    0x001ffffffffff800, // y=15
    0x007ffffffffffe00, // y=16
    0x00ffffffffffff00, // y=17
    0x01ffffffffffff80, // y=18
    0x03ffffffffffffc0, // y=19
    0x07ffffffffffffe0, // y=20
    0x0ffffffffffffff0, // y=21
    0x0ffffffffffffff0, // y=22
    0x1ffffffffffffff8, // y=23
    0x1ffffffffffffff8, // y=24
    0x1ffffffffffffff8, // y=25
    0x1ffffffffffffff8, // y=26
    0x0ffffffffffffff0, // y=27
    0x0ffffffffffffff0, // y=28
    0x07ffffffffffffe0, // y=29
    0x03ffffffffffffc0, // y=30
    0x01ffffffffffff80, // y=31
    0x007ffffffffffe00, // y=32
    0x003ffffffffffc00, // y=33
    0x000ffffffffff000, // y=34
    0x0001ffffffff8000, // y=35
    0x00001ffffff80000, // y=36
    0x000000ffff000000, // y=37
    0x0000000000000000, // y=38
    0x0000000000000000, // y=39
    0x0000000000000000, // y=40
    0x0000000000000000, // y=41
    0x0000000000000000, // y=42
    0x0000000000000000, // y=43
    0x0000000000000000, // y=44
    0x0000000000000000, // y=45
    0x0000000000000000, // y=46
    0x0000000000000000, // y=47
    0x0000000000000000, // y=48
    0x0000000000000000, // y=49
    0x0000000000000000, // y=50
    0x0000000000000000, // y=51
    0x0000000000000000, // y=52
    0x0000000000000000, // y=53
    0x0000000000000000, // y=54
    0x0000000000000000, // y=55
    0x0000000000000000, // y=56
    0x0000000000000000, // y=57
    0x0000000000000000, // y=58
    0x0000000000000000, // y=59
    0x0000000000000000, // y=60
    0x0000000000000000, // y=61
    0x0000000000000000, // y=62
    0x0000000000000000, // y=63
];

/// The four `E` marks on the drawn map, in world units at the tile's top-left corner --
/// the same convention `handlers::player::LOBBY_ENTRANCE` and [`GATES`] are written
/// in, and the one `is_wall` inverts with `pos / TILE`.
///
/// Row-major scan order (top to bottom, then left to right), *not* compass order.
/// Redrawing the grid re-orders this array and nothing may assume otherwise.
///
/// This exists so respawn points are *read out of the map* instead of restated beside it.
/// `handlers::tick::entrance_for` picks `ENTRANCES[seat % 4]` and fans that door's ranks
/// along the wall it is set into; the `ENTRANCE_X`/`ENTRANCE_Y` pair that used to
/// describe the arena a second time is gone. Move an `E` in the grid, re-run the tool,
/// and the respawn moves with it.
pub const ENTRANCES: [(i16, i16); 4] = [
    (192, 480), // tile (12, 30)
    (352, 480), // tile (22, 30)
    (656, 480), // tile (41, 30)
    (816, 480), // tile (51, 30)
];

/// The `B` heart tile: where the boss stands, in world units at the tile's top-left
/// corner -- the same convention as [`ENTRANCES`].
///
/// `handlers::init` reads this and writes it to `Boss.x`/`Boss.y` on every spawn and
/// respawn. It is here rather than there because the boss's position is a fact about
/// the *map*: every rectangle in `hitboxes.rs` is an offset from this point, and the
/// open rows above the dais are the only space on the grid tall enough to hold them.
///
/// It is the creature's feet line, on the dais's own tiles: the boss is drawn upward
/// from here, so the creature fills the top of the frame, and the raid walks the dais
/// around it -- `handlers::player` refuses a step into the body, folded out of the
/// hitbox table, so the pit needs no hole cut where the boss stands. The assertion
/// block at the bottom of this file proves it is on the dais, inside
/// `PIT_TOP..=PIT_BOT`, and outside the gate.
///
/// It used to be a pair of literals in `init.rs` reading (512, 320) -- tile (32, 20),
/// which was a two-tile corridor on the map of the time. The shell was mostly inside
/// solid rock and `shoot`'s ray died on the corridor wall before reaching it, while
/// this generator "checked" the spawn against a hardcoded map centre attributed to a
/// `start_match` write that never existed. Three copies, two of them wrong, and the
/// fight had never been run on chain so nothing had noticed.
pub const BOSS_SPAWN: (i16, i16) = (512, 352); // tile (32, 22)

/// The raider box: a `ZONE_ARENA` player's y is confined to `PIT_TOP..=PIT_BOT`.
///
/// Compiled from the `P` block's bounding rows (12..37) -- inclusive of the last
/// row's last unit, which is the form `move_player` compares a *destination* against.
/// Comparing the destination and not the current position is load-bearing: a player who
/// flips zone while standing on the gate is below `PIT_BOT`, and a current-position test
/// would refuse every direction and freeze them there for the match.
///
/// This is a movement rule and deliberately **not** a wall. The rows above the pit are
/// open floor because `shoot`'s raycast tests `is_wall` before the part rectangles, so a
/// single wall tile between a player and the boss would kill every shot in that column
/// with nothing logged anywhere. The band holds the lobby below the rim and is the coarse
/// half of the raider's rule; [`DAIS`] is the fine half, tile by tile, since the boss's
/// air now reaches down beside the dais's shoulders. Barriers that can disagree --
/// `tools/gen_map.py` proves the dais is one connected room and that the gate walks onto
/// it, which is the only guard against a rule that boxes someone in open floor.
pub const PIT_TOP: i16 = 192; // tile row 12
pub const PIT_BOT: i16 = 607; // tile row 37, last unit

/// One gate block, in world units, both edges inclusive -- the form `handlers::player`
/// compares a seat's `(x, y)` against.
#[derive(Clone, Copy)]
pub struct Gate {
    pub min_x: i16,
    pub max_x: i16,
    pub min_y: i16,
    pub max_y: i16,
}

impl Gate {
    /// Is this world point inside the block? Two range tests, which is why the generator
    /// holds every drawn block to a solid rectangle.
    pub const fn contains(&self, x: i16, y: i16) -> bool {
        x >= self.min_x && x <= self.max_x && y >= self.min_y && y <= self.max_y
    }
}

/// The gate blocks `enter_gate` demands the player be standing in, compiled from the
/// separate `G` blocks on rows 38..39 -- left to right, so the index IS the
/// difficulty tier (`state::TIER_EASY..=TIER_HARD`) and `state::N_TIERS` is the length.
///
/// The gate is a portal, not a corridor: `enter_gate` writes `tick::entrance_for(seat)`,
/// so a block owes the pit no adjacency and the three can sit anywhere in the lobby's
/// top wall. What the generator does prove is that each is a solid rectangle of floor
/// inside the lobby box, reachable from every lobby spawn without leaving it, that the
/// three do not share a column, and that the heart stands on none of them -- the last
/// re-proved below on every `cargo check`, against the table that shipped.
///
/// These were four hand literals in `handlers::player` that `gen_map.py` parsed back out
/// of Rust source to validate against the drawn grid: one fact stored twice, with the
/// tool agreeing with whichever copy it read.
pub const GATES: [Gate; 3] = [
    // tier 0: tiles (12, 38)..(18, 39)
    Gate { min_x: 192, max_x: 303, min_y: 608, max_y: 639 },
    // tier 1: tiles (29, 38)..(34, 39)
    Gate { min_x: 464, max_x: 559, min_y: 608, max_y: 639 },
    // tier 2: tiles (45, 38)..(51, 39)
    Gate { min_x: 720, max_x: 831, min_y: 608, max_y: 639 },
];

/// Which gate this world point stands in, as its tier, or `None` off every gate. The
/// predicate `enter_gate` runs; `packages/client/src/map.ts` mirrors it as `gateAt`.
pub const fn gate_at(x: i16, y: i16) -> Option<u8> {
    let mut tier = 0;
    while tier < GATES.len() {
        if GATES[tier].contains(x, y) {
            return Some(tier as u8);
        }
        tier += 1;
    }
    None
}

/// The x span `handlers::player::lobby_spawn` fans the seats across, and their shared row.
///
/// Emitted so the client's lobby camera can frame every spawn instead of guessing. Seat 0
/// sits `MAX_SEATS / 2` spacings left of `LOBBY_ENTRANCE`, which a gate-centred camera
/// cropped off screen -- and seat 0 is what the first player to join always gets.
pub const LOBBY_SPAWN_MIN_X: i16 = 208;
pub const LOBBY_SPAWN_MAX_X: i16 = 664;
pub const LOBBY_SPAWN_Y: i16 = 832;

/// The lobby floor band: the drawn floor rows below the gate (40..55), in world
/// units, `LOBBY_BOT` inclusive of the last row's last unit exactly as [`PIT_BOT`] is.
///
/// A *drawing* fact, not a movement rule -- `player::zone_box` holds a `ZONE_LOBBY` seat
/// in `PIT_BOT + 1 ..= MAP_MAX_XY`, which is wider: it also covers the gate rows and the
/// border ring. Emitted because the renderer frames on the floor, not on the box:
/// `docs/architecture/17-fullscreen-spec.md` 1.1 builds `VIEW_LOBBY` as this band plus 208
/// units of masonry above and 80 below, and its self-check asserts the frame still lands
/// on `LOBBY_BOT + 1`. Retyping 640/1008 in the browser beside a map that owns them is the
/// drift this generator exists to prevent.
pub const LOBBY_TOP: i16 = 640; // tile row 40
pub const LOBBY_BOT: i16 = 895; // tile row 55, last unit

/// The secret room: a THIRD zone, `state::ZONE_SECRET`, laid over the lobby floor (tiles
/// (22, 40) .. (41, 49)), so the grid is unchanged and a lobby seat and a
/// secret seat may share a tile -- the zone keeps them apart on screen. `player::zone_box`
/// and `player::standable` hold a secret seat inside this block; `player::use_door` flips a
/// `ZONE_LOBBY` seat standing in [`SECRET_DOOR`] to [`SECRET_ENTRY`] in `ZONE_SECRET`, and a
/// `ZONE_SECRET` seat standing in [`SECRET_EXIT`] back to [`SECRET_RETURN`] in `ZONE_LOBBY`.
/// Re-proved below on every `cargo check`: floor inside the lobby band, wall west of every
/// door tile, the exit on the room's east column, the entry an exit tile.
pub const SECRET_ROOM: Gate = Gate { min_x: 352, max_x: 671, min_y: 640, max_y: 799 };
/// The lobby tiles a seat pushes WEST from: the painted arch in the lobby's west wall.
pub const SECRET_DOOR: Gate = Gate { min_x: 80, max_x: 95, min_y: 688, max_y: 751 };
/// The room tiles a seat pushes EAST from: against the room's east wall, where its door is drawn.
pub const SECRET_EXIT: Gate = Gate { min_x: 656, max_x: 671, min_y: 672, max_y: 751 };
/// Where `use_door` puts a seat coming in, and where it puts one going out.
pub const SECRET_ENTRY: (i16, i16) = (656, 704); // tile (41, 44)
pub const SECRET_RETURN: (i16, i16) = (80, 704); // tile (5, 44)

/// Every entrance stands on floor in the table above.
///
/// The generator proves the same thing plus reachability, but only when someone runs it.
/// This fires on every `cargo check`, against the table that actually shipped -- and it
/// is also what keeps `ENTRANCES` from being an unread constant that quietly rots.
const _: () = {
    let mut i = 0;
    while i < ENTRANCES.len() {
        let (x, y) = ENTRANCES[i];
        let tx = (x / TILE) as usize;
        let ty = (y / TILE) as usize;
        assert!(
            x >= 0 && y >= 0 && tx < MAP_TILES && ty < MAP_TILES,
            "an entrance in map::ENTRANCES is off the map -- re-run tools/gen_map.py",
        );
        assert!(
            WALLS[ty] & (1u64 << tx) == 0,
            "an entrance in map::ENTRANCES lands in a wall -- redraw assets/map/arena.json \
             and re-run tools/gen_map.py",
        );
        assert!(
            DAIS[ty] & (1u64 << tx) != 0,
            "an entrance in map::ENTRANCES is off the dais -- a raider would respawn onto \
             the boss's air",
        );
        i += 1;
    }

    // And the boss stands on floor. Same argument, higher stakes: a boss inside rock
    // is a boss whose shell no ray can strip, which is a match that cannot be won and
    // which nothing at runtime reports.
    let (bx, by) = BOSS_SPAWN;
    assert!(
        WALLS[(by / TILE) as usize] & (1u64 << (bx / TILE)) == 0,
        "map::BOSS_SPAWN lands in a wall -- move the `B` in assets/map/arena.json \
         and re-run tools/gen_map.py",
    );

    // The dais is floor, row by row, and nothing on the dais has wall directly over it:
    // one AND per row each. The first is what lets `standable` skip the wall test's
    // work; the second is the pocket `gen_hitboxes.py`'s sweep found -- a raider on a
    // shoulder tile's top corner whose every upward shot died on the cap above it.
    let mut y = 1;
    while y < MAP_TILES {
        assert!(
            DAIS[y] & WALLS[y] == 0,
            "a dais tile is a wall -- re-run tools/gen_map.py",
        );
        assert!(
            DAIS[y] & WALLS[y - 1] == 0,
            "a dais tile has wall directly over it: every upward shot from its top corner \
             dies there -- the boss's air must reach down past it (tools/gen_rooms.py)",
        );
        y += 1;
    }
    assert!(DAIS[0] == 0, "the top border row is dais");

    // The pit band is non-empty and sits inside the map.
    assert!(PIT_TOP >= 0 && PIT_TOP < PIT_BOT && PIT_BOT < (MAP_TILES as i16) * TILE);

    // The boss is reachable by a raider: its anchor is inside the band they are clamped
    // to and on the dais they walk. A boss above `PIT_TOP` would be a target no one can
    // ever stand level with.
    assert!(
        by >= PIT_TOP && by <= PIT_BOT,
        "map::BOSS_SPAWN is outside PIT_TOP..=PIT_BOT -- the raid is clamped away from \
         its own boss; redraw assets/map/arena.json and re-run tools/gen_map.py",
    );
    assert!(
        DAIS[(by / TILE) as usize] & (1u64 << (bx / TILE)) != 0,
        "map::BOSS_SPAWN is off the dais -- the raid can never walk up to its own boss",
    );

    // The gates: one per tier, each a real block, in tier order left to right, every one
    // inside the lobby box -- a lobby seat standing on a gate row inside the pit rows
    // would be outside `PIT_BOT + 1 ..= MAP_MAX_XY` and refused every step -- and above
    // the painted lobby floor the browser frames on. And the boss stands on none of
    // them, which would let a player flip zone by walking into the creature: the
    // assertion the four `GATE_*` literals in `handlers::player` could never carry, since
    // it needs both facts to come out of one grid.
    assert!(GATES.len() == crate::state::N_TIERS, "one gate per difficulty tier");
    let mut tier = 0;
    while tier < GATES.len() {
        let gate = GATES[tier];
        assert!(gate.min_x <= gate.max_x && gate.min_y <= gate.max_y);
        assert!(
            gate.min_y > PIT_BOT && gate.max_y < LOBBY_TOP,
            "a gate is not between the pit and the lobby floor -- re-run tools/gen_map.py",
        );
        assert!(tier == 0 || GATES[tier - 1].max_x < gate.min_x, "gates are tiers, left to right");
        assert!(!gate.contains(bx, by), "map::BOSS_SPAWN is inside a gate block");
        tier += 1;
    }
    assert!(gate_at(bx, by).is_none());

    // The waiting room the browser frames on is the floor under the gates, and every
    // seat it fans out stands on that floor.
    //
    // These four constants exist only for the renderer -- `VIEW_LOBBY` is
    // `LOBBY_TOP..=LOBBY_BOT` plus masonry, and `LOBBY_SPAWN_MIN_X..MAX_X` is what has to
    // be inside it -- so nothing on the chain would ever notice them drifting. That is
    // exactly why the check is here: a hand-edit of this generated file, which the banner
    // at the top forbids and someone will do anyway, shows up as a knight standing
    // outside its own frame with no error anywhere.
    assert!(
        LOBBY_TOP < LOBBY_BOT && LOBBY_BOT < (MAP_TILES as i16) * TILE,
        "the lobby floor band is empty or off the map -- re-run tools/gen_map.py",
    );
    assert!(
        LOBBY_SPAWN_MIN_X <= LOBBY_SPAWN_MAX_X
            && LOBBY_SPAWN_Y >= LOBBY_TOP
            && LOBBY_SPAWN_Y <= LOBBY_BOT,
        "the lobby spawn row is outside the lobby floor band -- the browser would frame \
         the waiting room on floor the seats do not stand on",
    );
    // The two seats at the ends of the fan -- the only two this file names, and the pair
    // the frame is built out of. The other eighteen are swept by the generator.
    assert!(
        WALLS[(LOBBY_SPAWN_Y / TILE) as usize]
            & ((1u64 << (LOBBY_SPAWN_MIN_X / TILE)) | (1u64 << (LOBBY_SPAWN_MAX_X / TILE)))
            == 0,
        "an outermost lobby spawn stands in a wall -- redraw assets/map/arena.json and \
         re-run tools/gen_map.py",
    );

    // The secret room, a third zone over the lobby floor. Every fact `use_door` and the
    // movement rule lean on, re-proved against the bitboard that shipped: the room is floor
    // inside the lobby band, every door tile has wall to its west (the refusal the client
    // knocks with), the exit is the room's east column, the entry is an exit tile and the
    // return a door tile.
    assert!(
        SECRET_ROOM.min_y >= LOBBY_TOP && SECRET_ROOM.max_y <= LOBBY_BOT,
        "the secret room is off the lobby floor band -- re-run tools/gen_map.py",
    );
    let mut ty = SECRET_ROOM.min_y / TILE;
    while ty <= SECRET_ROOM.max_y / TILE {
        let mut tx = SECRET_ROOM.min_x / TILE;
        while tx <= SECRET_ROOM.max_x / TILE {
            assert!(WALLS[ty as usize] & (1u64 << tx) == 0, "a secret room tile is wall");
            tx += 1;
        }
        ty += 1;
    }
    let mut ty = SECRET_DOOR.min_y / TILE;
    while ty <= SECRET_DOOR.max_y / TILE {
        assert!(WALLS[ty as usize] & (1u64 << (SECRET_DOOR.min_x / TILE)) == 0, "a secret door tile is wall");
        assert!(
            WALLS[ty as usize] & (1u64 << (SECRET_DOOR.min_x / TILE - 1)) != 0,
            "no wall west of the secret door -- a step there would be taken, not refused",
        );
        ty += 1;
    }
    assert!(SECRET_ROOM.contains(SECRET_EXIT.min_x, SECRET_EXIT.min_y) && SECRET_ROOM.contains(SECRET_EXIT.max_x, SECRET_EXIT.max_y));
    assert!(SECRET_EXIT.max_x == SECRET_ROOM.max_x, "the secret exit is not the room's east column");
    assert!(SECRET_EXIT.contains(SECRET_ENTRY.0, SECRET_ENTRY.1), "the secret entry is not an exit tile");
    assert!(SECRET_DOOR.contains(SECRET_RETURN.0, SECRET_RETURN.1), "the secret return is not a door tile");
    assert!(!SECRET_ROOM.contains(SECRET_DOOR.min_x, SECRET_DOOR.min_y), "the secret door is inside the room");
};

#[cfg(test)]
mod tests {
    use super::*;

    const fn solid(tx: usize, ty: usize) -> bool {
        tx >= MAP_TILES || ty >= MAP_TILES || WALLS[ty] & (1u64 << tx) != 0
    }

    fn floor(tx: usize, ty: usize) -> bool {
        !solid(tx, ty)
    }

    fn dais(tx: usize, ty: usize) -> bool {
        tx < MAP_TILES && ty < MAP_TILES && DAIS[ty] & (1u64 << tx) != 0
    }

    /// 4-connected flood fill from the boss tile over the tiles `open` admits, confined
    /// to tile rows `top..=bot`.
    ///
    /// 4- and not 8-connected on purpose: movement is 8-way but only tests the
    /// destination tile, so a diagonal can squeeze past a corner. Accepting that here
    /// would sign off on passages that exist by accident.
    ///
    /// Relaxed to a fixpoint rather than queued, so it allocates nothing: 64x64 is four
    /// thousand tiles and this is a test.
    fn reachable(top: usize, bot: usize, open: fn(usize, usize) -> bool) -> [[bool; MAP_TILES]; MAP_TILES] {
        let mut seen = [[false; MAP_TILES]; MAP_TILES];
        seen[(BOSS_SPAWN.1 / TILE) as usize][(BOSS_SPAWN.0 / TILE) as usize] = true;
        let mut changed = true;
        while changed {
            changed = false;
            for ty in top..=bot {
                for tx in 0..MAP_TILES {
                    if seen[ty][tx] || !open(tx, ty) {
                        continue;
                    }
                    let touching = (ty > top && seen[ty - 1][tx])
                        || (ty < bot && seen[ty + 1][tx])
                        || (tx > 0 && seen[ty][tx - 1])
                        || (tx + 1 < MAP_TILES && seen[ty][tx + 1]);
                    if touching {
                        seen[ty][tx] = true;
                        changed = true;
                    }
                }
            }
        }
        seen
    }

    /// One room, not several. `tools/gen_map.py` proves this against `arena.json`, but
    /// only when someone runs it; this proves it against the table that actually
    /// shipped, and it is what stands behind "the gate is reachable from every lobby
    /// spawn" -- both are floor, and every floor tile is in the same component.
    #[test]
    fn every_floor_tile_is_one_room() {
        let seen = reachable(0, MAP_TILES - 1, floor);
        for ty in 0..MAP_TILES {
            for tx in 0..MAP_TILES {
                assert_eq!(
                    !solid(tx, ty),
                    seen[ty][tx],
                    "tile ({tx}, {ty}) is floor but sealed off from the boss",
                );
            }
        }
    }

    /// The border ring is closed, so the coordinate clamp is never the only thing
    /// holding a player on the map.
    #[test]
    fn the_border_is_closed() {
        for i in 0..MAP_TILES {
            for (x, y) in [(i, 0), (i, MAP_TILES - 1), (0, i), (MAP_TILES - 1, i)] {
                assert!(solid(x, y), "border tile ({x}, {y}) is not wall");
            }
        }
    }

    /// The dais is one room *on its own terms*. A raider may only stand on dais tiles,
    /// so a pinch in the shaping cannot be walked around through the air the way
    /// [`every_floor_tile_is_one_room`] would let you. The two are not the same test,
    /// and this is the one that catches a shaped dais cut in half.
    #[test]
    fn the_dais_is_one_room_a_raider_can_cross() {
        let (top, bot) = ((PIT_TOP / TILE) as usize, (PIT_BOT / TILE) as usize);
        let seen = reachable(top, bot, dais);
        let mut tiles = 0usize;
        for ty in 0..MAP_TILES {
            for tx in 0..MAP_TILES {
                if dais(tx, ty) {
                    tiles += 1;
                    assert!(ty >= top && ty <= bot, "dais tile ({tx}, {ty}) is outside the band");
                    assert!(seen[ty][tx], "dais tile ({tx}, {ty}) is cut off from the boss");
                }
            }
        }
        assert_eq!(tiles, 1198, "the drawn dais changed size");
    }

    /// Every respawn door is on the dais, inside the pit band. A raider respawned off it
    /// is a seat governed by walls alone until it walks onto the dais, standing where the
    /// painting shows no floor, with nothing logged.
    #[test]
    fn every_door_is_on_the_dais() {
        for (x, y) in ENTRANCES {
            assert!(
                y >= PIT_TOP && y <= PIT_BOT,
                "entrance ({x}, {y}) is outside PIT_TOP..=PIT_BOT",
            );
            assert!(dais((x / TILE) as usize, (y / TILE) as usize));
        }
    }

    /// Every gate block is walkable end to end, with wall on both sides of it on every one
    /// of its rows, and `gate_at` answers its own tier on every unit of it and nothing on
    /// the wall beside it. Walling any of a block is a tier nobody can pick; a block that
    /// runs into its neighbour is two tiers `gate_at` cannot tell apart.
    #[test]
    fn every_gate_is_a_walled_block_that_names_its_tier() {
        for (tier, gate) in GATES.iter().enumerate() {
            for ty in (gate.min_y / TILE)..=(gate.max_y / TILE) {
                for tx in (gate.min_x / TILE)..=(gate.max_x / TILE) {
                    assert!(!solid(tx as usize, ty as usize), "gate {tier} tile ({tx}, {ty}) is wall");
                    assert_eq!(gate_at(tx * TILE, ty * TILE), Some(tier as u8));
                    assert_eq!(gate_at(tx * TILE + TILE - 1, ty * TILE + TILE - 1), Some(tier as u8));
                }
                assert!(solid((gate.min_x / TILE - 1) as usize, ty as usize), "gate {tier} is open to the west");
                assert!(solid((gate.max_x / TILE + 1) as usize, ty as usize), "gate {tier} is open to the east");
                assert_eq!(gate_at(gate.min_x - 1, ty * TILE), None);
                assert_eq!(gate_at(gate.max_x + 1, ty * TILE), None);
            }
            assert_eq!(gate_at(gate.min_x, gate.min_y - 1), None);
            assert_eq!(gate_at(gate.min_x, gate.max_y + 1), None);
        }
    }

    /// The boss's air is open floor. `handlers::shoot`'s raycast tests `is_wall` before
    /// the part rectangles, so one wall tile between a stand and the boss kills every
    /// shot in that column -- a raid that cannot be won, reporting nothing. The air is
    /// held off the raid by `DAIS`, a movement rule, and this is the test that keeps it
    /// from becoming wall the next time someone redraws the grid.
    ///
    /// Both spans are generated -- rows 1..=23, columns 2..=61 --
    /// rather than written as `1..PIT_TOP` and `1..MAP_TILES - 1`: the first form stopped
    /// being true when the dais grew past the boss's feet and the air had to reach down
    /// beside its shoulders, the second the moment the side perimeter was drawn two
    /// tiles thick.
    #[test]
    fn the_boss_air_is_open() {
        for ty in 1..=23 {
            for tx in 2..=61 {
                assert!(
                    !solid(tx, ty),
                    "tile ({tx}, {ty}) is wall in the boss's air -- every shot in that \
                     column dies on it before reaching the boss",
                );
            }
        }
    }
}
