//! Arena wall bitboard.
//!
//! GENERATED by tools/gen_map.py from assets/map/arena.json. Do not edit.
//! The grid there is written by tools/gen_rooms.py from the room paintings: edit
//! `rooms` in that file, run gen_rooms.py, then re-run this tool.
//!
//! Bit *x* of row *y* is set when tile (x, y) is solid, which is the shape
//! `handlers::player::is_wall` already indexes and the cheapest wall test that
//! exists: one shift and one mask, no account, no CU worth measuring.
//!
//! The map is static per deployment, so it lives in the program image rather than
//! in an account. An account would cost rent, would have to be delegated and
//! committed with the arena, and would spend one of the ~38 account keys an ER
//! transaction is allowed -- with no address lookup tables available to buy it
//! back. This table costs 512 bytes of .so and zero keys. If maps ever need to
//! vary at runtime the upgrade path is a second generated table and a `map_id: u8`
//! on `Arena` selecting between them; still no account, still no key.

/// Map edge in tiles -- the width of the ASCII grid in `assets/map/arena.json`,
/// which is also what sizes the table below.
///
/// This is the only declaration of it in the program: `handlers::player` re-exports
/// this constant and `handlers::tick` casts it, so there is nothing left to assert it
/// against. An `assert!(MAP_TILES == player::MAP_TILES)` used to sit here, and once
/// `player.rs` became a `pub use` it was comparing this value to itself -- a drift
/// guard over a fact that is no longer stored twice is theatre, so it is gone.
pub const MAP_TILES: usize = 64;

/// Arena-space units per tile, compiled from `arena.json`'s `tile_size`.
///
/// Same story as `MAP_TILES`: sole declaration, re-exported rather than restated, and
/// `handlers::tick::ARENA_SIZE` is `MAP_TILES * TILE` derived from these two.
pub const TILE: i16 = 16;

/// Wall bitboard: bit *x* of row *y* set means tile (x, y) is solid.
///
/// Layout, top to bottom. Open floor for the boss's air, then the pit -- the lower half
/// of the painted dais, narrowing to its stairs -- then the gate block under the stairs,
/// then the painted lobby floor. The whole vertical order is the fight: you walk up the
/// lobby, through the gate, up the stairs onto the dais, and the creature is above you.
///
/// Both rooms are open floor with zero interior obstacles. `tools/gen_map.py` holds
/// them that way: at most one contiguous run of floor per row, so a free-standing
/// block anywhere splits a row and is refused. Perimeter architecture, banners,
/// torches, chains and floor markings are paint, never wall tiles.
///
/// The rows above the pit are floor, not wall, and that is load-bearing rather than
/// lazy drawing -- see [`PIT_TOP`].
pub const WALLS: [u64; MAP_TILES] = [
    0xffffffffffffffff, // y=0  ################################################################
    0xc000000000000003, // y=1  ##............................................................##
    0xc000000000000003, // y=2  ##............................................................##
    0xc000000000000003, // y=3  ##............................................................##
    0xc000000000000003, // y=4  ##............................................................##
    0xc000000000000003, // y=5  ##............................................................##
    0xc000000000000003, // y=6  ##............................................................##
    0xc000000000000003, // y=7  ##............................................................##
    0xc000000000000003, // y=8  ##............................................................##
    0xc000000000000003, // y=9  ##............................................................##
    0xc000000000000003, // y=10 ##............................................................##
    0xc000000000000003, // y=11 ##............................................................##
    0xc000000000000003, // y=12 ##............................................................##
    0xc000000000000003, // y=13 ##............................................................##
    0xc000000000000003, // y=14 ##............................................................##
    0xc000000000000003, // y=15 ##............................................................##
    0xc000000000000003, // y=16 ##............................................................##
    0xc000000000000003, // y=17 ##............................................................##
    0xc000000000000003, // y=18 ##............................................................##
    0xc000000000000003, // y=19 ##............................................................##
    0xc000000000000003, // y=20 ##............................................................##
    0xc000000000000003, // y=21 ##............................................................##
    0xe000000000000007, // y=22 ###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPBPPPPPPPPPPPPPPPPPPPPPPPPPPPP###
    0xe000000000000007, // y=23 ###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###
    0xe000000000000007, // y=24 ###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###
    0xe000000000000007, // y=25 ###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###
    0xe000000000000007, // y=26 ###PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###
    0xf00000000000000f, // y=27 ####PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP####
    0xf00000000000000f, // y=28 ####PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP####
    0xf80000000000001f, // y=29 #####PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#####
    0xfc0000000000003f, // y=30 ######PPPPPPEPPPPPPPPPEPPPPPPPPPPPPPPPPPPEPPPPPPPPPEPPPPPP######
    0xfe0000000000007f, // y=31 #######PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#######
    0xff800000000001ff, // y=32 #########PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP#########
    0xffc00000000003ff, // y=33 ##########PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP##########
    0xfff0000000000fff, // y=34 ############PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP############
    0xfffe000000007fff, // y=35 ###############PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP###############
    0xffffe0000007ffff, // y=36 ###################PPPPPPPPPPPPPPPPPPPPPPPPPP###################
    0xffffff0000ffffff, // y=37 ########################PPPPPPPPPPPPPPPP########################
    0xfffffff00fffffff, // y=38 ############################GGGGGGGG############################
    0xfffffff00fffffff, // y=39 ############################GGGGGGGG############################
    0xfe0000000000007f, // y=40 #######..................................................#######
    0xfe0000000000007f, // y=41 #######..................................................#######
    0xfe0000000000007f, // y=42 #######..................................................#######
    0xfe0000000000007f, // y=43 #######..................................................#######
    0xfe0000000000007f, // y=44 #######..................................................#######
    0xfe0000000000007f, // y=45 #######..................................................#######
    0xfe0000000000007f, // y=46 #######..................................................#######
    0xfe0000000000007f, // y=47 #######..................................................#######
    0xfe0000000000007f, // y=48 #######..................................................#######
    0xfe0000000000007f, // y=49 #######..................................................#######
    0xfe0000000000007f, // y=50 #######..................................................#######
    0xfe0000000000007f, // y=51 #######..................................................#######
    0xfe0000000000007f, // y=52 #######..................................................#######
    0xfe0000000000007f, // y=53 #######..................................................#######
    0xfe0000000000007f, // y=54 #######..................................................#######
    0xfe0000000000007f, // y=55 #######..................................................#######
    0xfe0000000000007f, // y=56 #######..................................................#######
    0xfe0000000000007f, // y=57 #######..................................................#######
    0xfe0000000000007f, // y=58 #######..................................................#######
    0xfe0000000000007f, // y=59 #######..................................................#######
    0xfe0000000000007f, // y=60 #######..................................................#######
    0xfe0000000000007f, // y=61 #######..................................................#######
    0xfe0000000000007f, // y=62 #######..................................................#######
    0xffffffffffffffff, // y=63 ################################################################
];

/// The four `E` marks on the drawn map, in world units at the tile's top-left corner --
/// the same convention `handlers::player::LOBBY_ENTRANCE` and `GATE_MIN_X` are written
/// in, and the one `is_wall` inverts with `pos / TILE`.
///
/// Row-major scan order (top to bottom, then left to right), *not* compass order.
/// Redrawing the grid re-orders this array and nothing may assume otherwise.
///
/// This exists so respawn points are *read out of the map* instead of restated beside it.
/// `handlers::tick::entrance_for` picks `ENTRANCES[seat % 4]` and fans that door's ranks
/// along the wall it is set into; the `ENTRANCE_X`/`ENTRANCE_Y` pair that used to
/// describe the arena a second time is gone. Move an `E` in the grid, re-run the tool,
/// and the respawn moves with it.
pub const ENTRANCES: [(i16, i16); 4] = [
    (192, 480), // tile (12, 30)
    (352, 480), // tile (22, 30)
    (656, 480), // tile (41, 30)
    (816, 480), // tile (51, 30)
];

/// The `B` heart tile: where the boss stands, in world units at the tile's top-left
/// corner -- the same convention as [`ENTRANCES`].
///
/// `handlers::init` reads this and writes it to `Boss.x`/`Boss.y` on every spawn and
/// respawn. It is here rather than there because the boss's position is a fact about
/// the *map*: every rectangle in `hitboxes.rs` is an offset from this point, and the
/// open rows above the pit are the only space on the grid tall enough to hold them.
///
/// It sits at the *top* of the pit band rather than in the middle of the map: the boss
/// is drawn upward from here, so the creature fills the top of the frame and the raid
/// shoots up at it from the pit below. The assertion block at the bottom of this file
/// proves it is on floor, inside `PIT_TOP..=PIT_BOT`, and outside the gate.
///
/// It used to be a pair of literals in `init.rs` reading (512, 320) -- tile (32, 20),
/// which was a two-tile corridor on the map of the time. The shell was mostly inside
/// solid rock and `shoot`'s ray died on the corridor wall before reaching it, while
/// this generator "checked" the spawn against a hardcoded map centre attributed to a
/// `start_match` write that never existed. Three copies, two of them wrong, and the
/// fight had never been run on chain so nothing had noticed.
pub const BOSS_SPAWN: (i16, i16) = (512, 352); // tile (32, 22)

/// The raider box: a `ZONE_ARENA` player's y is confined to `PIT_TOP..=PIT_BOT`.
///
/// Compiled from the `P` block's bounding rows (22..37) -- inclusive of the last
/// row's last unit, which is the form `move_player` compares a *destination* against.
/// Comparing the destination and not the current position is load-bearing: a player who
/// flips zone while standing on the gate is below `PIT_BOT`, and a current-position test
/// would refuse every direction and freeze them there for the match.
///
/// This is a movement rule and deliberately **not** a wall. The rows above the pit are
/// open floor because `shoot`'s raycast tests `is_wall` before the part rectangles, so a
/// single wall tile between a player and the boss would kill every shot in that column
/// with nothing logged anywhere. The clamp holds raiders out of the boss's air; the
/// bitboard holds bullets and rays to the map. Two barriers, and they can disagree --
/// `tools/gen_map.py` proves the pit is one connected room and that the gate walks into
/// it, which is the only guard against a clamp that boxes someone in open floor.
pub const PIT_TOP: i16 = 352; // tile row 22
pub const PIT_BOT: i16 = 607; // tile row 37, last unit

/// The gate block `enter_gate` demands the player be standing in, compiled from the `G`
/// rectangle -- tiles (28, 38)..(35, 39).
///
/// These were four hand literals in `handlers::player` that `gen_map.py` parsed back out
/// of Rust source to validate against the drawn grid: one fact stored twice, with the
/// tool agreeing with whichever copy it read. Drawing them is what lets the assertion
/// below prove `BOSS_SPAWN` is outside the gate on every `cargo check`.
pub const GATE_MIN_X: i16 = 448;
pub const GATE_MAX_X: i16 = 575;
pub const GATE_MIN_Y: i16 = 608;
pub const GATE_MAX_Y: i16 = 639;

/// The x span `handlers::player::lobby_spawn` fans the seats across, and their shared row.
///
/// Emitted so the client's lobby camera can frame every spawn instead of guessing. Seat 0
/// sits `MAX_SEATS / 2` spacings left of `LOBBY_ENTRANCE`, which a gate-centred camera
/// cropped off screen -- and seat 0 is what the first player to join always gets.
pub const LOBBY_SPAWN_MIN_X: i16 = 208;
pub const LOBBY_SPAWN_MAX_X: i16 = 664;
pub const LOBBY_SPAWN_Y: i16 = 832;

/// The lobby floor band: the drawn floor rows below the gate (40..62), in world
/// units, `LOBBY_BOT` inclusive of the last row's last unit exactly as [`PIT_BOT`] is.
///
/// A *drawing* fact, not a movement rule -- `player::zone_box` holds a `ZONE_LOBBY` seat
/// in `PIT_BOT + 1 ..= MAP_MAX_XY`, which is wider: it also covers the gate rows and the
/// border ring. Emitted because the renderer frames on the floor, not on the box:
/// `docs/architecture/17-fullscreen-spec.md` 1.1 builds `VIEW_LOBBY` as this band plus 208
/// units of masonry above and 80 below, and its self-check asserts the frame still lands
/// on `LOBBY_BOT + 1`. Retyping 640/1008 in the browser beside a map that owns them is the
/// drift this generator exists to prevent.
pub const LOBBY_TOP: i16 = 640; // tile row 40
pub const LOBBY_BOT: i16 = 1007; // tile row 62, last unit

/// Every entrance stands on floor in the table above.
///
/// The generator proves the same thing plus reachability, but only when someone runs it.
/// This fires on every `cargo check`, against the table that actually shipped -- and it
/// is also what keeps `ENTRANCES` from being an unread constant that quietly rots.
const _: () = {
    let mut i = 0;
    while i < ENTRANCES.len() {
        let (x, y) = ENTRANCES[i];
        let tx = (x / TILE) as usize;
        let ty = (y / TILE) as usize;
        assert!(
            x >= 0 && y >= 0 && tx < MAP_TILES && ty < MAP_TILES,
            "an entrance in map::ENTRANCES is off the map -- re-run tools/gen_map.py",
        );
        assert!(
            WALLS[ty] & (1u64 << tx) == 0,
            "an entrance in map::ENTRANCES lands in a wall -- redraw assets/map/arena.json \
             and re-run tools/gen_map.py",
        );
        i += 1;
    }

    // And the boss stands on floor. Same argument, higher stakes: a boss inside rock
    // is a boss whose shell no ray can strip, which is a match that cannot be won and
    // which nothing at runtime reports.
    let (bx, by) = BOSS_SPAWN;
    assert!(
        WALLS[(by / TILE) as usize] & (1u64 << (bx / TILE)) == 0,
        "map::BOSS_SPAWN lands in a wall -- move the `B` in assets/map/arena.json \
         and re-run tools/gen_map.py",
    );

    // The pit band is non-empty and sits inside the map.
    assert!(PIT_TOP >= 0 && PIT_TOP < PIT_BOT && PIT_BOT < (MAP_TILES as i16) * TILE);
    assert!(GATE_MIN_X <= GATE_MAX_X && GATE_MIN_Y <= GATE_MAX_Y);

    // The boss is reachable by a raider: its anchor is inside the band they are clamped
    // to. A boss above `PIT_TOP` would be a target no one can ever stand level with.
    assert!(
        by >= PIT_TOP && by <= PIT_BOT,
        "map::BOSS_SPAWN is outside PIT_TOP..=PIT_BOT -- the raid is clamped away from \
         its own boss; redraw assets/map/arena.json and re-run tools/gen_map.py",
    );

    // And it is not standing on the gate, which would let a player flip zone by walking
    // into the creature. This is the assertion the four `GATE_*` literals in
    // `handlers::player` could never carry: it needs both facts to come out of one grid.
    assert!(
        !(bx >= GATE_MIN_X && bx <= GATE_MAX_X && by >= GATE_MIN_Y && by <= GATE_MAX_Y),
        "map::BOSS_SPAWN is inside the gate block",
    );

    // The gate is immediately below the pit, so stepping out of it lands in the band.
    assert!(
        GATE_MIN_Y == PIT_BOT + 1,
        "the gate does not adjoin the pit -- a player who flips zone on it would have \
         no legal destination inside PIT_TOP..=PIT_BOT and would freeze",
    );

    // The waiting room the browser frames on is the floor immediately under the gate,
    // and every seat it fans out stands on that floor.
    //
    // These four constants exist only for the renderer -- `VIEW_LOBBY` is
    // `LOBBY_TOP..=LOBBY_BOT` plus masonry, and `LOBBY_SPAWN_MIN_X..MAX_X` is what has to
    // be inside it -- so nothing on the chain would ever notice them drifting. That is
    // exactly why the check is here: a hand-edit of this generated file, which the banner
    // at the top forbids and someone will do anyway, shows up as a knight standing
    // outside its own frame with no error anywhere.
    assert!(
        LOBBY_TOP == GATE_MAX_Y + 1
            && LOBBY_TOP < LOBBY_BOT
            && LOBBY_BOT < (MAP_TILES as i16) * TILE,
        "the lobby floor band does not start where the gate ends -- re-run tools/gen_map.py",
    );
    assert!(
        LOBBY_SPAWN_MIN_X <= LOBBY_SPAWN_MAX_X
            && LOBBY_SPAWN_Y >= LOBBY_TOP
            && LOBBY_SPAWN_Y <= LOBBY_BOT,
        "the lobby spawn row is outside the lobby floor band -- the browser would frame \
         the waiting room on floor the seats do not stand on",
    );
    // The two seats at the ends of the fan -- the only two this file names, and the pair
    // the frame is built out of. The other eighteen are swept by the generator.
    assert!(
        WALLS[(LOBBY_SPAWN_Y / TILE) as usize]
            & ((1u64 << (LOBBY_SPAWN_MIN_X / TILE)) | (1u64 << (LOBBY_SPAWN_MAX_X / TILE)))
            == 0,
        "an outermost lobby spawn stands in a wall -- redraw assets/map/arena.json and \
         re-run tools/gen_map.py",
    );
};

#[cfg(test)]
mod tests {
    use super::*;

    const fn solid(tx: usize, ty: usize) -> bool {
        tx >= MAP_TILES || ty >= MAP_TILES || WALLS[ty] & (1u64 << tx) != 0
    }

    /// 4-connected flood fill from the boss tile, confined to tile rows `top..=bot`.
    ///
    /// 4- and not 8-connected on purpose: movement is 8-way but only tests the
    /// destination tile, so a diagonal can squeeze past a corner. Accepting that here
    /// would sign off on passages that exist by accident.
    ///
    /// Relaxed to a fixpoint rather than queued, so it allocates nothing: 64x64 is four
    /// thousand tiles and this is a test.
    fn reachable(top: usize, bot: usize) -> [[bool; MAP_TILES]; MAP_TILES] {
        let mut seen = [[false; MAP_TILES]; MAP_TILES];
        seen[(BOSS_SPAWN.1 / TILE) as usize][(BOSS_SPAWN.0 / TILE) as usize] = true;
        let mut changed = true;
        while changed {
            changed = false;
            for ty in top..=bot {
                for tx in 0..MAP_TILES {
                    if seen[ty][tx] || solid(tx, ty) {
                        continue;
                    }
                    let touching = (ty > top && seen[ty - 1][tx])
                        || (ty < bot && seen[ty + 1][tx])
                        || (tx > 0 && seen[ty][tx - 1])
                        || (tx + 1 < MAP_TILES && seen[ty][tx + 1]);
                    if touching {
                        seen[ty][tx] = true;
                        changed = true;
                    }
                }
            }
        }
        seen
    }

    /// One room, not several. `tools/gen_map.py` proves this against `arena.json`, but
    /// only when someone runs it; this proves it against the table that actually
    /// shipped, and it is what stands behind "the gate is reachable from every lobby
    /// spawn" -- both are floor, and every floor tile is in the same component.
    #[test]
    fn every_floor_tile_is_one_room() {
        let seen = reachable(0, MAP_TILES - 1);
        for ty in 0..MAP_TILES {
            for tx in 0..MAP_TILES {
                assert_eq!(
                    !solid(tx, ty),
                    seen[ty][tx],
                    "tile ({tx}, {ty}) is floor but sealed off from the boss",
                );
            }
        }
    }

    /// The border ring is closed, so the coordinate clamp is never the only thing
    /// holding a player on the map.
    #[test]
    fn the_border_is_closed() {
        for i in 0..MAP_TILES {
            for (x, y) in [(i, 0), (i, MAP_TILES - 1), (0, i), (MAP_TILES - 1, i)] {
                assert!(solid(x, y), "border tile ({x}, {y}) is not wall");
            }
        }
    }

    /// The pit is one room *on its own terms*. A raider is clamped to
    /// `PIT_TOP..=PIT_BOT`, so a pinch in the corner shaping cannot be walked around the
    /// way [`every_floor_tile_is_one_room`] would let you. The two are not the same
    /// test, and this is the one that catches a shaped pit cut in half.
    #[test]
    fn the_pit_is_one_room_a_raider_can_cross() {
        let (top, bot) = ((PIT_TOP / TILE) as usize, (PIT_BOT / TILE) as usize);
        let seen = reachable(top, bot);
        let mut floor = 0usize;
        for ty in top..=bot {
            for tx in 0..MAP_TILES {
                if !solid(tx, ty) {
                    floor += 1;
                    assert!(seen[ty][tx], "pit tile ({tx}, {ty}) is cut off from the boss");
                }
            }
        }
        assert_eq!(floor, 764, "the drawn pit changed size");
    }

    /// Every respawn door is inside the pit band. A raider respawned above `PIT_TOP` or
    /// below `PIT_BOT` is a seat clamped out of every legal move, with nothing logged.
    #[test]
    fn every_door_is_inside_the_raider_box() {
        for (x, y) in ENTRANCES {
            assert!(
                y >= PIT_TOP && y <= PIT_BOT,
                "entrance ({x}, {y}) is outside PIT_TOP..=PIT_BOT",
            );
            assert!(!solid((x / TILE) as usize, (y / TILE) as usize));
        }
    }

    /// The gate block is walkable end to end, and its columns step straight into the
    /// pit. Walling any of it is a lobby nobody can leave; a gate that does not adjoin
    /// the pit is a player who flips zone and then cannot move.
    #[test]
    fn the_gate_is_floor_and_walks_into_the_pit() {
        for ty in (GATE_MIN_Y / TILE)..=(GATE_MAX_Y / TILE) {
            for tx in (GATE_MIN_X / TILE)..=(GATE_MAX_X / TILE) {
                assert!(!solid(tx as usize, ty as usize), "gate tile ({tx}, {ty}) is wall");
            }
        }
        let last_pit_row = (PIT_BOT / TILE) as usize;
        for tx in (GATE_MIN_X / TILE)..=(GATE_MAX_X / TILE) {
            assert!(
                !solid(tx as usize, last_pit_row),
                "gate column {tx} runs into wall at the pit's last row",
            );
        }
    }

    /// The boss's air is open floor. `handlers::shoot`'s raycast tests `is_wall` before
    /// the part rectangles, so one wall tile above the pit kills every shot in that
    /// column -- a raid that cannot be won, reporting nothing. The pit ceiling is
    /// `PIT_TOP`, a movement rule, and this is the test that keeps it from becoming a
    /// wall the next time someone redraws the grid.
    ///
    /// The column span is generated (2..=61) rather than written as
    /// `1..MAP_TILES - 1`: that form assumed a one-tile border ring and started
    /// failing the moment the side perimeter was drawn two tiles thick.
    #[test]
    fn the_boss_air_above_the_pit_is_open() {
        let top = (PIT_TOP / TILE) as usize;
        for ty in 1..top {
            for tx in 2..=61 {
                assert!(
                    !solid(tx, ty),
                    "tile ({tx}, {ty}) is wall above PIT_TOP -- every shot in that \
                     column dies on it before reaching the boss",
                );
            }
        }
    }
}
