//! Arena wall bitboard.
//!
//! GENERATED by tools/gen_map.py from assets/map/arena.json. Do not edit.
//! Redraw the ASCII grid in that file and re-run the tool.
//!
//! Bit *x* of row *y* is set when tile (x, y) is solid, which is the shape
//! `handlers::player::is_wall` already indexes and the cheapest wall test that
//! exists: one shift and one mask, no account, no CU worth measuring.
//!
//! The map is static per deployment, so it lives in the program image rather than
//! in an account. An account would cost rent, would have to be delegated and
//! committed with the arena, and would spend one of the ~38 account keys an ER
//! transaction is allowed -- with no address lookup tables available to buy it
//! back. This table costs 512 bytes of .so and zero keys. If maps ever need to
//! vary at runtime the upgrade path is a second generated table and a `map_id: u8`
//! on `Arena` selecting between them; still no account, still no key.

/// Map edge in tiles -- the width of the ASCII grid in `assets/map/arena.json`,
/// which is also what sizes the table below.
///
/// This is the only declaration of it in the program: `handlers::player` re-exports
/// this constant and `handlers::tick` casts it, so there is nothing left to assert it
/// against. An `assert!(MAP_TILES == player::MAP_TILES)` used to sit here, and once
/// `player.rs` became a `pub use` it was comparing this value to itself -- a drift
/// guard over a fact that is no longer stored twice is theatre, so it is gone.
pub const MAP_TILES: usize = 64;

/// Arena-space units per tile, compiled from `arena.json`'s `tile_size`.
///
/// Same story as `MAP_TILES`: sole declaration, re-exported rather than restated, and
/// `handlers::tick::ARENA_SIZE` is `MAP_TILES * TILE` derived from these two.
pub const TILE: i16 = 16;

/// Wall bitboard: bit *x* of row *y* set means tile (x, y) is solid.
///
/// Layout: a central open heart chamber around the boss spawn, four 2-tile-wide
/// corridors radiating N/S/E/W as the only approaches to it, four large outer
/// halls broken up by 2x2 pillars, and four edge entrances. The 2-wide fronts are
/// the difficulty system -- a corridor has almost no perimeter to defend, a hall
/// has perimeter everywhere.
pub const WALLS: [u64; MAP_TILES] = [
    0xffffffffffffffff, // y=0  ################################################################
    0x8000000000000001, // y=1  #...............................E..............................#
    0x830c30c30c30c30d, // y=2  #.##....##....##....##....##....##....##....##....##....##.....#
    0x830c30c30c30c30d, // y=3  #.##....##....##....##....##....##....##....##....##....##.....#
    0x8000000000000001, // y=4  #..............................................................#
    0x87e00000000007e1, // y=5  #....######..........................................######....#
    0x87e00000000007e1, // y=6  #....######..........................................######....#
    0x87e00000000007e1, // y=7  #....######..........................................######....#
    0x87ec30c30c30c7ed, // y=8  #.##.######...##....##....##....##....##....##....##.######....#
    0x87ec30c30c30c7ed, // y=9  #.##.######...##....##....##....##....##....##....##.######....#
    0x87e00000000007e1, // y=10 #....######..........................................######....#
    0x8000000000000001, // y=11 #..............................................................#
    0x8000000000000001, // y=12 #..............................................................#
    0x8000000000000001, // y=13 #..............................................................#
    0x830c00000000030d, // y=14 #.##....##........................................##....##.....#
    0x830dfffe7fff830d, // y=15 #.##....##.....################..################.##....##.....#
    0x8001fffe7fff8001, // y=16 #..............################..################..............#
    0x8001fffe7fff8001, // y=17 #..............################..################..............#
    0x8001fffe7fff8001, // y=18 #..............################..################..............#
    0x8001fffe7fff8001, // y=19 #..............################..################..............#
    0x830dfffe7fff830d, // y=20 #.##....##.....################..################.##....##.....#
    0x830dfffe7fff830d, // y=21 #.##....##.....################..################.##....##.....#
    0x8001fffe7fff8001, // y=22 #..............################..################..............#
    0x8001fffe7fff8001, // y=23 #..............################..################..............#
    0x8001ff0000ff8001, // y=24 #..............#########................#########..............#
    0x8001ff0000ff8001, // y=25 #..............#########................#########..............#
    0x830dff0000ff830d, // y=26 #.##....##.....#########................#########.##....##.....#
    0x830dff0000ff830d, // y=27 #.##....##.....#########................#########.##....##.....#
    0x8001ff0000ff8001, // y=28 #..............#########................#########..............#
    0x8001ff0000ff8001, // y=29 #..............#########................#########..............#
    0x8001ff0000ff8001, // y=30 #..............#########................#########..............#
    0x8000000000000001, // y=31 #..............................................................#
    0x830c00000000030d, // y=32 #E##....##......................B.................##....##....E#
    0x830dff0000ff830d, // y=33 #.##....##.....#########................#########.##....##.....#
    0x8001ff0000ff8001, // y=34 #..............#########................#########..............#
    0x8001ff0000ff8001, // y=35 #..............#########................#########..............#
    0x8001ff0000ff8001, // y=36 #..............#########................#########..............#
    0x8001ff0000ff8001, // y=37 #..............#########................#########..............#
    0x830dff0000ff830d, // y=38 #.##....##.....#########................#########.##....##.....#
    0x830dff0000ff830d, // y=39 #.##....##.....#########................#########.##....##.....#
    0x8001fffe7fff8001, // y=40 #..............################..################..............#
    0x8001fffe7fff8001, // y=41 #..............################..################..............#
    0x8001fffe7fff8001, // y=42 #..............################..################..............#
    0x8001fffe7fff8001, // y=43 #..............################..################..............#
    0x830dfffe7fff830d, // y=44 #.##....##.....################..################.##....##.....#
    0x830dfffe7fff830d, // y=45 #.##....##.....################..################.##....##.....#
    0x8001fffe7fff8001, // y=46 #..............################..################..............#
    0x8001fffe7fff8001, // y=47 #..............################..################..............#
    0x8001fffe7fff8001, // y=48 #..............################..################..............#
    0x8000000000000001, // y=49 #..............................................................#
    0x830c30c30c30c30d, // y=50 #.##....##....##....##....##....##....##....##....##....##.....#
    0x830c30c30c30c30d, // y=51 #.##....##....##....##....##....##....##....##....##....##.....#
    0x8000000000000001, // y=52 #..............................................................#
    0x87e00000000007e1, // y=53 #....######..........................................######....#
    0x87e00000000007e1, // y=54 #....######..........................................######....#
    0x87e00000000007e1, // y=55 #....######..........................................######....#
    0x87ec30c30c30c7ed, // y=56 #.##.######...##....##....##....##....##....##....##.######....#
    0x87ec30c30c30c7ed, // y=57 #.##.######...##....##....##....##....##....##....##.######....#
    0x87e00000000007e1, // y=58 #....######..........................................######....#
    0x8000000000000001, // y=59 #..............................................................#
    0x8000000000000001, // y=60 #..............................................................#
    0x8000000000000001, // y=61 #..............................................................#
    0x8000000000000001, // y=62 #...............................E..............................#
    0xffffffffffffffff, // y=63 ################################################################
];

/// The four `E` marks on the drawn map, in world units at the tile's top-left corner --
/// the same convention `handlers::player::LOBBY_ENTRANCE` and `GATE_MIN_X` are written
/// in, and the one `is_wall` inverts with `pos / TILE`.
///
/// Row-major scan order (top to bottom, then left to right), *not* compass order: for
/// the map as drawn that happens to be north, west, east, south, but redrawing the grid
/// re-orders this array and nothing may assume otherwise.
///
/// This exists so respawn points are *read out of the map* instead of restated beside it.
/// `handlers::tick::entrance_for` picks `ENTRANCES[seat % 4]` and fans that door's ranks
/// along the wall it is set into; the `ENTRANCE_X`/`ENTRANCE_Y` pair that used to
/// describe the arena a second time is gone. Move an `E` in the grid, re-run the tool,
/// and the respawn moves with it.
pub const ENTRANCES: [(i16, i16); 4] = [
    (512, 16), // tile (32, 1)
    (16, 512), // tile (1, 32)
    (992, 512), // tile (62, 32)
    (512, 992), // tile (32, 62)
];

/// Every entrance stands on floor in the table above.
///
/// The generator proves the same thing plus reachability, but only when someone runs it.
/// This fires on every `cargo check`, against the table that actually shipped -- and it
/// is also what keeps `ENTRANCES` from being an unread constant that quietly rots.
const _: () = {
    let mut i = 0;
    while i < ENTRANCES.len() {
        let (x, y) = ENTRANCES[i];
        let tx = (x / TILE) as usize;
        let ty = (y / TILE) as usize;
        assert!(
            x >= 0 && y >= 0 && tx < MAP_TILES && ty < MAP_TILES,
            "an entrance in map::ENTRANCES is off the map -- re-run tools/gen_map.py",
        );
        assert!(
            WALLS[ty] & (1u64 << tx) == 0,
            "an entrance in map::ENTRANCES lands in a wall -- redraw assets/map/arena.json \
             and re-run tools/gen_map.py",
        );
        i += 1;
    }
};
